arduino/arduino-ide

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
> RC – 2.0.0-beta.4

- arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
- arduino-ide-extension/src/browser/style/debug.css
- arduino-ide-extension/src/browser/style/index.css
- arduino-ide-extension/src/browser/theia/debug/debug-editor-model.ts
- arduino-ide-extension/src/browser/theia/debug/debug-hover-source.ts
- arduino-ide-extension/src/browser/theia/debug/debug-hover-widget.ts
- arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
> ATL-988, ATL-1068: Fixed missing ampersand in the menu. Made the debug hover slightly smaller.

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
> Updated to `2.0.0-beta.5`.

- .github/workflows/check-certificates.yml
We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.
Some improvements and standardizations have been made in the upstream "template" workflow, and those are introduced to this repository here.
---
NOTE: I have already added the required `SLACK_WEBHOOK` secret and will remove the unused `TEAM_TOOLING_CHANNEL_SLACK_WEBHOOK` secret from the repository once merged.
> Sync certificate check workflow with "template"

- .github/tools/fetch_athena_stats.sh
- .github/workflows/arduino-stats.yaml
- .github/workflows/github-stats.yaml
This PR adds workflows and related tooling to gather release downloads statistical data
> [skip changelog] Add stats workflow to gather downloads data

- arduino-ide-extension/src/node/core-service-impl.ts
> Remove gRPC errors codes from compile/upload console output

- README.md
Add link to Transifex project in `README.md` Contributions and development section.
> Update `README.md` with translations project link

- arduino-ide-extension/package.json
- yarn.lock
integrate latest version of the serial plotter
> bump serial plotter version

- arduino-ide-extension/src/browser/boards/boards-data-store.ts
> Fix board options not shown for manually installed platforms

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
Upgrading Arduino IDE version to rc4
> Upgrade version to rc4

- .github/PULL_REQUEST_TEMPLATE.md
Standardize the structure of arduino-ide PRs
added the `PULL_REQUEST_TEMPLATE.md` file
> add PR template file

- arduino-ide-extension/src/browser/create/create-api.ts
The remote sketchbook is limited to 20 sketches. It is needed to enable the pagination in order to get all the remote sketches.
Instead of doing just one call to retrive all the sketches, the component will keep calling the api with a window of 50 sketches per call. Untill it will get all of them.
> handling pagination in getting the sketches

- .github/ISSUE_TEMPLATE/config.yml
High quality issue reports are very valuable contributions to this open source project.
This repository's issue tracker is for the specific use of tracking defect reports and feature requests. 
Other communication channels are used for support requests and general discussion. The users and maintainers are best served if those channels are clearly indicated and easily accessible to ensure the best channel is used from the start.
GitHub has a nice feature that can be used for this purpose, which is set up here.
The automatically created issue template chooser provides a menu of links to the available [issue report templates](https://docs.github.com/en/articles/about-issue-and-pull-request-templates) as well as [the security policy](https://github.com/arduino/arduino-ide/security/policy) at …
> Add links for other communication channels to the GitHub issue template chooser

- arduino-ide-extension/package.json
> bump arduino-cli version to 0.24.0

- arduino-ide-extension/src/node/boards-service-impl.ts
Users have reported that selecting certain boards; for which a platform is not installed, erroneously fails to show an auto-install prompt.
Inverts the comparator used when sorting uninstalled packages, without affecting fqbn information in platform search results. Other changes are simple code quality cleanup.
> #979 fix platform installation prompt only made for boards listed in oldest release

- arduino-ide-extension/src/browser/style/sketchbook.css
The background of an element selected in the sketchbook needs to be updated.
Update CSS rule.
Before:
After:
> Update the background of a selected item in the sketchbook

- arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
> Avoid using useContentSize when creating a new window

- arduino-ide-extension/package.json
Use the latest available RC CLI.
> Use `0.25.0-rc2` CLI.

- arduino-ide-extension/package.json
Updates the Arduino CLI version to `0.25.1`.
No code change.
> Use `0.25.1` CLI.

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
Releasing version 2.0.0-rc9.1
Waiting for #1252 to be merged before releasing 2.0.0-rc9.1
> 2.0.0-rc9.1

- arduino-ide-extension/package.json
Pinned the [2dd8976](https://github.com/arduino/arduino-cli/commit/2dd8976683f4a9f83fcee478620f1e83d11111b2) CLI version in the IDE2 so that users can have the bugfix.
No code changes. Only the CLI version has been updated.
> Pinned `2dd8976` CLI in the IDE2.

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
> 2.0.0-rc9.2

- arduino-ide-extension/src/browser/contributions/compiler-errors.ts
- arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
- arduino-ide-extension/src/node/core-client-provider.ts
- arduino-ide-extension/src/node/core-service-impl.ts
- scripts/i18n/transifex-pull.js
Several of the log messages contained minor typos.
Fix the typos.
Originally reported by @sterretjeToo at https://forum.arduino.cc/t/rc9-2-ide-hangs-when-saving-a-new-sketch/1023314/2
> Fix typos in log messages

- arduino-ide-extension/package.json
To use the latest CLI from the `master`.
Ref: https://github.com/arduino/arduino-cli/commit/63f1e1855aa4c91415480be40fc49fd50d597e35
> Pinned 63f1e18 CLI.

- arduino-ide-extension/package.json
- browser-app/package.json
- electron-app/package.json
- package.json
Updated versions to `2.0.0-rc9.3`  for the release.
No code changes.
> Prepared `2.0.0-rc9.3`.

- arduino-ide-extension/package.json
Use the latest (`0.28.0`) CLI in IDE2.
> chore: Use `0.28.0` CLI in IDE2.

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
See https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#4-%EF%B8%8F-bump-version-metadata-of-packages
> Bump version metadata post release: 2.0.3

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
> Bump version metadata post release: 2.0.4

- .github/workflows/build.yml
- .github/workflows/check-i18n-task.yml
- .github/workflows/i18n-nightly-push.yml
- .github/workflows/i18n-weekly-pull.yml
- .github/workflows/themes-weekly-pull.yml
To support pinned arduino-cli in builds.
> Bump go version in workflow .yml files

- .github/label-configuration-files/labels.yml
As a contributor, I want to group issues and PRs if they are Arduino Cloud or cloud sketch related.
Updated the list of allowed GH labels.
> feat(infra): support for `topic: cloud` label

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
Bumped IDE2 version to `2.1.0`.
I have updated the `version` in the `package.json` files.
> chore: Prepared for the `2.1.0` release

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
To produce the correct nightly version, the IDE2 version should be updated after the release: https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#5-%EF%B8%8F-bump-version-metadata-of-packages
Updated from `2.1.0` to `2.1.1`
> chore: Updated to the next version after release.

- arduino-ide-extension/package.json
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts
- arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
Use the latest CLI release: `0.33.0`.
Updated the pinned version of the CLI and regenerated the JS/TS gRPC code for the CLI.
> chore(cli): Bumped the CLI version to `0.33.0`

- arduino-ide-extension/package.json
To fix a CLI-related defect on Windows: arduino/arduino-cli#2234
Updated the CLI version to [`0.32.3`](https://github.com/arduino/arduino-cli/releases/tag/0.32.3).
> chore(cli): Bumped the CLI version to `0.32.3`

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
It's required to update the minor version for the next release.
Moved from `2.1.2` to `2.2.0`
> chore: bump the version to `2.2.0`

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
[After-release procedure](https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) to produce correctly versioned nightly updates.
Updated the IDE2 version from `2.2.0` to `2.2.1`
> chore: update version to `2.2.1`

- arduino-ide-extension/package.json
Update the Arduino Firmware Uploader to `2.4.1`, including https://github.com/arduino/arduino-fwuploader/pull/216 for the Arduino Uno R4 board.
Update to `arduino-fwuploader@2.4.1`.
> chore: update to `arduino-fwuploader@2.4.1`

- arduino-ide-extension/package.json
- electron-app/package.json
- package.json
[After-release procedure](https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) to produce correctly versioned nightly updates.
Updated the IDE2 version from `2.2.1` to `2.2.2`
> chore: update version to `2.2.2`

- arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
Only run the tests when the OS throws the `EACCESS` error.
- Do not expect `EACCESS` on Linux.
- Run the test only if `EACCESS` occurs via the `stat` syscall.
> test: relax accessible sketch path test condition

- README.md
> adding a hyperlink to the README

- yarn.lock
> fix: update `yarn.lock`

- scripts/package.sh
> Added timeout to yarn install

- arduino-ide-extension/src/browser/theia/core/application-shell.ts
Resolves https://github.com/arduino/arduino-ide/issues/2679
Prevent `ApplicationShell` to set main window focus if revealed widget is `OutputWidget`
Although I wasn't able to reproduce the issue in Theia IDE Desktop v1.57.0, seems that the problem might be caused by a regression or an expected change in behaviour in Theia. To deal with the secondary window, Theia might prioritize the main one when `OutputWidget` is refreshed (see https://github.com/eclipse-theia/theia/pull/13493)
An issue will follow on Theia side after a deeper analysis or anything new is found.
> fix: prevent `OutputWidget` to gain focus when updated
