arduino/arduino-ide

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/workspace/workspace-variable-contribution.ts
Fall back to the current sketch, if `currentWidget` points to a file
outside of the workspace.
Closes: arduino/arduino-ide#46
How to test:
- You should be able to start/stop as many consecutive debug sessions from the toolbar as you pleased.
=> Fixed workspace variable resolver. Can start debug session multiple times from the toolbar.

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/browser/theia/debug/debug-configuration-manager.ts, arduino-ide-extension/src/browser/theia/debug/debug-configuration-model.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/node/sketches-service-impl.ts
What it does:
- This PR gets rid of the `sketch_folder/.theia/launch.json` and moves it to a temp folder.
Steps to reproduce:
- Create a sketch. Do not save it yet.
- Select a board that can debug.
- Compile and start the debug from the toolbar.
- Debug view open, you should see a config entry `Arduino`. You can open the config file in an editor. Hover over the editor tab of `launch.json`; it will point to some temp folder (`arduino-ide2-`).
- You should be able to re-launch the debug from the Debug view and toolbar as many times as you want.
- Save the sketch. (**Note:** the `Arduino` config is missing from the debug view! We need a solution for this in the future.)
- Compile and start the debugging. You should be able to restart the debug session from both the view and the toolbar.
- …
=> ATL-972: Moved the `./theia/launch.json` config into a temp folder.

arduino-ide-extension/src/node/grpc-client-provider.ts
Previously, when gRPC client creation failed, the incorrect error message was shown:
```
root ERROR Could create client for gRPC.
```
When the message is intended to have the opposite meaning.
---
Reference: https://forum.arduino.cc/index.php?topic=730720.msg4917491#msg4917491
=> Correct typo in gRPC client creation error message

README.md
The issue numbers changed when they were transferred from the `arduino/arduino-pro-ide` to `arduino/arduino-ide` repositories.
Previous issue:
https://github.com/arduino/arduino-pro-ide/issues/287
Now redirects to:
https://github.com/arduino/arduino-ide/issues/107
---
Supercedes https://github.com/arduino/arduino-ide/pull/146
=> Update ARM Linux link in download table

arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/style/main.css, arduino-ide-extension/src/browser/toolbar/arduino-toolbar.tsx
- We are missing hover and pressed state on the buttons, which can be confusing to users switching from Java IDE.
- The Java IDE has the buttons remain “activated” until an operation is carried out.
- We want the "Verify" and "Upload" buttons (and menu items) to be disabled while the corresponding operation is in progress.
- added "hover" behavior to all toolbar items, via CSS rule
- added "toggle" state to arduino toolbar buttons, by adding a prop, binded to the relative registry command. The `isToggled` function of the registry command was previously not called by Toolbar Items. I adopted the same mechanism used for `isEnabled`.
- set isToggled/isEnabled using an internal state updated by the verify and upload functions
[Jira Task …
=> [Toolbar] Hover style and Toggle State [ATL-1107][ATL-1045]

arduino-ide-extension/src/browser/contributions/examples.ts, arduino-ide-extension/src/browser/contributions/open-sketch.ts, arduino-ide-extension/src/browser/contributions/sketchbook.ts, arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts, arduino-ide-extension/src/common/protocol/examples-service.ts, arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/node/examples-service-impl.ts, arduino-ide-extension/src/node/sketches-service-impl.ts
This PR adds support for sketchbook subfolders.
FS State:
`Sketchbook` menu:
`Open` context menu. `libraries` are there, just like in the Java IDE.
Note: This PR does not expand the `examples` node from the `libraries`.
Java IDE:
IDE 2:
=> ATL-1064: Support for nested sketchbook structure

arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/library-service-server-impl.ts
From now on, we toast an error message and update the _Arduino_ output channel if the platform/lib installation has failed for whatever reason. 
I tested the changeset with the following 3rd party cores:
- https://github.com/watterott/Arduino-Boards/raw/master/package_watterott_index.json (checksum issue)
- https://raw.githubusercontent.com/eddieespinal/atmegazero/master/package_atmegazero_index.json (no unique root dir in archive)
- https://raw.githubusercontent.com/tenbaht/sduino/master/package_sduino_stm8_index.json (no unique root dir in archive)
- https://udooboard.github.io/arduino-board-package/package_udoo_index.json (no unique root dir in archive)
In-action:
https://user-images.githubusercontent.com/1405703/110629391-67248b80-81a4-11eb-8d18-cd6ec91b1539.mp4
Before this change: …
=> ATL-653: Added error handling for core/lib install

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/boards/boards-widget-frontend-contribution.ts, arduino-ide-extension/src/browser/library/library-widget-frontend-contribution.ts, arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/theia/debug/debug-frontend-application-contribution.ts, arduino-ide-extension/src/browser/theia/navigator/navigator-contribution.ts, arduino-ide-extension/src/browser/theia/search-in-workspace/search-in-workspace-frontend-contribution.ts, arduino-ide-extension/src/browser/theia/search-in-workspace/search-in-workspace-result-tree-widget.ts, arduino-ide-extension/src/browser/theia/search-in-workspace/search-in-workspace-widget.tsx
What it does:
- This PR integrates Theia's default `Search` view into the IDE2.
- From now on, the `Search` view is part of the default layout, so when the user opens a new sketch, the `Search` view (with the magnifier icon. the monitor widget has a similar icon 😕) should be visible on the left sidebar.
- This PR changes the order of the widgets on the left: `Board Manager`, `Lib Manager`, `Debug`, `Explorer` (this is hidden), `Search`, and `Outline` is the order. Then the rest of the views, if any.
- This PR changes the default width of the sidebar views. When you open the view, it should require 200px width. It was 100px before. I thought increasing the width is a good thing, whenever I open a view, I have to change the horizontal …
=> ATL-1063: Integrated search in workspace into IDE

arduino-ide-extension/src/node/sketches-service-impl.ts
This PR fixes the recursive folder creation on non-POSIX filesystems when saving a sketch as anything into the current sketch folder. Unlike the Java IDE, the new IDE does not prevent the entire `Save As...` operation; one can save a sketch as anything into the current sketch folder. Please review.
Closes #65.
=> ATL-941: Fixed recursive folder issue on `Save as`

.github/workflows/build.yml, .github/workflows/check-certificates.yml, BUILDING.md, electron/build/scripts/notarize.js
This PR supersedes https://github.com/arduino/arduino-ide/pull/208 and comes from a fork of this repo in order to test the workflow update it contains.
The purpose of this PR is to refactor the CI workflows to be more "fork friendly".
If workflows are run on a PR generated by a fork, where secrets are not available, the CI will run skipping the signing steps, providing unsigned artifacts.
What this PR does:
- Skip Mac/Win code signing and Apple notarization only if PR comes from a fork
- Disable workflows entirely if the user enabled Github Actions in
their fork repo
- Add steps to help Mac users to test their forked code in BUILDING.md
=> ATL-1119 Disable code signing when workflows run from forks

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
A gear icon is shown prominently in the side bar
This PR removes the gear icon from the sidebar
[Jira Task](https://arduino.atlassian.net/browse/ATL-959)
Github Issue: fixes #15
=> [ATL-959] Remove settings icon from sidebar

arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/contributions/add-zip-library.ts, arduino-ide-extension/src/browser/output-service-impl.ts, arduino-ide-extension/src/browser/settings.tsx, arduino-ide-extension/src/browser/style/settings-dialog.css, arduino-ide-extension/src/browser/toolbar/arduino-toolbar-contribution.ts, arduino-ide-extension/src/electron-main/splash/splash-screen.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/monitor/monitor-service-impl.ts, arduino-ide-extension/src/node/notification-service-server.ts, arduino-ide-extension/tslint.json, browser-app/package.json, electron-app/package.json
While the auto complete functionality will be extremely useful to advanced users, the low level code it exposes constantly while typing will be confusing and distracting to beginners.
This PR disables by default the editor quick suggestion, adding a checkbox in the arduino preference panel to enable it.
[Jira Task](https://arduino.atlassian.net/browse/ATL-960)
Github Issue: fixes #17
=> [ATL-960] Disable editor quick suggestion

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/style/main.css, arduino-ide-extension/src/browser/toolbar/arduino-toolbar.tsx
Creating another PR as I accidentally merged #190 
This PR is an amend to the previous one, containing fixes after @kittaakos review
I Will **squash merge** this PR into main once the review is over, in order to have a single commit on the main branch
=> [ATL-1107][ATL-1045] Verify/Upload Buttons Hover & "running" style

arduino-ide-extension/src/browser/contributions/examples.ts
simple solution for issue #185
=> Fixed sorting of sketches and examples - ignore case

.github/workflows/build.yml
Previously, a single workflow artifact was created by the "Arduino IDE" GitHub Actions workflow. This artifact contained
the builds for each operating system, including all three versions of the Windows build. This resulted in beta testers
needing to do a >1 GB download for every build, even though they likely needed only ~200 MB of what they downloaded.
Producing separate workflow artifacts makes it easier for beta testers to participate in the development and is less wasteful of
resources.
=> Create separate tester artifacts for each build

BUILDING.md
The "Arduino IDE" workflow was updated to produce individual artifacts for each operating system (https://github.com/arduino/arduino-ide/pull/256), but the development documentation was not updated accordingly at that time.
=> Update development documentation to reflect change in workflow artifacts

electron/build/template-package.json, package.json
=> ATL-1150: Bumped the `cortex-debug` to `0.3.10`.

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/settings.ts, arduino-ide-extension/src/browser/menu/arduino-menus.ts, arduino-ide-extension/src/browser/theia/keymaps/keymaps-frontend-contribution.ts, arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts, browser-app/package.json, electron-app/package.json, yarn.lock
The default keybindings may be reasonable for beginners, but PRO users expect the keybindings to be customizable, as they are in other editors.
In this PR:
- add the `theia/keymap` packages that let users change the default keybindings to their preference (see image below)
- refactor the settings menu: from a single entry it's now submenu containing both the settings and the keymap actions to open the relevant functionalities (see images below)
(window version)
=> ATL-1118: Add keymaps customization support

arduino-ide-extension/src/common/protocol/sketches-service.ts
This PR  add support to create and view `.md` and `.adoc` files in IDE2. It also fix .S file extension (see #218 )
> Note: this PR alone do not solve the fact the IDE2 do not open automatically .md and .adoc files belonging to a sketch. That will be handled in a separate PR addressing [ATL-1152](https://arduino.atlassian.net/browse/ATL-1152)
- open IDE2
- create a new tab using the top right button
- give it a name and and extension `.md` or `.adoc`
[ATL-1136](https://arduino.atlassian.net/browse/ATL-1136)
fixes #218
=> ATL-1136: Add .adoc and .md file support

.github/workflows/build.yml
=> GH-259: Use Ubuntu `18.04` for the build job.

arduino-ide-extension/src/browser/style/main.css
The active area for the new tab button is very small.
This PR expands the active area by moving the padding from the container of the button to the button itself.
Padding changed because of the actual size of the chevron icon in the button.
___
Fixes #97 
[Jira Task](https://arduino.atlassian.net/browse/ATL-1128)
=> ATL-1128: make the new tab button easier to click

.vscode/launch.json, arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts, arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/grpc-client-provider.ts, arduino-ide-extension/src/node/monitor/monitor-service-impl.ts
=> ATL-1137: Show error when could not connect to CLI

arduino-ide-extension/src/browser/contributions/burn-bootloader.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts
With this PR I set the timeout of the following notification to 3 seconds (like other notifications in the IDE)
- burn bootloader
- verify sketch
- upload sketch
=> ATL-970: notification to last longer

arduino-ide-extension/src/browser/settings.tsx
We want the settings preference panel to reflect the actual state of the application. Even if command palette commands change the status bypassing the preference panel UI.
- reload the preference before opening the preference panel dialog
[Jira task](https://arduino.atlassian.net/browse/ATL-1151)
Demo:
https://user-images.githubusercontent.com/1636933/112849916-d1489600-90a9-11eb-9148-017c1c17d131.mov
=> ATL-1151: settings panel to reflect actual state

arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/theia/git/git-init.ts
This PR does one thing: it suppresses the error message when the Git executable is not on the `$PATH`.
How to verify: this is an interesting part, I did the straightforward way and renamed all my Git executables to something else so that `git version` fails from a terminal. I renamed the followings:
- `C:\Program Files\Git\cmd\git.exe`,
- `C:\Users\my_name\scopes\shims\git.EXE`, and
- made sure `/mingw64/bin/git` (for Git Bash) also not accessible.
Once you have a setup without git on the `$PATH`, start the app. You should not see any errors.
=> ATL-1145: Suppress error if Git is not on `$PATH`.

arduino-ide-extension/src/browser/settings.tsx
The previous text used past tense, which is not appropriate for a button.
Credit to Arduino Forum user "arduinoshop":
https://forum.arduino.cc/t/ide-2-0-beta-4-ubuntu-21-04-first-time-install/847777/10
=> Correct sketchbook folder selection button text

arduino-ide-extension/src/browser/data/arduino.color-theme.json
This PR fixes the following colors:
- constant and double quoted strings (as they are constants) have the same color (dark teal color)
- function / methods (orange)
Tasks: 
Fixes [ATL-1222](https://arduino.atlassian.net/browse/ATL-1222)
Fixes #291
=> [ATL-1222] fix editor colors

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/common/protocol/config-service.ts
Language server: pass a flag to set arduino-cli config file
- get the cli config path
- pass it to the language server
**In order to test this PR you have to manually install the updated `vscode-arduino-tools` plugin (recommended) or wait for it to be built in the nightly** 
So you are bold enough to try with the manual test, aren't you?
-> Unzip the following file in the `.plugins` directory of arduino-ide, replacing the existing `vscode-arduino-tools` dir (see screenshot)
[vscode-arduino-tools.zip](https://github.com/arduino/arduino-ide/files/6426153/vscode-arduino-tools.zip)
- Task [ATL-1247](https://arduino.atlassian.net/browse/ATL-1247)
- vscode-arduino-tools [PR](https://github.com/arduino/vscode-arduino-tools/pull/25)
=> [ATL-1247] Language Server now requires an additional cliConfigPath

arduino-ide-extension/scripts/download-examples.js
A new release is available for the example sketches provided via the IDE's **File > Examples > Built-in examples** menu.
- https://github.com/arduino/arduino-examples/releases/tag/1.9.1
- https://github.com/arduino/Arduino/pull/11519
=> Use latest release of built-in examples

.eslintrc.js, package.json, yarn.lock
tsc complains about unused imports, stopping the builds in the CI. We want to catch unused imports asap.
Eslint supports unused-vars rule, but this appears to be too strict for our usecase. We need to catch imports *only*, and possibly auto-fix those before committing.
[eslint-plugin-unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports) integrates with eslint, detecting unused imports and removing them from the codebase. This automaically integrates with husky/lint staged that are already in place
=> eslint to fix unused imports

arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget-contribution.ts
Reveal sketchbook directory in explorer/finder is not working. This is caused by the `node.id` not being a valid URI.
Correctly parse the `node.uri` to a valid, independent, path, via `fileService.fsPath`. Then use `remote.shell.openPath(fsPath);` to open the sketch directory
Jira Task:
- [[sketchbook] Open in folder on windows does not work](https://arduino.atlassian.net/browse/ATL-1451)
=> ATL-1451: reveal sketch directory in file explorer

arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-model.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget-contribution.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
Need to improve the user experience when working on local files.
- As a user, I expect the current file I'm working on in the Editor to be highlighted in the sketchbook explorer
- As a user, I expect the local sketchbook explorer to reflect changes happening in the file system. Eg: I expect to immediately see freshly added/renamed/deleted files in the sketchbook explorer tree
- Refactored the sketchbook tree to use a single root node which contains a child for every directory in the `Arduino` user directory
- Re-create the node tree when changes in either Monaco/FileSystem happens. This let us update the sketchbook treen when files are added-removed to directories as well as selecting the current focused file in the Monaco editor
- Removed useless re-renders of the sketchbook explorer …
=> Improve local sketchbook tree

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/browser/create/create-fs-provider.ts, arduino-ide-extension/src/browser/create/create-uri.ts, arduino-ide-extension/src/browser/create/typings.ts, arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketch-cache.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-contributions.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-model.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-widget.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-model.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget-contribution.ts
A major re-design of the sketchbook tree is needed in order to enable a number of features.
- improved performances when refreshing the sketch tree. Resources are now loaded *on demand* meaning you will notice a short delay when opening a directory for the first time. A caching system is in place in order to make subsequent actions more quick
- The sketchbook tree highlights the file currently marked as "active" in the editor. The containing folders are automatically expanded if closed, in order to help the users immediately see the location of the files they are working on
- Creating a file in the local file system automatically adds it to the sketchbook tree and make it selectable. This is required in order to allow creation/removal/rename of files in the "local copy" of a remote …
=> Improve remote sketchbook tree

arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-contributions.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
When opening a sketch in the Cloud editor through the contextual menu in the Remote Sketchbook, the user is redirected to the wrong URL.
It should link to: “create.arduino.cc/[USERNAME]/[SKETCH_ID]”
But right now it links to: “create.arduino.cc/[SKETCH_ID]”  
Which results in the editor opening the first sketch in the list
Pass the username as an argument when executing the command to open the contextual menu.
=> Fix url to open sketch in cloud editor

arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
We need to force some files (`"thingProperties.h"`) to be read-only, even if they are downloaded on the user's machine
Use an array of read-only files and add a simple check in the `isReadOnly()` function.
=> [ATL-1435] Force some files to be read-only

arduino-ide-extension/package.json, arduino-ide-extension/scripts/download-fwuploader.js, arduino-ide-extension/src/node/executable-service-impl.ts
We need to bundle the firmware uploader into the IDE2
- added download script
- updated `package.json` accordingly
- exposed the fw uploader executable  via `executable-service-impl.ts`
=> [ATL-1539] Integrate FWUploader into IDE2

arduino-ide-extension/src/browser/contributions/board-selection.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts
Add `{in Sketchbook)` label to manually installed board packages.
Should solve #126
=> [ATL-493] Support platforms installed in directories.user

arduino-ide-extension/README.md
I believe this file name " path src/node/monitor-service-impl.ts " was moved into another folder named monitor, making the correct path for this file here "src/node/monitor/monitor-service-impl.ts"
=> 404 error solved

arduino-ide-extension/src/browser/settings.tsx
We were getting `quickSuggestion` instead of `quickSuggestions` :')
=> [ATL-1571] Fix editor quick suggestions preference

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
Use `LocalStorageService` to know if it's the first IDE startup, and in that case launch `arduino:avr` installation.
=> [ATL-1294] At first ide startup invoke installation of arduino:avr

.github/ISSUE_TEMPLATE/bug_report.md, .github/label-configuration-files/labels.yml, .github/workflows/sync-labels.yml
On every push that changes relevant files, and periodically, use [github-label-sync](https://github.com/Financial-Times/github-label-sync) to configure the repository's issue/PR labels according to the universal, shared, and local label configuration files.
Preview of the changes that would be made if merged:
https://github.com/arduino/arduino-ide/pull/515/checks?check_run_id=3702301590#step:9:15
=> Add CI workflow to synchronize with shared repository labels

.vscode/launch.json, arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/boards/boards-auto-installer.ts, arduino-ide-extension/src/browser/contributions/add-zip-library.ts, arduino-ide-extension/src/browser/response-service-impl.ts, arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx, arduino-ide-extension/src/common/protocol/installable.ts, arduino-ide-extension/src/common/protocol/response-service.ts, arduino-ide-extension/src/test/browser/boards-auto-installer.test.ts, arduino-ide-extension/src/test/utils.ts, package.json, yarn.lock
The first step for enabling us to implement unit tests on the frontend. Simply run `yarn test` 😄 
We decided to use [typemoq](https://github.com/florinn/typemoq) in order to mock our injectable services.
While doing the tests, we noticed the `ResponseService` were not being injected correctly as we were injecting `ResponseServiceImpl` directly and this was causing troubles, so we created a new interface `ResponseServiceArduino`.
=> Implement unit tests for boards-auto-installer

.github/workflows/check-i18n-task.yml, .github/workflows/i18n-nightly-push.yml, .github/workflows/i18n-weekly-pull.yml, i18n/en.json, package.json, scripts/i18n/transifex-pull.js, scripts/i18n/transifex-push.js, scripts/i18n/transifex.js, yarn.lock
Add four `yarn` commands:
* `i18n:generate` to generate the source json file that contains all translatable strings
* `i18n:check` to verify that the source json file is updated with new strings
* `i18n:push` to push source file json file to Transifex
* `i18n:pull` to pull translation files from Transifex
Also add three new workflows:
* `check-i18n-task.yml` to verify that each PR updates the source json file in `i18n` if necessary
* `i18n-nightly-push.yml` to push source file json file to Transifex each night
* `i18n-weekly-pull.yml` to pull translation files from Transifex each Monday
The workflow currently in use in the [arduino/arduino-cli](github.com/arduino/arduino-cli) repo is not usable for this project since the release process is different.
=> Add commands and workflows to handle translations

arduino-ide-extension/src/browser/contributions/save-sketch.ts, arduino-ide-extension/src/node/sketches-service-impl.ts
Closes arduino/arduino-ide#64
This is my first contribution to arduino-ide, please let me know if anything is missing.
=> Open Save as... dialog when saving sketches for the first time

browser-app/package.json, electron-app/package.json
In the last update of Theia we included breadcrumbs just below the tab name. This is an optional feature that we do not plan to support, hence needs to disabled by default. Advanced users can still enable breadcrumbs using the **unsupported** theia preferences via theia preference panel.
Set the breadcrumbs to be disabled by default
=> Disable Breadcrumbs

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/theia/core/shell-layout-restorer.ts
After the latest Theia inclusion, tabs order gets scrambled. This is particularly true when the Sketch has multiple .ino files and/or a file different from the main .ino file was selected the last time the sketch was opened
- Changed the cleanup script that finds duplicated tabs in monaco
- removed the now useless force open on the main .ino file. This was actually causing the issue as forcing the open of the file that was already opened caused the close of the original one and a new open in the last position
=> Fix tabs ordering

arduino-ide-extension/src/browser/settings.tsx
Remove the `Enable language server logging` option in the preferences
This option was needed in the early development and testing phase of the Arduino Language Server. However, this is not something the target user will ever have a need for, so it only makes the IDE less friendly.
=> Remove language server log preference

arduino-ide-extension/src/browser/serial/monitor/monitor-view-contribution.tsx, arduino-ide-extension/src/browser/serial/serial-connection-manager.ts, arduino-ide-extension/src/browser/theia/messages/notification-center-component.tsx, arduino-ide-extension/src/browser/theia/messages/notification-component.tsx, i18n/en.json
Notifications have broken icons
Use codicons to restore icons in the notification center
fixes #531
=> fix notification icons

arduino-ide-extension/src/browser/contributions/burn-bootloader.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/node/core-service-impl.ts, i18n/en.json
Compilation error before:
Upload error before:
Compilation error after: 
Upload error after:
Fixes #151.
=> Remove gRPC error code from error notifications

arduino-ide-extension/package.json, arduino-ide-extension/scripts/download-ls.js, arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/common/protocol/arduino-daemon.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/grpc-client-provider.ts, arduino-ide-extension/src/test/node/arduino-daemon-impl.test.ts
It's not possible to make assumptions on what ports are available on the different OS the IDE can be run, and the default port 50051 is already in use in some cases (such as OS Monterey).
This issue is particularly annoying for first-time users that should go into the CLI configuration and change the port manually, before running the IDE.
The IDE now force the CLI daemon port to `0` (automatically assigned from the OS). This ensure an available port is always picked up and the IDE can start normally, without manual intervention of the user
=> IDE to run CLI with auto assigned port

arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/library-service-server-impl.ts
After installing a board/library the discoveries are be broken: plugging or unplugging a board has no effect on the UI.
This issue is 100% reproducible on windows and a minority of mac users are affected as well.
The reason is that, in some circumstances that need to be further investigated, the CLI is not sending the `quit` or `end` message when an install/uninstall action is perfomed. ( cc @silvanocerza )
This causes the IDE not to restart the watchers on the board discoveries when needed (as it's never been informed they ever stopped).
Being the watchers broken, the UI do not react to changes that communicated (correctly) from the CLI.
This workaround perform a stop of the discoveries from the IDE side before any install/uninstall operation.
Calling the stop from the IDE actually fixes …
=> workaround: stop discoveries before install/uninstall boards/libs

arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts
=> Close serial port connection before flashing firmware

arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
currently, lines plotted to the serial plotter have fixed height, as a this is required for the virtual scroll to work properly and guarantee good performance.
This causes longer lines to wrap and overflow over the line below, causing a glitch in the ui (see picture)
Setting the `white-space: nowrap;` property fixes the issue allowing the whole panel to scroll horizontally
=> Serial monitor lines not to wrap lines

arduino-ide-extension/src/browser/create/create-api.ts
IDE2 currently converts larger files to uint8arrays. When a file is then pushed to the cloud it needs to be conferted back to a string.
This process fails miserably, as we are trying to use `new TextDecoder().decode(content)` which is broken in the electron version used by theia (https://github.com/electron/electron/issues/18733)
Replace `new TextDecoder().decode(content)` with `new util.TextDecoder().decode(content)`
=> Correctly transform uint8array to string

BUILDING.md
Improve build instruction based on feedback from the community: https://forum.arduino.cc/t/build-question-about-old-node-module-requested-by-package-json/936228
=> Improve build instructions

docs/internal/Arm.md, docs/internal/Ubuntu.md
The original location of the project repository was `bcmi-labs/arduino-editor` and some of the internal development documentation for the project contains references to the repository.
This documentation was not updated at the time the repository was moved to the current home in `arduino/arduino-ide`.
Fixes https://github.com/arduino/arduino-ide/issues/388
=> Update development docs for current repository

arduino-ide-extension/src/node/core-service-impl.ts
An extra brace [was inadvertently introduced](https://github.com/arduino/arduino-ide/commit/5ddab1ded74a0fe74cd5350579dc60a6327f4940#diff-620225c1911f715af828b254eb226f590cea42b7787c5f5941d38f115924a3e1R95) into a template literal used to format output text in the event of an error
during compilation. This caused the text to end in a pointless `}`
For example, compiling this sketch:
```cpp
#error
void setup() {}
void loop() {}
```
Previously produced this output:
```
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2022014-9692-1u5eon9.v425\sketch_jan14a\sketch_jan14a.ino:1:2: error: #error 
#error
^~~~~
Compilation error: exit status 1}
```
After this change, the output text is as expected:
```
C:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2022014-9692-1u5eon9.v425\sketch_jan14a\sk …
```
=> Remove stray brace from compilation error output

.github/workflows/build.yml, .github/workflows/compose-full-changelog.yaml, arduino-ide-extension/package.json, arduino-ide-extension/scripts/compose-changelog.js, package.json, yarn.lock
This PR adds a `compose-changelog` script to create a changelog containing all versions of the `arduino-ide` project released on Github.
Calling this `yarn run compose-changelog changelog.md` from the project root will create a `changelog.md` file in the `arduino-ide-extension` folder since it's used as working directory.
This also updates the release process to generate the changelog and upload it to AWS S3, a manifest `latest.txt` file is also uploaded containing the name of the latest changelog available. 
The generated changelog file is formatted like so `<tag_name>-<iso-8601-date>.md`, for example `2.0.0-rc3-2022-01-26T15:55:46+01:00.md`.
Changelog and manifest are uploaded to `https://downloads.arduino.cc/arduino-ide/changelog/`.
=> Add script to create historical changelog

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/contributions/board-selection.ts, arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx, arduino-ide-extension/src/browser/serial/serial-connection-manager.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/serial/serial-service-impl.ts, arduino-ide-extension/src/test/browser/fixtures/boards.ts, arduino-ide-extension/src/test/node/serial-service-impl.test.ts
Fix ports not being stored correctly causing ports found by multiple discovery with same address but different protocol conflicting with each other and not being shown correctly in Board Selector dropdown list and Select Board dialog.
Ports separation in Tools > Ports menu is unchanged.
Fixes #711.
=> Solve ports conflicts with same address and different protocol

arduino-ide-extension/src/browser/boards/boards-service-provider.ts
This is the same as  #765, which was closed since it was a PR on a branch that got merged. @silvanocerza asked for this PR to get rebased on the latest main, so here it is. Please let me know if you need any changes / cleanups, etc.
The original description is:
Currently, when a user selects Board A, and Port B, when that device disconnects, the IDE searches for a 'similar' port to connect to. For reasons I don't fully appreciate [^1] some boards when they disconnect and reconnect, they reconnect on a different port. So when the IDE searches for a similar port, it first searches for an exact match. But if that fails, it then searches for a match on FQBN-name pairs only and ignores the port. 
Unfortunately, when the user selects Board A, then any port that isn't known to the IDE is listed …
=> When selecting new port that matches board type, also check match of protocol

arduino-ide-extension/src/browser/arduino-workspace-resolver.ts, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Closes arduino/arduino-ide#384
Stores sketches which were closed immediately before the application closed in the `electronStore` of the main app. When restarting the application, the sketches are loaded and a dedicated window is launched for each of them.
The fix needs some special treatment for Windows. Due to my local setup, I was not able to test this on a POSIX system. although I'm quite certain it should work there as well.
=> Restore open sketches on startup

arduino-ide-extension/src/node/grpc-client-provider.ts
This PR adds the `arduino-ide/<version>` User Agent as the primary UA when connecting to the CLI gRPC daemon.
Closes #790.
=> Add gRPC user agent

arduino-ide-extension/src/node/grpc-client-provider.ts
Wrong import in code run in `node` process was causing the IDE not to start.
This happened because the `node` process doesn't have access to the defines found in the `electron` process, thus we had to find a different way of getting the version information.
Fixes #836.
=> Fix version retrieval in node process

.github/workflows/build.yml, electron/packager/config.js, electron/packager/index.js, electron/packager/utils.js
The process that generates the updater channel files is broken in the CI
Move the renaming of the channel files (`beta*.yml` and `latest*.yml` into `nightly*.yml` and `stable*.yml`) inside the electron [packager script](https://github.com/arduino/arduino-ide/compare/fix-updater-ci?expand=1#diff-715843d959de89fd225385052931f6ff41bdf90ac5a9e18c3f876a789561a1abR346-R358). 
Apparently, electron-builder doesn't allow custom channels, so the only channels available are `alpha`, `beta` and `latest`. Since we want to use different channel names (`stable` and `nightly`) we need to rename the channel files after the packaging of the app.
=> Fix generation of update channel files in CI

arduino-ide-extension/src/browser/dialogs/settings/settings.tsx
Closes #830
For some reason, you cannot save preferences in parallel. I assume this is due to https://github.com/eclipse-theia/theia/pull/10562, but I'm not 100% sure. I'll create an issue in the Theia repo as well. But for now, this works fairly well.
This also adds an additional guard to the `window.reload()` when changing the preferences to not reload the app when the `nls.locale` variable is undefined (this indicates that the app runs in English).
=> Save preferences in sequence

electron/packager/index.js
During the generation of the `stable-mac.yml` and `nightly-mac.yml` files, electron builder duplicates the number of entries for dmg files.
This PR fixes the issue, removing the duplicated files using the sha512 as a key.
=> Avoid duplicated yaml entries

electron/build/template-package.json, package.json
vscode-arduino-tools used to have restrictive file permissions, that break the update process on mac.
This PR updates vscode-arduino-tools to the last version, which is more permissive
=> Bump vscode-arduino-tools to v0.0.2-beta.2

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, electron/build/template-package.json
Closes #72
Closes #370
Closes #293
I needed a workaround to make MacOS wait for the `open-file` event, which is accomplished using the `openFilePromise`. However, I can't test this on Mac currently, so please get back to me if does not work correctly on Mac :)
=> Enable opening the IDE from finder/explorer

arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
Fixes #848 
- moved updater files to proper location
- Autoupdater forced to download only after user confirmation
=> Disable autodownload of updates on startup

.github/workflows/build.yml, arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts, arduino-ide-extension/src/common/protocol/ide-updater.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
Checking for updates should happen only once at startup.
Right now, every time a new sketch is open (that is, every time an electron renderer process is instantiated) a check for updates is performed. Since we don't want to flood the users with unnecessary dialogs, we need to show it only on the first sketch they open.
Add a flag to check if an initial check has already been performed
=> Automatically check for updates only once

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/common/protocol/ide-updater.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
We want to have a way to test the automatic update feature when downloading a build from a PR.
Add the possibility to change the URL the updater uses to know if there are updates and to download them. This way, anyone could start a local server that serves the files needed for the automatic update and fool the updater to make them think there is a new update to download.
This is necessary because a PR build of the Arduino IDE will generally be a newer version than the current latest version, so it's difficult to test before merging.
=> Add preference to set a custom update url

arduino-ide-extension/src/browser/theia/workspace/workspace-service.ts
On macOS, you can [set a represented file](https://www.electronjs.org/docs/latest/tutorial/represented-file) for any window in your application. The represented file's icon will be shown in the title bar, and when users CMD/CTRL+Click, a popup with a path to the file will be shown.
Use [BrowserWindow.setRepresentedFilename](https://www.electronjs.org/docs/latest/api/browser-window#winsetrepresentedfilenamefilename-macos) whenever the file selected in the editor changes.
=> show represented file on MacOS

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx, arduino-ide-extension/src/browser/style/ide-updater-dialog.css, arduino-ide-extension/src/common/protocol/ide-updater.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts, i18n/en.json
Errors happening during the automatic update aren't handled properly. 
Whenever an error happens during the automatic update occurs, show a link to the download page to let the user download the IDE by themselves.
=> Go to download page when automatic update fails

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/contributions/help.ts, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx, arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts, arduino-ide-extension/src/common/protocol/ide-updater.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts, i18n/en.json
IDE updater commands are not working how expected. They work, but they are not giving any feedback to the user.
Remove useless commands. Leave only the "Check for Arduino IDE updates" command. When launching this command, if there is an update available, it opens the update dialog. If there isn't any update available or some error occurs, it shows a notification message.
=> fix IDE updater commands

.github/workflows/compose-full-changelog.yaml
**Compose full changelog** workflow [is failing](https://github.com/arduino/arduino-ide/actions/runs/1922676001) because we're not installing the correct version of Node.
Add a step to install the correct version of Node.
=> Install Node.js 14.x on compose-full-changelog workflow

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Closes https://github.com/arduino/arduino-ide/issues/829
The original Theia code contains a new IPC signal `RELOAD_REQUESTED_SIGNAL`, which wasn't used in the Arduino IDE.
=> Override the `RELOAD_REQUESTED_SIGNAL` correctly

.github/workflows/compose-full-changelog.yaml
The "Compose full changelog" GitHub Actions workflow generates a changelog file from [the release notes](https://github.com/arduino/arduino-ide/releases/latest) and uploads this to Arduino's server for display to the user by [the IDE updater](https://github.com/arduino/arduino-ide/pull/797).
Previously, this workflow could be [triggered](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on) by either of two types of [`release` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release):
- Release creation
- Release edit
To reduce the possibility of endless recursion, GitHub Actions ignores events which are triggered using the auto-generated [`GITHUB_TOKEN` access …
=> Remove irrelevant trigger from "Compose full changelog" workflow

README.md
Linux x86-64 builds of the Arduino IDE are now available in [AppImage format](https://appimage.org/) in additional to the previous ZIP format (https://github.com/arduino/arduino-ide/pull/846).
Since only the AppImage format IDE supports auto-updates (the IDE installed from the ZIP will notify of available updates, but can't auto-update), this will be the preferred format and so good beta testing coverage of it is especially important.
Add Linux x64-64 AppImage option to the "**Nightly builds**" download link table in the readme.
=> Add Linux AppImage to nightly build download links

arduino-ide-extension/src/node/sketches-service-impl.ts
Newly created sketches share the same auto-generated name #593 
Improve the function to generate the suffix of the sketch name.
Use a variable to count the number of sketches created today to prevent useless access to the file system
=> Fix sketch name duplicates

arduino-ide-extension/src/browser/contributions/help.ts
The "Help" menu contains the item "Toggle Developer Tools". In this case, "developer" is referring to the developer of the IDE itself. Those using the IDE to develop Arduino sketches will not find this to be useful in any way, so it only adds unnecessary complexity to the primary UI of the IDE.
Solves #650 
Unregister the dev tools menu item, which is automatically registered by a Theia module.
=> Remove dev tools menu item

electron/build/resources/eula.txt
When using the interactive installer, the user is presented with a dialog requesting they agree to this:
The previous statement about initiation of a download constituting agreement is relevant in the context of [the text's source on the arduino.cc downloads page](https://www.arduino.cc/en/software#terms-of-service), but not at all in the context of the installer dialog.
Remove the irrelevant statement
=> Remove irrelevant statement from EULA

arduino-ide-extension/src/browser/contributions/help.ts, i18n/en.json
We need to add a link to our [Privacy Policy](https://www.arduino.cc/en/privacy-policy)
=> Add privacy policy menu item

.github/workflows/compose-full-changelog.yaml, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts
The changelog in the update dialog is not displayed correctly.
- Workflow to compose changelog is failing because `octokit` is not installed, so we just install it
- Fix the string that searches for the current version in the changelog
=> Install oktokit in changelog workflow

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
Closes https://github.com/arduino/arduino-ide/issues/648
Listens to any changes of open editors and removes them if the `type` indicates that the underlying file has been deleted.
=> Automatically remove editors for deleted files

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/theia/core/application-shell.ts, arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts
Closes https://github.com/arduino/arduino-ide/issues/552
Removes all contributed commands which programmatically enable users to split editors. Also disables widget dragging so that it's not possible to split editors that way. I believe the dragging functionality hasn't been used anyway?
=> Disable widget dragging/splitting

electron/build/template-package.json
Arduino IDE is packaged for Windows in multiple formats:
- ZIP
- [NSIS](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System)
- [Windows Installer](https://en.wikipedia.org/wiki/Windows_Installer) (AKA "MSI")
The interactive installer of the NSIS package makes it the best option for installation by users.
The other use case for the installers is deployment by a system administrator. The Windows Installer package was added to offer an additional installer option for this specific use case.
Previously, the Windows Installer package was configured to start the Arduino IDE after completing the installation. That behavior is likely to be problematic for the very use case the Windows Installer package is intended for, where a "silent install" will often be required …
=> Disable automatic application start after install via Windows Installer

arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
When printing output to the serial monitor, some characters are not being rendered as expected. For example, tabs are rendered like normal whitespaces (#675). This is caused by how HTML treats these kinds of characters.
Wrap each serial monitor message inside a `<pre>` element.
fixes #675
=> Correctly print backslash-escaped characters

arduino-ide-extension/src/browser/utils/constants.ts, arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts
The condition to check if a sketch must be shown in read-only mode is too mild. For example, a `thingProperties.h` file shouldn't be read-only if it's not inside an IoT sketch
Check if it's an IoT sketch.
=> Improve condition to recognise read-only sketches

arduino-ide-extension/src/browser/dialogs/settings/settings.tsx
Attempt to solve #948 
fixes #948
Execute the command `ElectronCommands.RELOAD` instead of running calling `window.location.reload();`
=> Use electron reload command when changing language

arduino-ide-extension/src/browser/dialogs/settings/settings.tsx, arduino-ide-extension/src/node/arduino-daemon-impl.ts
The English language gets forgotten when changing the language.
Solves #956 
Set the language to the localization provider
=> Set the current language on the localization provider

arduino-ide-extension/src/browser/theia/core/application-shell.ts
Closes https://github.com/arduino/arduino-ide/issues/866
Closes https://github.com/arduino/arduino-ide/issues/831
When adding a widget to the tracker we first try to see whether it is contained in one of our `ignoreFolders` (`.vscode`, `.theia` and `src` so far). If it is, we allow it to stay closable.
=> Allow to close files in certain folders

.github/workflows/compose-full-changelog.yaml
This line was making the changelog workflow fail
https://github.com/arduino/arduino-ide/compare/fix-changelog?expand=1#diff-1c6c9545ae4f7be1b70ffe6ab6a047db3a73f2053f914068cb78258a77cae818L35
=> Remove useless step in changelog workflow

arduino-ide-extension/src/browser/contributions/save-as-sketch.ts
Closes https://github.com/arduino/arduino-ide/issues/896
Invokes the `saveAll` operation of the `ApplicationShell` before saving the sketch to a new location.
This saves any unsaved changes to the current sketch as well. Is this alright with the usability concept? Or should the new changes exclusively be saved to the new sketch? (this would be a bit more involved)
=> Save all open editors before running `Save As`

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
[GitHub issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) are used in this repository to facilitate the creation of high quality issues. These provide input fields for each of the distinct classes of information which will be essential for the evaluation of the issues.
One of these fields is for the user's operating system. A dropdown menu is used for the selection of the high level operating system type. Previously this only permitted the selection of a single option. A devoted contributor might have made the effort to determine that the issue applies to multiple operating system types only to be met with the inability to provide this information via the …
=> Allow flexibility in OS type selections in issue forms

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx
This PR restores the missing `inject` decorator to
- fix the error thrown at startup,
- fix the editor tab open/close when sketch files are added/deleted outside from the IDE2
Fixes the service injection. The breaking change was [here](https://github.com/arduino/arduino-ide/commit/20f771212910cfdac4f14621b96fda6562c6afa9#diff-abca14a02be77160a86d9f4fb6eca8c18d47312d2d4be37c50de50430bbbcd07L203).
`main` with the bug:
https://user-images.githubusercontent.com/1405703/167870194-184faa67-0c11-406c-9666-3a170c335fc5.mp4
This PR with the fix (also tracks deletion):
https://user-images.githubusercontent.com/1405703/167870155-6266d690-ecca-43c5-a467-93a142e26b69.mp4
Closes #985.
=> #985: Restored the missing `inject` decorator.

arduino-ide-extension/src/browser/auth/authentication-client-service.ts, arduino-ide-extension/src/common/protocol/authentication-service.ts, arduino-ide-extension/src/node/auth/authentication-service-impl.ts
To ensure login sessions to Arduino Cloud are persistent when closing and reopening the application.
We were initialising our backend auth service and performing token refreshes without the required "authOptions" properties. These properties are set on the frontend after the backend service is initialised.
We now perform the auth service initialisation and token refreshes on the frontend after the required "authOptions" properties are set.
> Removed initialisation from the backend service;
> Created a method on the backend service to initialise the auth service from the frontend (and added the method to the related interface);
> Created an "initialised" variable in the backend auth service to ensure initialisation does not run more than once (incase of multiple frontend instances);
> …
=> #944: Fixed auth. sessions not persistent

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/editor/editor-manager.ts
Closes https://github.com/arduino/arduino-ide/issues/656
Closes https://github.com/arduino/arduino-ide/issues/793
Since editor widget identity is based not only on the `URI`, but also the options, we need to pass the correct options into the `open` call. Doing that prevents Theia from opening multiple tabs of the same editor
You might need to run the `View: reset workbench layout` command before testing this, since it modifies some state which is stored (in parts) in the browsers local storage.
=> Fix duplicated editor tabs

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/hosted-plugin-events.ts, arduino-ide-extension/src/browser/theia/plugin-ext/hosted-plugin.ts
This PR should fix the unresponsive language feature after waking up the OS from sleep.
Theia does not fire an event when the connection to the plugin server proxy closes. Theia also does not fire an event if the hosted plugins have been re-loaded. This PR adds hooks for such events, and wires in the lifecycle of the LS to the new events exposed from the hosted plugins.
- Start IDE2,
- Verify LS is functional,
- Put the OS into sleep (I do not know if it works on Windows/Linux, but it's reliable on macOS),
- Wake up the OS,
- The LS must work (try the content assist)
=> Fixed LS stops working after OS sleep/wakeup cycle

arduino-ide-extension/package.json, arduino-ide-extension/scripts/download-ls.js, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/format.ts, arduino-ide-extension/src/browser/theia/monaco/monaco-formatting-conflicts.ts, arduino-ide-extension/src/common/protocol/formatter.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/clang-formatter.ts, arduino-ide-extension/src/node/exec-util.ts
Use `clang-format` as the default sketch file formatter. It's faster and does not require a running LS.
- Bumped `clangd` to `14.0.0`,
Closes #1009
Closes #566
For the reviewers:
- Please open dev tools for verification. _Formatting `$URI` [Range: `$RANGE`]_ should be logged when the `clang-format`-ter is used instead of the LS.
- The formatter should work if the LS is not running.
(👆 The _Format Document_ and _Format Selection_ context menu items are available, although the LS is not running.)
- The formatter should work even if there is a whitespace in the sketch name (`sketch with spaces.ino`) or in the IDE path (`/path/to/segment with spaces/arduino-ide`).
- Make sure the beginning and the end of the document are formatted (this should verify the correctness of document range …
=> #1009, #566: Use `clang-format` as the default sketch formatter.

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/core/shell-layout-restorer.ts, arduino-ide-extension/src/browser/theia/editor/editor-manager.ts
This PR should fix the duplicate editor tab issue.
- Fixes the dependency injection by binding the editor manager in a singleton scope,
- Added a workaround in the layout data parser to drop preview editor constructions options when restoring the layout at app startup.
=> Editor manager should be singleton, patched layout restorer to avoid duplicate editor tabs

arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts, arduino-ide-extension/src/node/monitor-manager.ts
This PR solves an issue that happens when uploading a sketch to some boards when the serial port is open.
Some boards need configuration parameters to append to the fqbn during the upload:
https://github.com/arduino/arduino-ide/blob/main/arduino-ide-extension/src/browser/contributions/upload-sketch.ts#L216-L219
and this is messing up with the `MonitorManager` because when `notifyUploadStarted()` is called, the monitor ID won't match the `MonitorService` instance that handles the serial connection:
https://github.com/arduino/arduino-ide/blob/main/arduino-ide-extension/src/node/monitor-manager.ts#L114-L119
Add some logic to make sure only the first part of an fqbn is relevant when creating a `monitorID`
https://github.com/arduino/arduino-ide/compare/fix-monitor-id?expand=1#diff-cf90510ad3f81 …
=> Fix monitor service id creation

arduino-ide-extension/src/browser/theia/preferences/preference-tree-generator.ts
This PR will restore the (advanced) Settings UI in the IDE2. The proposed changes also defer the model (and UI) loading until the IDE2 is ready. Delaying the model load keeps the startup's performance OK and the Settings UI feature in IDE2.
How to verify:
- Open the IDE2, and open the preferences as described in #1031,
- Verify that the preferences UI is the same as before `rc7`,
- Close the IDE2, and reopen it.
- The widget is open, the content is unavailable, then the UI refreshes. Verify that the Settings UI feature is fully functional.
https://user-images.githubusercontent.com/1405703/173190402-f5c9c518-061a-491a-9c97-8fc2f3d4d11f.mp4
Closes #1031
=> #1031 Restored the Settings UI. Deferred model loading.

arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/output-panel-buffer-provider.ts, arduino-ide-extension/src/node/utils/simple-buffer.ts
Output panel prints slower than the CLI and on windows is out of sync with the upload operation.
Adds a simple buffer mechanism for the related stream from the CLI.
Optimisations on CLI side should also complement the resolution of this issue.
=> Output panel optimisation

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts, arduino-ide-extension/src/browser/theia/core/window-contribution.ts
Removed the following items from the `File` menu:
- `New File`,
- `New Window`.
I was there, so I removed `New Window`. It did not work and we never wanted to have such a menu item.
Before:
After:
=> #1014 Cleaned up `File` menu.

arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, i18n/en.json
Can enable the debug logging of the gRPC call to the Arduino CLI.
How to test:
- Open the `~/.arduinoIDE/settings.json`, you can use IDE2 or your favorite text editor,
- Add `"arduino.cli.daemon.debug": true` to the `settings.json` file and save it,
- Start the IDE2 from a terminal, see that debug calls, such as:
```
daemon INFO 3 |  RESP: {
3 |    "download_progress": {
3 |      "url": "https://downloads.arduino.cc/packages/package_index.tar.bz2",
3 |      "file": "Downloading index: package_index.tar.bz2",
3 |      "total_size": 41847
3 |    }
3 |  }
3 |  RESP: {
3 |    "download_progress": {
3 |      "downloaded": 41847
3 |    }
3 |  }
3 |  RESP: {
3 |    "download_progress": {
3 |      "completed": true
3 |    }
3 |  }
```
=> Can enable debug logging of the gRPC calls.

arduino-ide-extension/src/node/utils/simple-buffer.ts
Missing compilation output in output panel.
Make sure we flush all chunks of output from the CLI to the IDE.
=> flush on clear output buffer

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/contributions/burn-bootloader.ts, arduino-ide-extension/src/browser/contributions/compiler-errors.ts, arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/core-error-handler.ts, arduino-ide-extension/src/browser/contributions/format.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/ino-selectors.ts, arduino-ide-extension/src/browser/response-service-impl.ts, arduino-ide-extension/src/browser/style/editor.css, arduino-ide-extension/src/browser/theia/output/output-channel.ts, arduino-ide-extension/src/browser/utils/monaco.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/common/protocol/response-service.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/node/cli-error-parser.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/examples-service-impl.ts, arduino-ide-extension/src/node/service-error.ts, arduino-ide-extension/src/node/utils/simple-buffer.ts, i18n/en.json
- To reveal the compilation error location in the editor after a failed verify. The first compiler error is extracted from the CLI output and the IDE2 reveals it. (#608)
https://user-images.githubusercontent.com/1405703/173849256-bd6e6797-15a5-474d-b93e-6e58282c67e6.mp4
- Show the errors with error color in the _Output_ view (https://github.com/arduino/arduino-ide/issues/229).
- Show the first compilation error in the notification center.
- Can copy the _Output_ content from the error notification:
https://user-images.githubusercontent.com/1405703/173850735-bb65386b-51d2-4dab-b1fd-c95d65c0b389.mp4
You need to enable the experimental features from the `settings.json` if you want to see "more errors" 😉:
- Open the _Command Palette_ with <kbd>F1</kbd>,
- Type and `Preferences: Open Settings …
=> #608, #229 Reveal the error location after the failed verify

arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts
The [`MenuItem#role`](https://www.electronjs.org/docs/latest/api/menu-item#roles) support is [broken in Theia](https://github.com/eclipse-theia/theia/issues/11217). This PR disables the `role` and falls back to the default, command-based execution on `click`.
Disabled the `role` support on macOS.
This issue must be macOS-specific and should be verified by a macOS user.
=> Disabled `MenuItem` `roles` on macOS.

arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
- The indent size of the folders in the sketchbook is too small
The sketchbook structure:
```
Arduino/
├── Foo/
│   └── Bar/
│       └── Sketch/
│       └── Sketch_old/
```
was rendered:
after the changes:
- The sketches have an inappropriate indentation level
The sketchbook structure:
```
Arduino/
├── Foo/
│   └── Bar/
│   └── sketch_jun14a/
```
was rendered:
after the changes:
Updated the left padding of the icons in the sketchbook
Fix for:
- https://github.com/arduino/arduino-ide/issues/1049
- https://github.com/arduino/arduino-ide/issues/1050
=> Sketchbook tree indentation

arduino-ide-extension/package.json
To use the cli version 0.24.0-rc1 in the IDE.
Modifies the package.json cli version reference.
=> reference cli rc1 0.24 in package.json

arduino-ide-extension/src/browser/contributions/settings.ts, i18n/en.json
The localization of the string "Advanced" was missing.
Added localization for "Advanced" string.
=> Add missing 'Advanced' string

.github/workflows/build.yml
Contributors may submit pull requests against development branches in the repository for either of the following valid reasons:
- Propose changes to a previous proposal, either while it is still in development, or else in the case where the changes are more complex/extensive than can be efficiently proposed via the PR review framework.
- The proposal is dependent on work from an unmerged PR.
Previously, [the "Arduino IDE" GitHub Actions workflow](https://github.com/arduino/arduino-ide/actions/workflows/build.yml) was unnecessarily [configured](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore) to only run for PRs based on the `main` branch. This meant that validation and tester builds were not …
=> Run "Arduino IDE" workflow on pull requests with any base branch

.github/workflows/build.yml, electron/build/scripts/notarize.js
GitHub Actions workflows may require access to privileged information in order to perform certain operations. GitHub provides the capability for doing this via ["repository secrets"](https://docs.github.com/en/actions/security-guides/encrypted-secrets).
For security reasons, repository secrets are only accessible to a GitHub Actions workflow run when it is triggered by an event from within the repository containing the secret. This means that a workflow which requires such secrets would fail when run in a fork (unless the fork owner has set up their own secrets with suitable values).
In order to make the relevant components of the CI system friendly for use in forks by contributors validating their work in preparation for submitting a PR, when the operations that require access to a …
=> Enable "Arduino IDE" workflow use by contributors

.github/workflows/build.yml
I have added filters for the irrelevant paths I am aware of. Since I am not deeply familiar with the internal workings of the project, it is possible other paths in the repository could also be filtered to achieve even higher levels of efficiency. If you have any suggestions, I would be happy to add them.
---
The ["Arduino IDE" workflow](https://github.com/arduino/arduino-ide/actions/workflows/build.yml) performs the following operations when triggered on push and pull request [events](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows):
- Build application
- Lint code
- Run tests
- Produce tester packages
All of these operations are specific to the TypeScript/JavaScript code base and its infrastructure.
Previously, the workflow ran whenever any file in the …
=> Only run "Arduino IDE" workflow on relevant changes

arduino-ide-extension/src/browser/theia/core/tab-bars.ts
Editor tabs context menus are empty and, as reported in #1127, they should be removed.
No operation is performed by right-clicking a tab in the editor.
=> Remove tabs context menu

arduino-ide-extension/src/browser/style/sketchbook.css, electron-app/package.json
UI improvements.
simple css override.
=> remove border from tree indent

arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
The indentation of the sketchbook tree must be increased even more in order to reflect the design system.
Increase the padding.
Before:
After:
=> Increase sketchbook tree indentation to reflect design system

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts
We need to disable the survey notification for now.
Remove binding of survey frontend contribution.
=> disable survey contribution

arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx, arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx, arduino-ide-extension/src/browser/style/dialogs.css, arduino-ide-extension/src/browser/style/settings-dialog.css, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
The current window minimum size is too low, we want to increase it.
- [set the minWidth and minHeight](https://github.com/arduino/arduino-ide/compare/window-min-size?expand=1#diff-54951a7f6fc1d8e5bca375af44a6874aa403c6ab0942031b7126743fc7d5ab66R366-R368) when opening a new window (note that I also set `useContentSize` to `true` to ensure the top bar of the OS is not included in the minHeight
- changes the style of the dialogs to ensure the UI doesn't glitch when the user resizes the window
=> Window min size

arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/monitor-manager.ts, arduino-ide-extension/src/node/monitor-service-factory.ts, arduino-ide-extension/src/node/monitor-service.ts
To fix non-functional monitor in IDE2.
Restored monitor service creation state before a36524e:
Pass core client-provider into new instances as a field.
This PR restores the state of the following files before https://github.com/arduino/arduino-ide/pull/1132:
- `arduino-ide-extension/src/node/monitor-manager.ts` (changes from breaking PR [here](https://github.com/arduino/arduino-ide/pull/1132/files#diff-cf90510ad3f811b7073a1934f11698463693bf446a2521eb2a55f27a48328427)),
- `arduino-ide-extension/src/node/monitor-service-factory.ts` ([here](https://github.com/arduino/arduino-ide/pull/1132/files#diff-cf90510ad3f811b7073a1934f11698463693bf446a2521eb2a55f27a48328427)),
- `arduino-ide-extension/src/node/monitor-service.ts` ([here](https://github.com/arduino/arduino-ide/pull/1132/files#diff-a8376e …
=> #1161: Fixed missing core client in the monitor service.

arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/monitor-manager.ts, arduino-ide-extension/src/node/monitor-service-factory.ts, arduino-ide-extension/src/node/monitor-service.ts
Let the dependency injection framework create the service instances. This PR is a dev thing only and the follow-up of #1162.
- Reduced the visibility of the `coreClientProvider` field to `private`,
- Inject `MonitorServiceFactoryOptions` into the `MonitorService` instances,
- Removed `coreClientProvider` field from the `MonitorServiceFactoryOptions`. The DI will take care of injecting props from superclasses.
The monitor functionality must be the same as on the `main`. The PR is a dev-only thing; expect no behavioral changes.
=> Let DI framework create `MonitorService` instances

arduino-ide-extension/src/node/plotter/plotter-backend-contribution.ts
Avoid to have the serial plotter app twice in the IDE.
Use `require#resolve` to locate the plotter app.
=> Use `require#resolve` to locate the plotter app.

arduino-ide-extension/package.json, arduino-ide-extension/src/node/plotter/plotter-backend-contribution.ts
IDE2 contains two serial plotter apps, one in the `build` directory and the other in` node_modules/arduino-ide-extension/build`.
Do not copy the app into the `build` folder.
=> Avoid twice serial plotter apps

arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/library-service-impl.ts, arduino-ide-extension/src/node/service-error.ts
Before #1132 the core gRPC client was not re-initialized (`InitRequest`) after the indexes update. Hence; the CLI could not provide up-to-date `core search` results to the IDE2. Now, it is working in IDE2 but after the core gRPC re-initialization, the board discovery (`BoardListWatchRequest`) is non-functional. This PR fixes it by sending out an event after the core client re-initialization so that the board discovery can restart in IDE2.
From [here](https://github.com/arduino/arduino-cli/pull/1274#issue-866154638):
> The `Rescan` gRPC function has been removed completely in favour of `Init`.
> 
> `UpdateIndex` and `UpdateLibrariesIndex` gRPC functions now don't implicitly reload the indexes, it has to be done explicitly with the `Init` function.
How to test:
- start IDE2,
- make sure you …
=> Restart discovery after re-initializing client.

arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx, arduino-ide-extension/src/browser/style/settings-dialog.css
The [`max-width` rule of the settings dialog](https://github.com/arduino/arduino-ide/compare/fix-settings-dialog-width?expand=1#diff-485ef8a1bfa1280fa7e76193e4ab2b4d596b28f232e2075bda4eb8736a61c57fL3) is being overridden by the [default dialog `max-width`](https://github.com/arduino/arduino-ide/blob/main/arduino-ide-extension/src/browser/style/dialogs.css#L11), resulting in a _VERY_ big (and ugly) dialog. Also, the height of the dialog shouldn't change when switching to the _Network_ tab.
- [give an id](https://github.com/arduino/arduino-ide/compare/fix-settings-dialog-width?expand=1#diff-6d93cde46877c7fcc99a5fdf6798f96d138d2237ac44ea249f5924279710ff1fL66) to the settings dialog html element and use it in the css rule to grant it a higher priority.
- fix settings dialog height
The credit …
=> Fix settings dialog size

arduino-ide-extension/src/node/arduino-localization-contribution.ts, electron/build/template-package.json, package.json
As on [Transifex](https://www.transifex.com/arduino-1/ide2/) we are getting more and more strings translated we want to add support for new languages.
=> Add language packs

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/first-startup-installer.ts, arduino-ide-extension/src/browser/contributions/init-libs-platforms.ts, arduino-ide-extension/src/common/protocol/installable.ts, arduino-ide-extension/src/common/protocol/library-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js, arduino-ide-extension/src/node/library-service-impl.ts
The first time the IDE is launched, it has a mechanism in place to automatically install the most common libraries and platforms, in order to deliver a better out-of-the-box experience for a majority of users.
Right now though, this process would [overwrite libraries and platforms](#798) that were previously installed by the user.
- when installing libraries and platforms _at first start-up_, use the `--no-overwrite` flag of the arduino-cli 
- [refactor] move the code that manages the initialization of these libraries to a new contribution.
=> Prevent overwriting existing libraries and platforms at first IDE start-up

arduino-ide-extension/package.json, arduino-ide-extension/scripts/download-cli.js, arduino-ide-extension/scripts/download-ls.js, arduino-ide-extension/scripts/downloader.js, arduino-ide-extension/scripts/utils.js, arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/contributions/compiler-errors.ts, arduino-ide-extension/src/browser/contributions/core-error-handler.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/node/cli-error-parser.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js, arduino-ide-extension/src/node/core-service-impl.ts, electron/build/template-package.json, i18n/en.json, package.json
Avoid reindexing libraries on every single text document change event.
After a verify (both success and failure), the IDE2 calls the `arduino.languageserver.notifyBuildDidComplete` command (exposed by the VS Code extension) and pushes the most recent [`build_path`](https://github.com/arduino/arduino-cli/blob/63b53c0fa6830ce77cfb5508f06b2b4e601c90b5/rpc/cc/arduino/cli/commands/v1/compile.proto#L44) to the LS via the custom `ino/buildDidComplete` JSON-RPC.
- Use `0.25.0-rc1` CLI,
- Use `0.0.2-beta.4` VS Code extension, and
- Use `0.7.1` Arduino LS
Dev:
- Updated the build scripts; can build the LS from sources besides downloading it from S3 or GH.
#714
=> #714: Use the build cache to speed up the LS

arduino-ide-extension/src/browser/ide-updater/ide-updater-commands.ts, arduino-ide-extension/src/browser/serial/plotter/plotter-frontend-contribution.ts, i18n/en.json
Some unlocalized commands:
- "check for updates"
- "open serial plotter"
=> Localize commands

arduino-ide-extension/src/browser/contributions/ino-language.ts
The ` arduino.language.realTimeDiagnostics` preference value was not forwarded to the LS; hence it's always published the diagnostics to the IDE2.
Closes #1207.
=> #1207: Forward the `realTimeDiagnostics` to the LS.

arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, i18n/en.json
Closes #1212.
Restored the `Optimize for Debugging` before:
abca14a02be77160a86d9f4fb6eca8c18d47312d2d4be37c50de50430bbbcd07
Signed-off-by: Akos Kitta <a.kitta@arduino.cc>
=> Dropped `compile.optimizeForDebug` preference.

arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/browser/style/main.css
The debug button should be present in the toolbar.
Restore the previous button.
Enabled:
Disabled:
=> Toolbar debug button

arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx, arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx, arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/style/settings-step-input.css
To allow users to change font size and app scaling with the keyboard.
Use a custom controlled input component for the desired functionality.
=> Add typing support to steppers

arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx, arduino-ide-extension/src/browser/contributions/open-boards-config.ts
The Board selector is not correctly synchronized when the board/port config changes, which results in inconsistent and confusing UI.
We also want to prevent deselecting the current board from the Board Selector by clicking on Unknown boards
#1204
#1206 
- if no board is selected after closing the board selection dialog, restore the previously connected board https://github.com/arduino/arduino-ide/pull/1214/files#diff-85056a8e2611f77f68cc49f8ea30ab9e5e8ea370f0123e9f1ac63b404fc36195R247-R282
- rely on `boardsServiceProvider` when showing the currently selected board and port https://github.com/arduino/arduino-ide/pull/1214/files#diff-85056a8e2611f77f68cc49f8ea30ab9e5e8ea370f0123e9f1ac63b404fc36195L202-R213
- update available boards in `boardsServiceProvider` when fqbn changes (this fixes a …
=> Fix board selector synchronization

arduino-ide-extension/src/browser/style/settings-step-input.css
Hard coded color was used in stepper styling, hence mismatch with dark theme.
Uses a variable instead of a hard coded color. A typo width property has also been removed.
=> use variable for step button container bkgnd

arduino-ide-extension/src/browser/boards/boards-auto-installer.ts
The primary action button should be to the right of the notification box.
Reverses the position of the buttons.
Before:
After:
Closes #1227.
=> Primary action button to the right of the notification box

arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/node/core-service-impl.ts
Verbose output preferences reported as incorrect during upload actions.
Ensure compile "verbose" preference is considered when performing compile step prior to upload.
Upload "verbose" preference was being used for both compile and upload steps of the "upload operation".
=> #374: ensure compile verbose pref is included on upload

arduino-ide-extension/src/browser/dialogs/settings/settings.ts, electron/build/patch/frontend/index.js
Incorrect theme shown on first start in settings.
Use `matchMedia` method to determine initial UI dropdown value. Patch the app config provider to dispatch based on the OS' theme.
=> #1223: use theme service on settings load

arduino-ide-extension/src/browser/style/settings-dialog.css
Settings dialog reported as visually unpleasing, and functionally impaired when scaling up the IDE.
Uses a fixed footer and `overflow: auto` for settings dialog content.
=> #1205: improve "broken UI" with settings dialog when app is scaled up

arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts, arduino-ide-extension/src/node/i18n/localization-backend-contribution.ts
[IDE2 might forget the selected language](https://github.com/arduino/arduino-ide/issues/1219)
I noticed the root of the problem is here:
https://github.com/eclipse-theia/theia/blob/f4327c2f0c0f47f960a302590a51698879357841/packages/core/src/node/i18n/localization-backend-contribution.ts#L38-L39
`req.params.locale` is always restored correctly, but `this.localizationProvider.getAvailableLanguages()` doesn't return all the available languages. This happens because `getAvailableLanguages()` returns all the registered localizations with `languagePack` set to `true` (unless we call `getAvailableLanguages(true)`, in that case, it would always return all the languages):
https://github.com/eclipse-theia/theia/blob/f4327c2f0c0f47f960a302590a51698879357841/packages/core/src/node/i18n/localization-pro …
=> Fix current IDE language on start-up

arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx
The `settings-step-input.tsx` component contains unnecessarily verbose code and inefficient logic.
Refactors the code, to exclude useState and useEffect hooks.
The stepper component should function exactly as before (prior to the changes in this PR).
=> remove state from stepper input and simplify

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/ino-language.ts, arduino-ide-extension/src/browser/contributions/save-as-sketch.ts, arduino-ide-extension/src/browser/theia/core/application-shell.ts, arduino-ide-extension/src/browser/theia/core/connection-status-service.ts, arduino-ide-extension/src/browser/theia/core/status-bar.ts, arduino-ide-extension/src/browser/theia/core/tab-bars.ts, arduino-ide-extension/src/browser/theia/editor/editor-widget-factory.ts, arduino-ide-extension/src/browser/theia/markers/problem-manager.ts, arduino-ide-extension/src/electron-browser/theia/core/electron-menu-module.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, electron/build/template-package.json, package.json
The LS is still slow according to users.
- Debounced the connectivity status update.
- Silent the output channel for the Arduino LS.
- Delay the problem markers update with 500ms.
- Do not update the status bar on every `keypress` event.
- Debounced the tab-bar toolbar updates when typing in editor.
- Fixed electron menu contribution binding.
- Aligned the editor widget factory's API to Theia.
- Set the zoom level when the app is ready (Closes https://github.com/arduino/arduino-ide/issues/1244)
- Fixed event listener leak (Closes https://github.com/arduino/arduino-ide/issues/1062)
Closes #1244
Closes #1062
Closes #1191
=> Improve the UX of the Arduino language server

arduino-ide-extension/src/browser/contributions/add-zip-library.ts, arduino-ide-extension/src/browser/contributions/burn-bootloader.ts, arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/common/protocol/installable.ts, arduino-ide-extension/src/common/protocol/progressible.ts, arduino-ide-extension/src/common/protocol/response-service.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/grpc-progressible.ts, i18n/en.json
Show progress indication when running the `verify`, `upload`, `upload using programmer` or `burn bootloader` commands from IDE2.
The changes in action:
1. Verfiy:
https://user-images.githubusercontent.com/1405703/181473877-daa198b2-d102-446f-bf3d-1aa8d065e2e2.mp4
2. Upload:
https://user-images.githubusercontent.com/1405703/181473936-ba90256c-f925-4dde-9406-c9de7054af50.mp4
- [dev]: The core service (backend) does not run `compile` before `verify`; it's the caller's responsibility to run it.
~Noteworthy UI/UX changes:~
~An `Upload` consists of two tasks: `Verfiy` and `Upload`. With the proposed changes, users will see on the toolbar (Verify toolbar icon is yellow with the light Arduino theme) that if `Verify` is in progress, then `Upload` is in progress. See in action.~ …
=> #575, #1175 Show 'progress' indicator during verify/upload

arduino-ide-extension/src/browser/style/arduino-select.css, arduino-ide-extension/src/browser/style/boards-config-dialog.css, arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css, arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/style/list-widget.css, arduino-ide-extension/src/browser/style/main.css, arduino-ide-extension/src/browser/style/sketchbook.css
The High Contrast theme needs to be updated as hover status in drop-down menus and sketchbook is missing, board selector has no borders, and other design issues make the experience unpleasant to use.
- Serial Monitor drop-down menu selector hover and selected state.
- Board selector border.
- Board selector hover and selected state.
- Buttons hover and focus state.
- Side bar elements (Sketchbook etc.) hover and selected state.
- Toolbar buttons hover and selected state.
- Quick inputs hover and selected state.
- Install/Uninstall button hover state.
- Buttons borders.
- Notification hover status.
- Command palette border.
This is a workaround until the version of Theia used is updated to 1.27.0, where the Theia High Contrast theme is updated and it's possible to use the Theia APIs to …
=> High Contrast theme updates

arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx, arduino-ide-extension/src/browser/style/boards-config-dialog.css
As stated in #998, the items of the Board Selector dropdown may overflow in an ugly way if the label is too long. 
Adding `overflow: hidden` to parent and ellipsis to children.
I also added a tooltip to show the complete board/port combination, so that a user is able to see when hovering over the item.
=> Prevent board selector item labels to overflow

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/data/dark.color-theme.json, arduino-ide-extension/src/browser/data/default.color-theme.json, arduino-ide-extension/src/browser/style/boards-config-dialog.css, arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css, arduino-ide-extension/src/browser/style/cloud-sketchbook.css, arduino-ide-extension/src/browser/style/dialogs.css, arduino-ide-extension/src/browser/style/editor.css, arduino-ide-extension/src/browser/style/ide-updater-dialog.css, arduino-ide-extension/src/browser/style/main.css, arduino-ide-extension/src/browser/style/progress-bar.css, arduino-ide-extension/src/browser/style/settings-dialog.css, arduino-ide-extension/src/browser/style/sketchbook.css, arduino-ide-extension/src/browser/style/user-fields-dialog.css
The number of custom colors should be reduced because in the future it will be difficult to support VS Code themes while keeping all these extra colors.
Hard-coded colors must be removed using an appropriate variable.
The following is a proposed change taking into account these variables https://code.visualstudio.com/api/references/theme-color.
In particular:
- Remove hard-coded colors using appropriate variables.
- To change `"arduino.output.background"` and `"arduino.output.foreground"` with `"terminal.background"` and `"terminal.foreground"` (https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors). The values of these variables must be defined.
- `"arduino.branding.primary"` used for the "Learn more" link in the Cloud Sketchbook, could be replaced by …
=> Custom colors clean up

arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/monitor-manager.ts
To fix the upload functionality in IDE2 when the monitor is running.
Use `fqbn` (`string | undefined`) type instead of the `Board | undefined` for the monitor ID when notifying `MonitorService` before/after executing the `upload` command.
Closes #1278
=> #1278 Use FQBN instead of `Board` for the monitor ID.

electron/build/patch/backend/main.js
Set the `XDG_CONFIG_HOME` env on Linux when not set. Otherwise, `node-log-rotate` creates a folder with the `undefined` name.
Patched the patched `main.js` for the Theia backend. 🤦 
Closes #394.
=> Set `XDG_CONFIG_HOME` env on Linux when not set.

arduino-ide-extension/src/browser/contributions/edit-contributions.ts, arduino-ide-extension/src/browser/menu/arduino-menus.ts
`Auto Format` should be placed under the `Edit` menu according to the design specifications.
A new `registerMenuAction` has been added under the `Edit` menu with the `Auto Format` command.
Closes #1229.
=> Move Auto Format to the Edit menu

.github/workflows/build.yml, .github/workflows/check-i18n-task.yml, arduino-ide-extension/scripts/download-cli.js, arduino-ide-extension/scripts/utils.js
To show the exact CLI version (commit hash) in IDE2 when IDE2 is using a pinned version, not yet released CLI.
- Updated the GH workflow and make `Task` available,
- Changed the CLI downloader to use `task` instead of `go` when a CLI ought to be produced on the fly.
It's recommended for devs to install `Task` on the dev env. See [here](https://taskfile.dev/installation/).
Closes #1313
=> Use `Task` to build pinned CLI for IDE2.

arduino-ide-extension/package.json
The IDE2 uses a CLI from the [`test_1`](https://github.com/arduino/arduino-cli/tree/test_1) branch from the `arduino` owner.
No code changes. The IDE2 uses the CLI from the `HEAD` of [this](https://github.com/arduino/arduino-cli/tree/test_1) branch.
=> Use the refactored CLI in IDE2

arduino-ide-extension/src/browser/contributions/burn-bootloader.ts, arduino-ide-extension/src/browser/contributions/compiler-errors.ts, arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/format.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/selectors.ts, arduino-ide-extension/src/browser/theia/messages/notifications-manager.ts, arduino-ide-extension/src/browser/utils/monaco.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/node/cli-error-parser.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/utils/buffers.ts, i18n/en.json
Can reveal the error location in the editor from the _Output_ view.
In-action:
https://user-images.githubusercontent.com/1405703/182376367-d2f5c299-9370-49bb-a67d-342d887115ec.mp4
Noteworthy changes:
- The error decoration is automatically removed from the editor when a `TextDocumentChangeEvent` affects the line where the decorator is.
https://user-images.githubusercontent.com/1405703/182377221-75662cf7-54bc-44b7-a485-4595cc61d05b.mp4
Closes #118
Closes #1154
=> #118, #1154 Link compiler errors to editor.

arduino-ide-extension/README.md
Arduino IDE has dependencies on the clangd C++ language server and ClangFormat code formatter tools. These are updated
periodically to benefit from the ongoing development on those projects.
The update procedure requires operations in three different repositories:
- Generate builds in [`arduino/clang-static-binaries`](https://github.com/arduino/clang-static-binaries/releases)
- Validate and update formatter configuration in [`arduino/tooling-project-assets`](https://github.com/arduino/tooling-project-assets)
- Update metadata in [`arduino/arduino-ide`](https://github.com/arduino/arduino-ide)
The above information is undocumented and the update procedure exists only in the form of ["institutional memory"](https://en.wikipedia.org/wiki/Institutional_memory).
This lack of documentation might …
=> Document clangd update procedure

electron/packager/config.js
Replace `-` with `.` to make auto-update work correctly
Automatic updates are not working anymore with nightly builds.
Fixes #1318.
As suggested in #1318, using a `.` instead of a `-` to separate the "nightly" and "snapshot" build makes the semver comparison to work as expected.
=> Change naming of nightly and snapshot builds

arduino-ide-extension/src/node/boards-service-impl.ts
Handles the `SupportedUserFieldsRequest` gracefully when the board's platform is not installed.
To verify:
- make sure you do not have the board for the RP2040 installed,
- start the IDE2 (you can also trace the error log or open the dev tools to see the client error),
- select the RP2040,
- you should see no errors as described in #1142
Closes #1142
=> #1142 Handle missing core when getting board user fields

arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/common/protocol/boards-service.ts
Removed the filtering of unrecognized `network` boards. Unrecognized `network` boards should show up with their IP addresses.
=> #1327 Show all network and serial ports

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/boards/boards-config-dialog.ts, arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx, arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-dialog.tsx, arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-dialog.tsx, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-component.tsx, arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx, arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx, arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx, arduino-ide-extension/src/browser/ide-updater/ide-updater-client-impl.ts, arduino-ide-extension/src/browser/style/boards-config-dialog.css, arduino-ide-extension/src/browser/style/certificate-uploader-dialog.css, arduino-ide-extension/src/browser/style/dialogs.css, arduino-ide-extension/src/browser/style/firmware-uploader-dialog.css, arduino-ide-extension/src/browser/style/ide-updater-dialog.css, arduino-ide-extension/src/browser/style/settings-dialog.css, arduino-ide-extension/src/browser/style/settings-step-input.css, arduino-ide-extension/src/common/protocol/ide-updater.ts, arduino-ide-extension/src/electron-main/ide-updater/ide-updater-impl.ts, i18n/en.json
As explained in #1309, our dialogs might become distorted when scaling up the UI (from the settings or using the shortcut CMD/CTRL + '+').
I've made some fixes in order to make the interface readable and usable with an interface that is scaled up to 200%, with a minimum window size of 450px in width and 300px in height. Maybe they won't look beautiful, but every dialog should be at least usable and readable up to that size.
Here's a list of screen captures **before** the changes, with an interface scale of 200% and a window size of 450x300:
https://user-images.githubusercontent.com/6939054/183592585-33d4c0fc-93d3-44cf-8dae-5bcc9ae127b5.mov
https://user-images.githubusercontent.com/6939054/183593554-00628d68-d7df-4a25-9494-eb3cf80f0418.mov
---
And **after** the changes: …
=> Fix dialogs UI scalability

arduino-ide-extension/src/browser/contributions/help.ts
Selecting **Help > Environment** from the Arduino IDE menus opens a page containing usage information for the Arduino IDE application in the browser.
Previously, the URL used was the same as that in [Arduino IDE 1.x](https://github.com/arduino/Arduino):
https://www.arduino.cc/en/Guide/Environment
The documentation from that page was written for Arduino IDE 1.x. Even though the UI of the two versions is aligned for the most part, advancements made for the 2.x major version series resulted in some differences. This means that documentation targeted at Arduino IDE 1.x is not always applicable to Arduino IDE 2.x.
Fortunately, documentation is now available for each major version series of the IDE. So resolution is only a matter of pointing the menu item at the correct URL: …
=> Use more relevant page for "Help > Environment" menu item target

arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-component.tsx, arduino-ide-extension/src/node/boards-service-impl.ts, i18n/en.json
The text of the Arduino IDE user interface has been localized to 12 languages.
Before localization can be accomplished, internationalization must be done in the application's codebase:
- Set up infrastructure to export localization data
- Pass all target strings to that infrastructure
While the first of these tasks is completed, the second was not completed for several strings which are part of the user interface.
Those outstanding strings are internationalized and will be made available for localization.
=> Add missing i18n for UI strings

.github/workflows/build.yml, .github/workflows/check-i18n-task.yml, .github/workflows/i18n-nightly-push.yml, .github/workflows/i18n-weekly-pull.yml, .github/workflows/themes-weekly-pull.yml
[**Arduino CLI**](https://github.com/arduino/arduino-cli) is a tool dependency of Arduino IDE. For this reason, the necessary Arduino CLI build is acquired whenever running the `yarn` command in the repository.
The way the **Arduino CLI** build is acquired depends on the type of version specified as dependency in [the `arduino.cli.version` field of the **arduino-ide-extension** package metadata](https://github.com/arduino/arduino-ide/blob/ca47e8a09af514926da28e6b2b09603b02476df4/arduino-ide-extension/package.json#L163):
- [Release/nightly: download pre-built standard distribution](https://github.com/arduino/arduino-ide/blob/ca47e8a09af514926da28e6b2b09603b02476df4/arduino-ide-extension/scripts/download-cli.js#L68-L80)
- [Git ref: build from …
=> Install Arduino CLI build dependencies in all dependent workflows

arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
Small fix for correctness. we are yet to decide whether or not to impose a specific max/min level of zoom in the IDE, in the meantime, to avoid confusion we should ensure the max-min zoom of the scale stepper reflects the actual max-min zoom of the application.
Changes hard coded max-min values used by the scale stepper.
=> Align functional max-min of scale stepper to actual max-min zoom level

arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/boards/boards-toolbar-item.tsx, arduino-ide-extension/src/browser/contributions/board-selection.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/monitor-manager-proxy-client-impl.ts, arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx, arduino-ide-extension/src/common/nls.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/auth/utils.ts, arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/monitor-service.ts, arduino-ide-extension/src/test/browser/fixtures/boards.ts
To show the `hostname` of the `network` port in the boards dropdown and `Tools` > `Ports` menu (#1331)
To fix the upload caused by missing port `properties` (#740) 
- Removed unnecessary `id` from the `Port` type. It can be derived from the `address` and `protocol`.
- Introduced a shared `Unknown` i18n string.
- Removed the deprecated `getAttacheBoards`/`getAvailablePorts` service APIs.
- Use the `addressLabel` instead of the `address` in the boards dropdown and `Tools` > `Ports` menu. (#1331)
- Introduced an optional `properties` on the `Port` type. (#740)
- Use the `Port#properties` for the upload. (#740)
- Better type guard for the `Port` type.
- Refactored the board discovery and added better typing for the gRPC `DetectedPort`.
Closes #1331
Closes #740
=> #740, #1331 Use port properties

arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, i18n/en.json
If the user presses the upload button and no board is selected, a message should appear warning what went wrong while uploading. Since verify takes place before upload, the same message that is given when the user tries to compile a sketch without selecting a board should be shown. On the other hand, this message is not very clear, so it should be updated.
Communicate to user when upload is impossible due to no board selection.
Make error message from compiling without board selected more user friendly.
Closes #845.
Closes #62.
This fix depends on the changes made here: https://github.com/arduino/arduino-cli/pull/1848. Without it it is not possible to verify that #62 is resolved.
=> Error message if upload is not possible

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/close.ts, arduino-ide-extension/src/browser/contributions/save-as-sketch.ts, arduino-ide-extension/src/browser/contributions/sketch-files-tracker.ts, arduino-ide-extension/src/browser/style/editor.css, arduino-ide-extension/src/browser/theia/core/application-shell.ts, arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts, arduino-ide-extension/src/browser/theia/core/widget-manager.ts, arduino-ide-extension/src/browser/theia/editor/editor-file.ts, arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/electron-browser/theia/core/electron-menu-module.ts, arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/board-discovery.ts, arduino-ide-extension/src/node/is-temp-sketch.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/node/theia/workspace/default-workspace-server.ts, i18n/en.json
Closes #1016
Closes #1274
Closes #1026
Closes #660
Closes #1034
Closes #994
=> #1016, #1274 Aligned the "Save your sketch" dialog behavior

arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/common/protocol/boards-service.ts
Avoid filtering ports and the boards connected to them if the `protocol` is neither `'serial'` nor `'network`', but the associated boards are recognized.
Single sourced the port filtering.
Closes #1365
=> #1365 Show ports if has recognized board attached to it

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/contributions/first-startup-installer.ts, arduino-ide-extension/src/common/protocol/library-service.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js, arduino-ide-extension/src/node/library-service-impl.ts
Use a dedicated install location for the `Arduino_BuiltIn` lib on the first IDE2 start.
From now on, the built-in lib will be installed into the `built-in` location of the CLI.
Closes #1055.
=> #1055 Install the `Arduino_BuiltIn` to built-in location

arduino-ide-extension/src/common/protocol/installable.ts
Fix `updatable` state calculation with _"relaxed-semver"_ (https://github.com/arduino/arduino-cli/issues/1727#issuecomment-1120805266).
To verify:
- install `PubSubClient@2.8.0`,
- check for updates (no updates)
- restart IDE2 (no updates)
From the `main` it detects updates, installs `PubSubClient`, and logs already installed.
Closes #1390
=> #1390 Coerce a semver when calculating updatables

arduino-ide-extension/src/browser/style/list-widget.css, arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx, arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
Improves the scrolling in the library/boards manager widgets.
Closes #1380
Closes #1381
Closes #1387
=> #1380 #1381 #1387 Improved the scrolling UX in list widgets

docs/advanced-usage.md
Although the Arduino IDE's primary preferences interface provides all required configuration capabilities, advanced users may wish to fine tune the behavior of the application or temporarily enable additional log output to use for troubleshooting problems with the IDE.
The IDE provides such settings in a separate interface.
The existence and access procedure for these settings is undocumented.
Provide instructions for accessing the advanced settings.
Since this is an advanced capability, the documentation is not appropriate for inclusion with the standard user
documentation on arduino.cc. A file here in the Arduino IDE is used instead. This file will serve as a container for all
such user-targeted documentation.
Resolves https://github.com/arduino/arduino-ide/issues/1367
=> Add instructions for accessing IDE's advanced settings

arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
Misalignment of output observed in Serial Monitor due to trimming of leading zeros in the datetime format
Datetime format modified to contain leading zeros i.e. 22:8:7.353 will now be printed as 22:08:07.353
Fixes #580
=> Time format in Serial Monitor changed. Fixes #580

arduino-ide-extension/package.json, browser-app/package.json, electron-app/package.json, package.json
Increase Arduino IDE version to release 2.0.0-rc9.4
Upgrade arduino-cli to [0.27.1](https://github.com/arduino/arduino-cli/releases/tag/0.27.1)
=> Prepare 2.0.0-rc9.4

BUILDING.md, docs/internal/release-procedure.md
An internal release procedure document was created separately from the documentation hosted in this repository. That internal document became significantly more comprehensive and up to date than the unmaintained documentation in this repository.
The current situation results either in the burden of maintaining two copies of the same information, or more likely the out of sync state between the information in the two resulting from lack of such maintenance.
A single document will be maintained here in this repository from now on. The superior version of the information from the internal document is migrated to the repository.
The documentation is moved from the previous inappropriate location in `BUILDING.md` to a dedicated file `docs/internal/release-procedure.md`
---
Supersedes the …
=> Update release procedure documentation

README.md
During the early phase of development, the download links for the nightly build were only available from the table in the project readme.
Since that time, download links were also added to [the "**Software**" page on arduino.cc](https://www.arduino.cc/en/software), which is already linked to from the readme. This means the nightly build link table is superfluous and only harms the readability of the readme.
Remove the superfluous table from the readme.
=> Remove table of nightly build links from readme

README.md, arduino-ide-extension/package.json, browser-app/package.json, electron-app/package.json, electron/packager/config.js, package.json
Prepare for releasing 2.0.0
https://github.com/arduino/arduino-ide/pull/1326 introduced a bug in versioning that is preventing CI to succeed in https://github.com/arduino/arduino-ide/pull/1422. We're reverting those changes and fix the issue, but we probably want to find a better solution later.
=> Prepare 2.0.0

arduino-ide-extension/src/browser/dialogs/ide-updater/ide-updater-dialog.tsx
The Arduino IDE has an auto update capability (https://github.com/arduino/arduino-ide/pull/797). A new version is checked for on every startup, and if available the user is offered an update.
Although this update can usually be done automatically by the IDE, under some conditions this is not possible. For example:
- The IDE package in use does not support auto update (i.e., Linux ZIP package)
- The file could not be downloaded due to a transient network service outage
In this case, the user is presented with a friendly dialog that explains the situation and links to [the "**Software**" page](https://www.arduino.cc/en/software) on arduino.cc, where the user can manually download and install the new version:
During the pre-release development phase of the project, the download links for …
=> Remove obsolete fragment identifier from IDE manual download link

arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx, i18n/en.json
Can send message to monitor with <kbd>Enter</kbd> instead of <kbd>Ctrl</kbd>/<kbd>⌘</kbd>+<kbd>Enter</kbd>.
I checked the Theia code, [it should work](https://github.com/eclipse-theia/theia/blob/9e5db7756755fe2cc4155f59fda27f32b3d5bbe4/packages/core/src/common/keys.ts#L659) with _Numpad Enter_ but it would be great if somebody could verify it. Thank you!
Closes #572
=> #572 Can send message to the monitor with `Enter`

electron-app/package.json
To fix unresponsive IDE2 issue due to tokenizer.
Set the `editor.maxTokenizationLineLength` to `500` characters.
Closes #1343.
=> #1343 Disabled the tokenizer after 500 chars.

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/user-fields.ts
When uploading a sketch with user fields, if the user made a mistake while filling in the dialog, or made a change that requires updating the fields, it might not be clear to them how to do that 🙁
As requested in #1386, I've made a change to show again the user field dialog when pressing the Upload button if the previous upload failed.
Closes #1386
=> Show user fields dialog again if upload fails

arduino-ide-extension/src/browser/dialogs/settings/settings-dialog.tsx, arduino-ide-extension/src/browser/library/library-list-widget.ts, arduino-ide-extension/src/browser/style/settings-dialog.css, arduino-ide-extension/src/browser/theia/workspace/workspace-input-dialog.ts
In some dialogs, the primary button is not on the right.
Move all primary buttons in dialogs to the right.
Closes #1368.
=> Move primary buttons on the right of the dialogs

arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx, arduino-ide-extension/src/browser/style/monitor.css
A fix for Issue #972
Fixed margin of `<pre></pre>` tag used to display each line of text
N/A
=> Serial Monitor autoscroll only makes bottom line partially visible #972

arduino-ide-extension/src/browser/style/firmware-uploader-dialog.css
In the Firmware Updater dialog  the "Select a board..." input has a contrast issue. See details [here](https://github.com/arduino/arduino-ide/issues/1441).
Changed the background of the input accordingly with the selected theme.
Dark:
Light:
Closes #1441.
=> #1441 Fix input background in Firmware Updater dialog

arduino-ide-extension/src/node/config-service-impl.ts
IDE2 creates the sketchbook folder (`directories.user`) on startup if it's missing.
Closes #1445
=> #1445 Ensure `directories.user` exists.

arduino-ide-extension/src/browser/style/settings-dialog.css
In the "Additional Boards Manager URLs" dialog, if the text of a 3rd party URL is too long, it is returned in a new line. See description [here](https://github.com/arduino/arduino-ide/issues/1470).
Avoid new line adding `white-space: nowrap;` CSS rule.
Result:
https://user-images.githubusercontent.com/94986937/191464446-daf7f98c-c26c-4258-a166-40e1fc674749.mp4
Closes #1470.
=> Avoid new line if 3rd party URLs text is too long

arduino-ide-extension/src/browser/contributions/add-file.ts, arduino-ide-extension/src/browser/contributions/add-zip-library.ts, arduino-ide-extension/src/browser/contributions/archive-sketch.ts, arduino-ide-extension/src/browser/contributions/open-sketch.ts, arduino-ide-extension/src/browser/contributions/save-as-sketch.ts, arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
This PR is the outcome of the investigation of #411. This PR fixes the default location when saving a sketch as. From now on, every native file dialog is modal.
Noteworthy changes:
- If the sketch is temp, the default save location is `directories/user/sketch_$current_date`,
https://user-images.githubusercontent.com/1405703/184651953-0b0c5f6b-4ca8-42a7-b61b-628b8d89be0d.mp4
- If a sketch is contained in the default location as `directories/user/sketch`, then the default location will be `directories/user/sketch_copy_date`,
https://user-images.githubusercontent.com/1405703/184652457-b41181d7-0dbb-4add-a74f-0344e870582b.mp4
- If a sketch is outside of the sketchbook, then the default location will be `directories/user/sketch_$current_date`, …
=> #411 Fixed bug when saving sketch as. Made native file dialogs modal.

arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
Delegate keyboard layout changes from the OS to the IDE2 frontend.
How to test:
- Follow the steps from #989.
Closes #989
=> #989 Listen on keyboard layout changes from the OS

.github/ISSUE_TEMPLATE/config.yml, arduino-ide-extension/package.json, docs/internal/release-procedure.md, electron-app/package.json, package.json
On every startup, the Arduino IDE checks for new versions of the IDE (https://github.com/arduino/arduino-ide/pull/797). If a newer version is available, a notification/dialog is shown offering an update.
"Newer" is determined by comparing the version of the user's IDE to the latest available version on the update channel. This comparison is done according to [semver](https://semver.org/).
In order to facilitate beta testing, builds are generated of the Arduino IDE at the current stage in development. These builds are given an identifying version of the following form:
- `<version>-snapshot-<short hash>` - builds generated for every push and pull request that modifies relevant files
- `<version>-nightly-<YYYYMMDD>` - daily builds of the tip of the default branch
The established project …
=> Bump version metadata to produce correct tester and nightly build precedence

docs/CONTRIBUTING.md, docs/contributor-guide/translation.md, i18n/README.md
Translation of the strings of the Arduino IDE UI is a valuable contribution which helps to make Arduino accessible to everyone around the world.
Localization of the Arduino-specific strings of the IDE is done in [the "**Arduino IDE 2.0**" project on **Transifex**](https://explore.transifex.com/arduino-1/ide2/). Previously, the "Translation" row in the contribution methods summary table in [the contributor guide entry page](https://github.com/arduino/arduino-ide/blob/main/docs/CONTRIBUTING.md#contributor-guide) simply linked to that project.
Arduino IDE also uses localized strings from several other sources:
- [**VS Code** language packs](https://open-vsx.org/?search=&category=Language%20Packs&sortBy=relevance&sortOrder=asc)
- [**Arduino …
=> Add a dedicated translator guide document

arduino-ide-extension/src/browser/contributions/check-for-ide-updates.ts
"Check for Arduino IDE Updates" operation fails when automatic update checks are disabled #1437
The reason is that we're avoiding to initialise the updater properly at start-up if the "Check for Arduino IDE Updates" preference is disabled.
Always initialise the updater. Only then we can decide if effectively check for updates or not.
=> Initialise the IDE updater even when 'checkForUpdates' preference is false

arduino-ide-extension/src/browser/style/main.css
Avoid the problem that the Intellisense widget may be cover by the bottom(Output) panel partially.
from: 
to:
=> Avoid intellisense widgets being covered by the bottom panel

arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/user-fields.ts, arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-dialog.tsx, arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-dialog.tsx, arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-component.tsx, arduino-ide-extension/src/browser/dialogs/user-fields/user-fields-dialog.tsx, i18n/en.json
Some dialogs, when being opened, don't set the focus on the controls (inputs, button, etc)
Fixed the focus in the following dialogs:
- Configure and Upload
- Firmware Uploader
- Certificate Uploader
Also changed "Configure And Upload" label to "Configure and Upload".
Fixes #1373
=> Dialog focus

arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx, i18n/en.json
An "**INSTALLED**" label is shown on the items in the **Library Manager** and **Boards Manager** views that are currently installed on the user's system:
During some work to add missing internationalization to the UI strings (https://github.com/arduino/arduino-ide/pull/1449), this text was changed to "**INSTALL**".
"**INSTALL**" is not appropriate for what this label is intended to communicate.
Correct the regression, while retaining the internationalization of the string.
=> Correct text of "INSTALLED" label in Library/Boards Manager

arduino-ide-extension/src/browser/contributions/examples.ts, arduino-ide-extension/src/browser/contributions/new-sketch.ts, arduino-ide-extension/src/browser/contributions/open-recent-sketch.ts, arduino-ide-extension/src/browser/contributions/open-sketch.ts, arduino-ide-extension/src/browser/contributions/save-sketch.ts, arduino-ide-extension/src/browser/contributions/sketchbook.ts, arduino-ide-extension/src/browser/theia/core/about-dialog.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/examples-service-impl.ts, arduino-ide-extension/src/node/sketches-service-impl.ts
IDE2 must notify the user about missing/invalid sketches and update the menus when opening the sketch has failed. This is the expected behavior when opening from `File` > `Open Recent`, `File` > `Sketchbook`, and `File` > `Examples`.
Closes #53
=> #53 Refresh menus when opening example/recent fails.

arduino-ide-extension/package.json, yarn.lock
A new version of the arduino-serial-plotter-webapp dependency is available.
Bump arduino-serial-plotter-webapp dependency to 0.2.0
Fixes https://github.com/arduino/arduino-ide/issues/1360
=> Bump arduino-serial-plotter-webapp dependency to 0.2.0

arduino-ide-extension/src/browser/library/library-list-widget.ts
Arduino libraries may specify dependencies on other libraries in their [metadata](https://arduino.github.io/arduino-cli/dev/library-specification/#library-metadata). The installation of these dependencies is offered by Arduino IDE when the user installs the dependent library using the "**Library Manager**" widget.
The order of the buttons in the dialog that offers the dependencies installation was recently rearranged (https://github.com/arduino/arduino-ide/pull/1382). The dialog response interpretation code was not updated to reflect the changes to the button indexes at that time. This caused the "**CANCEL**" button to trigger the behavior expected from the "**INSTALL ALL**" button, and vice versa.
1. Open the "**Library Manager**" view.
1. Install any version of the "ArduinoIoTCloud" …
=> Update library dependency installation dialog response indexes

arduino-ide-extension/scripts/download-examples.js
The Arduino IDE installation includes a collection of example sketches demonstrating fundamental concepts.
These examples are hosted in a dedicated repository, which is a dependency of this project. A new release has been made in that `arduino/arduino-examples` repository:
https://github.com/arduino/arduino-examples/releases/tag/1.10.0
This release updates the formatting of the examples to be compliant with the code style of the Arduino IDE 2.x "**Auto Format**" feature.
Bump the version of the `arduino/arduino-examples` dependency in the download script so that the latest version of the examples will be bundled with the Arduino IDE installation.
Related:
- https://github.com/arduino/arduino-ide/pull/383
- https://github.com/arduino/arduino-ide/issues/42
- …
=> Bump built-in example sketches version to 1.10.0

arduino-ide-extension/package.json, arduino-ide-extension/src/common/protocol/library-service.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js, arduino-ide-extension/src/node/examples-service-impl.ts, arduino-ide-extension/src/node/library-service-impl.ts
Align gRPC APIs with the most recent Arduino CLI. The `Library#real_name` has been removed from the gRPC API: arduino/arduino-cli#1890
This PR switches from `real_name` to `name` in the UI, as the `name` is the canonical form provided by the CLI.
How to verify:
- start the IDE2,
- open the library manager widget and type `SparkFun color lcd` in the search `<input>`, (expected a single result: `SparkFun Color LCD Shield`)
- if the library is installed, uninstall it by clicking on `UNINSTALL`,
- this should wipe the library without any errors,
- install the `SparkFun Color LCD Shield@1.0.1`,
- open `File` > `Examples`> verify that you see `SparkFun Color LCD Shield` as the grouping menu item. Like this:
Closes #1525
=> #1525 Removed the `real_name` of the libraries

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/edit-contributions.ts, arduino-ide-extension/src/browser/contributions/interface-scale.ts, arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
The interface scaling of the IDE doesn't handle scaling properly:
- as stated in #1384, it's possible to find yourself in unpredictable situations we're only limiting the scaling when using the stepper input
- same thing happen with the editor font size
- when changing the scaling really fast (e.g.: holding down `CTRL/CMD + =` for a while), the interface seems to 'bounce' from bigger to smaller and viceversa until it's stable
- move the interface scaling logic to a separate contribution
- the stepper in the settings dialog and the related commands now uses common values for min/max scale and font size
- when the `Automatic` flag in the settings dialog is **checked**, enable/disable the **'Increase/Decrease Font Size'** menu item and shortcuts when reaching `-60%` (min) and `280%` (max) 
- …
=> Limit interface scale

arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/grpc-progressible.ts
To fix the persistent error (see #1529) when installing a library or platform. As part of the arduino/arduino-cli#1875 the `DownloadProgress(Start|Update|End)` APIs have been unified. Besides the index updates, the lib/platform install started to use the same API as the index update, but IDE2 was not prepared for this. The PR should fix the bug by avoiding calling non-existing IDE2 code when installing a lib/platform. For the index updates, everything remains the same in IDE2.
To verify:
- Start IDE2 from a terminal or open DevTools in the browser window,
- Install a couple of libraries and platforms. It should work. It fails from the `main` (61a11a0)
Closes #1529
=> #1529 Avoid using `reportResult` if installing lib/core

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/boards/boards-widget-frontend-contribution.ts, arduino-ide-extension/src/browser/library/library-widget-frontend-contribution.ts, arduino-ide-extension/src/browser/widgets/component-list/list-widget-frontend-contribution.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/common/protocol/library-service.ts, arduino-ide-extension/src/common/protocol/searchable.ts, arduino-ide-extension/src/test/common/searchable.test.ts
~**This PR depends on #1530**~ ✅ 
-----
To search in lib/boards manager from a particular URL.
In action:
https://user-images.githubusercontent.com/1405703/191589097-4dd4b82a-d95e-436b-80c1-a240f0289bf3.mp4
Test with:
```cpp
void setup() {}
void loop() {}
// Additional Board Manager URL:
// https://raw.githubusercontent.com/sparkfun/Arduino_Apollo3/main/package_sparkfun_apollo3_index.json
//
// http://boardsmanager/All#SparkFun_Apollo3
// ~http://boardsmanager/All#SparkFun%20Apollo3~ UNSUPPORTED. Use underscore (_) instead of `%20` (URL encoded space)
// http://librarymanager/All#SparkFun_u-blox_GNSS
// ~http://librarymanager/All#SparkFun%20u-blox%20GNSS~ UNSUPPORTED. Use underscore (_) instead of `%20` (URL encoded space)
// http://librarymanager/All/Display#SparkFun
// …
```
=> #1442 Link resolver for lib/boards manager

arduino-ide-extension/src/browser/style/index.css
Fix bottom status bar(or top tool bar when click the `output` title) is clipped by allowing the `DockPanel` has a wider height range.
Make the total height of the split children less than the preset [minHeight](https://github.com/arduino/arduino-ide/commit/99664ee544d146c43a047547ea37e035eb90ff95) as much as possible.
Related to #1515 #1151 #779 #662
=> Fix status bar clipped in minimal state

arduino-ide-extension/src/browser/contributions/first-startup-installer.ts
~**This PR depends on #1530.**~ ✅ 
-----
This PR ensures that the `Arduino_BuiltIn` will be installed on the first start in case of absence.
To verify:
- Follow the steps described in #1526.
- After the first installation, the `Arduino_BuiltIn` library must be installed instead of any pseudo-random library containing either `Arduino` or `BuiltIn` as metadata.
Closes #1526
----
Local verification after wiping the `localStorage` content and starting IDE2.
```
Platform arduino:avr@1.8.5 already installed
Already installed Servo@1.1.8
Already installed Stepper@1.1.3
Already installed Ethernet@2.0.1
Already installed Firmata@2.5.8
Already installed Keyboard@1.0.4
Already installed LiquidCrystal@1.0.7
Already installed Mouse@1.0.1
Already installed SD@1.2.4
Already installed TFT@1.0.6
Already …
```
=> #1526 Ensure exact match when installing `Arduino_BuiltIn` on the first IDE2 startup

arduino-ide-extension/src/browser/style/main.css
Better tooltips.
https://user-images.githubusercontent.com/111981763/192629607-879de343-178e-4496-96c9-d5f2c8f8613d.mp4
=> Better tooltips.

arduino-ide-extension/src/browser/style/list-widget.css, arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx
If the version selected from the drop-down menu overlaps the next element, the focus on the current element is lost and the "INSTALL" button is no longer visible. Details [here](https://github.com/arduino/arduino-ide/issues/1425).
Keep the footer visible until installation is performed. (NOTE: The selection from the drop-down menu is not visible in the video because it wasn't captured by the screen recorder).
https://user-images.githubusercontent.com/94986937/194260064-b45b8e55-3897-4c11-b101-1b825fe12e70.mp4
Closes #1425.
=> Retain Library/Boards Manager installation interface using version menu

arduino-ide-extension/src/browser/boards/boards-data-menu-updater.ts, arduino-ide-extension/src/browser/contributions/board-selection.ts, arduino-ide-extension/src/browser/contributions/sketch-control.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts
The IDE needs to sort the menu for each platform in **Tools > Board** (e.g., **Tools > Board > Arduino AVR Boards**) according to the order of occurrence of the `name` property for each board definitions in the platform's [`boards.txt` configuration file](https://arduino.github.io/arduino-cli/dev/platform-specification/#boardstxt).
- use `listall` instead of `search` command in the arduino-cli
- add a proper order to the menu item when registering a board
- update the arduino-cli to use the sorting fix
Fixes #802.
This needed a fix in the CLI to get the correct order: https://github.com/arduino/arduino-cli/pull/1903
This PR is in **draft** because there isn't a release for the arduino-cli yet, but it can already be tested.
**Arduino IDE 2.x** _before_ this change:
**Arduino IDE 2.x** …
=> Fix boards listing

arduino-ide-extension/src/browser/boards/boards-config.tsx, arduino-ide-extension/src/browser/boards/boards-service-provider.ts
Listen on the client's port changes to fix intermittent failure to recognize ports.
The problem was that the _board select_ dialog was listening on the backend's board/port changes to show the available ports in the dialog. This was fundamentally incorrect as the following use case could happen.
- Attach boards,
- Start IDE2,
- Backend starts and detects the boards and ports via the `board list -w` gRPC equivalent, dispatches board/port change event **but** client is not started yet,
- Client starts,
- Initialize the dialog with zero ports (this is common practice to init with empty),
- Listen on the backend board/port changes (event never arrives),
- Attach/detach a board, and the ports section in the dialog starts working.
It was never an issue with the `Tool` > `Port` menu, as it was …
=> #573 Listen on the client's port change event

arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/style/list-widget.css, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx, i18n/en.json
Do not expose implementation details in the translation files. Related comment: https://github.com/arduino/arduino-ide/pull/1341#discussion_r950823868
This PR is a follow-up of #1507. Use no `uppercase` letters. CSS will do the trick [here](https://github.com/arduino/arduino-ide/blob/945a8f48412ddfd398192e5997b14f71534b09d6/arduino-ide-extension/src/browser/style/list-widget.css#L115) and [here](https://github.com/arduino/arduino-ide/blob/945a8f48412ddfd398192e5997b14f71534b09d6/arduino-ide-extension/src/browser/style/list-widget.css#L122).
This PR also changes the default translations of the following UI labels as requested in https://github.com/arduino/arduino-ide/pull/1521#pullrequestreview-1130249047:
- `GO TO CLOUD` ->. `Go to Cloud`, and
- `INSTALL` -> `Install`,
To verify:
- Open …
=> Let CSS do the uppercase transformation.

arduino-ide-extension/src/browser/boards/boards-service-provider.ts, arduino-ide-extension/src/browser/contributions/user-fields.ts
It is common for a "port" to be used in some way during the process of uploading to a board. However, the array of Arduino boards is very diverse. Some of these do not produce a port and their upload method has no need for one.
For this reason, the IDE must allow the upload process to be initiated regardless of whether a port happens to be selected. During the addition of support for [user provided fields](https://arduino.github.io/arduino-cli/dev/platform-specification/#user-provided-fields) (https://github.com/arduino/arduino-ide/pull/550), an unwarranted assumption was made that all boards require a port selection for upload and this resulted in a regression that broke uploading for these boards. This regression was especially user unfriendly in that there was no response whatsoever …
=> Allow uploads without port selection

arduino-ide-extension/src/browser/contributions/board-selection.ts
The Port submenu Section Heading for different protocols was being displayed at the bottom which is now corrected to show at top.
PR #1520 introduced this regression wherein the padStart method was used to fix sorting of entries in Boards and Port menu. However, this was missed for the Port Submenu Section headings.
Fixes #1566
=> Fix #1566 : Port submenu section heading show at top

arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx, arduino-ide-extension/src/browser/dialogs/settings/settings-step-input.tsx, arduino-ide-extension/src/browser/style/settings-step-input.css
It's difficult for the user to edit the font size in the preferences using the keyboard.
On the current state, when a user tries to edit the value of the font size with the keyboard, the value would update unexpectedly.
For example:
- the font size is 72
- focus the input field
- press BACKSPACE
- expected: the font size is 7; result: the font size is 8 😢 
- now press 1
- expected: the font size is 81; result: the font size is 72 😢 
The reason is we validate the user input _as they type_, and if the input is invalid, we change the value to a valid one.
With this change, I want to validate the user input _as they finished typing_ instead of _as they type_. In order to achieve that, I used the `onBlur` callback of the input field, so that the user can type whatever they want in the input …
=> Let the user edit the font size settings with the keyboard

arduino-ide-extension/src/node/arduino-daemon-impl.ts
To avoid encoding text to JSON on the CLI side.
Dropped the `--log-format json` options from the daemon spawn args.
Closes #1544
=> #1544 Changed the daemon output from `json` to `text`

arduino-ide-extension/src/browser/widgets/component-list/component-list-item.tsx, arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-item-renderer.tsx
At present in the IDE2 when hovering over an item in the library or board manager the item height changes, shifting the position of all library items in the manager. We should avoid this behavior because it is not ideal and could be considered "inaccessible."
Retain the version drop-down and the install button always visible in the item.
=> Prevent layout shift on hover in libs/board manager

arduino-ide-extension/package.json
Bump `arduino-fwuploader` to version [`2.2.2`](https://github.com/arduino/arduino-fwuploader/releases/tag/2.2.2)
=> bump arduino-fwuploader to `2.2.2`

arduino-ide-extension/package.json, electron-app/package.json, package.json
On every startup, the Arduino IDE checks for new versions of the IDE. If a newer version is available, a notification/dialog is shown offering an update.
"Newer" is determined by comparing the version of the user's IDE to the latest available version on the update channel. This comparison is done according to [the Semantic Versioning Specification](https://semver.org/) ("SemVer").
In order to facilitate [beta testing](https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md#beta-testing-guide), builds are generated of the Arduino IDE at the each stage in development. These builds are given an identifying version of the following form:
- `<version>-snapshot-<short hash>` - builds generated for every push and pull request that modifies relevant files
- …
=> Bump version metadata post release

.github/workflows/build.yml, .github/workflows/check-certificates.yml, .github/workflows/compose-full-changelog.yml, .github/workflows/sync-labels.yml
GitHub Actions provides the capability for workflow authors to use the capabilities of the GitHub Actions ToolKit package directly in the `run` keys of workflows via "[workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)". One such command is `set-output`, which allows data to be passed out of a workflow step as an output.
It has been determined that this command has potential to be a security risk in some applications. For this reason, GitHub has deprecated the command and a warning of this is shown in the workflow run summary page of any workflow using it:
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
=> Migrate workflows from deprecated `set-output` commands

arduino-ide-extension/src/node/exec-util.ts
To avoid hitting a _no newline at the end of file_ problem with the formatted.
Do not trim the stdout of `clang-format` process.
Closes #1487
=> fix: do not trim stdout of `clang-format` process

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/node/utils/errors.ts, scripts/i18n/transifex-pull.js
To fix missing `Open Recent` menu items in IDE2 when `~/arduinoIDE/recent-sketches.json` contains non-existing sketches.
The PR consists of three noteworthy changes:
- IDE2 gracefully handles `ENOENT` (No such file or directory) error when trying to detect if the `NotFound` error received from the CLI is an _"invalid sketch name"_ error.  See: #1563.
- Generalized `ErrnoException`([`errno(3)`](https://man7.org/linux/man-pages/man3/errno.3.html)) detection in IDE2.
- Relaxed when IDE2 tries to detect the _"invalid sketch name"_ error. IDE2 must access the filesystem to detect this error. From now on, the special error detection code must be explicitly requested by clients. This change does not affect IDE2's service APIs and recovery behavior. Still, for example, when populating the `Open …
=> fix: Handle gracefully when trying to detect invalid sketch name error and folder is missing on filesystem

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/close.ts, arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts, arduino-ide-extension/src/browser/contributions/new-sketch.ts, arduino-ide-extension/src/browser/contributions/open-sketch.ts, arduino-ide-extension/src/browser/contributions/save-sketch.ts, arduino-ide-extension/src/browser/create/create-uri.ts, arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts, arduino-ide-extension/src/browser/style/dialogs.css, arduino-ide-extension/src/browser/style/sketchbook.css, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-model.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-widget.ts, arduino-ide-extension/src/browser/widgets/sketchbook/create-new.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-composite-widget.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx, arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts, i18n/en.json
To create a remote sketch from IDE2 without opening https://create.arduino.cc/editor in a browser.
- `File` > `New` has been renamed to `File` > `New Sketch`.
- New menu item to create a remote sketch from IDE2: `File` > `New Remote Sketch`.
- If not signed into Arduino Cloud, the menu item is disabled.
- If the _Remote Sketchbook_ is hidden, the menu item is not visible. (`Advanced` > `Show/Hide Remote Sketchbook` or `"arduino.cloud.enabled": false` in `settings.json`)
- Can create a new sketch from the sketchbook.
https://user-images.githubusercontent.com/1405703/199044937-c482cb79-d827-4ecc-8e79-371a97b568fc.mp4
- When logged in to Arduino Cloud and the _Remote Sketchbook_ is not hidden, can create a new remote sketch from the Sketchbook. …
=> #1580 Create remote sketch

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
To allow opening a second sketch from the command line.
- Fix incorrect logic when detecting if the arg is a valid sketch,
- Allow opening a second instance on macOS.
Closes #1590
=> fix: avoid ENOTDIR when opening second instance. 

arduino-ide-extension/src/node/sketches-service-impl.ts
To open built-in examples from an AppImage.
Relaxed the condition to check if a resource exists.
The original (`fs-extra`-based) implementation did not check if the file is writable either.
Resources are not writable in mounted AppImages.
Closes #1586
=> fix: relaxed condition to check if resource exists

arduino-ide-extension/package.json, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, yarn.lock
If regex patterns are not correctly escaped, they will break. Such as the `File` > `Sketchbook` issue when there is a sketch with the following invalid name: `bar++`.
- Reuse the regex pattern escape mechanism from VS Code.
- Remove strict [`is-valid-path`](https://www.npmjs.com/package/is-valid-path) check. Otherwise, on Windows, it's impossible to open a sketch in the following way: `"Arduino IDE.exe" "..\\..\\Documents\\Arduino\\bar++"` input will give a false negative result.
Closes #1600
=> fix: escaped regex chars in pattern

arduino-ide-extension/src/browser/contributions/open-sketch-files.ts, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, arduino-ide-extension/src/node/sketches-service-impl.ts
This PR is to fix the flawed timing issue when opening editors.
- From now on, the editor widget open promise resolution does not rely on internal Theia events but solely on @phosphor's `isAttached`/`isVisible` properties. The editor widget promise resolves with the next task after a navigation frame so the browser can render the widget.
- Generalized the invalid sketch name error handling and removed the CLI error messaging parsing logic due to arduino/arduino-cli#1968.
For the testing, please use the [1612-sketches.zip](https://github.com/arduino/arduino-ide/files/9961315/1612-sketches.zip) archive. (However, you're allowed to use your own setup.)
`1612-sketches.zip`:
```
.
├── invalid-sketches
│   ├── Bar
│   │   └── xxx.ino
│   └── foo
│       └── Foo.ino
└── valid-sketches
└── …
```
=> fix: flawed timing issue when opening editors

arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts, arduino-ide-extension/src/browser/style/dialogs.css, i18n/en.json
Show progress when creating the remote sketch.
https://user-images.githubusercontent.com/1405703/201692728-c409fe51-5419-4181-8ff3-058603c97787.mp4
Closes #1668
=> feat: progress for the remote sketch creation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
The project's [issue forms](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) are configured to request the contributor to test using the [nightly build of Arduino IDE](https://www.arduino.cc/en/software#nightly-builds) before submitting an issue in order to make sure the bug or feature request has not already been resolved.
Some time ago, the repository's readme contained a table of download links. The links in the issue forms pointed there. That table was replaced with a link to [the official "Software" page](https://www.arduino.cc/en/software) in order to reduce unnecessary verbosity and maintenance burden of the project's documentation content …
=> Fix nightly build links in issue forms

arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
Fix bug when ensuring that an already editor is opened.
I have corrected the condition so that the promise can correctly resolve immediately. It did not cause a performance issue, as no callers have been awaiting the promise.
Closes #1718
=> fix: editor widget resolving when creating new tab

arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts
Shortcuts to switch between tabs not working on MacOS
Change the keybindings to switch between tabs from `ctrlcmd+...` to `ctrl+...` on MacOS.
Closes #1685
=> Fix keybindings to switch between tabs on MacOs

arduino-ide-extension/src/browser/contributions/open-sketch-files.ts, arduino-ide-extension/src/browser/theia/core/frontend-application.ts
**Depends on #1662**
----
To activate the editor of the main sketch file when opening the workspace (with the sketch) for the first time.
The _open sketch files_ contribution can now focus on the main sketch file.
To verify:
- Get the attached sketch from #643
> 1. Download this demonstration multi-file sketch: [MultipleFiles.zip](https://github.com/arduino/arduino-ide/files/7631481/MultipleFiles.zip)
- Open the sketch. For example: `"Arduino IDE.exe" ..\\..\\Documents\\Arduino\\MultipleFiles`; the main sketch file has the focus, and the cursor blinks in the editor.
- Select the other sketch file with `// hello`
- Quit IDE2,
- Start IDE2; the focus is not on the editor of the main sketch file.
Closes #643
=> fix: main sketch file editor focus on layout reset

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/dialogs/settings/settings.ts, i18n/en.json
**Depends on #1662**
----
To align the IDE2 codebase with the preferences provided by the Theia framework.
**Breaking**
- Users' `arduino.window.zoomLevel` setting will be ignored. Users have to set the preferred zoom level in one of the following ways:
- <kbd>Ctrl/⌘</kbd>+<kbd>=</kbd> and <kbd>Ctrl/⌘</kbd>+<kbd>-</kbd>,
- `File` > `Increase Font Size` and `File` > `Decrease Font Size` (assuming that the interface scale is automatic),
- Open the Settings dialog, and use the _Interface Scale_ stepper
to readjust the desired scale level.
Alternatively, users can restore the interface scale value via the [_Adcanced Settings_](https://github.com/arduino/arduino-ide/blob/main/docs/advanced-usage.md#advanced-settings):
Currently, when opening the `settings.json` in the file, there is a …
=> chore: Switched to `window.zoomLevel` preference 

arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
The new remote sketch creation must work from `File` > `New Remote Sketch` or <kbd>Ctrl/Cmd</kbd>+<kbd>Alt</kbd>+<kbd>N</kbd> when a user is logged in, but the _Remote Sketchbook_ is not the active tree inside the _Sketchbook_ view.
New API to access all widgets besides the currently selected one.
Closes #1715
=> fix: remote sketch creation if tree is not active

arduino-ide-extension/package.json, arduino-ide-extension/src/node/monitor-service.ts, yarn.lock
**Depends on #1662**
----
Do not send monitor settings changes when there are no settings updates.
I wanted to keep the changeset as small as possible. From now on, `setSettings` promise resolves with `undefined` if there are no effective monitor settings updates. In such a case, the IDE2 monitor service does not send a `MonitorRequest` to the CLI.
Closes #375
=> fix: update monitor settings only if it's changed

.vscode/launch.json, arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/theia/debug/debug-action.tsx, arduino-ide-extension/src/browser/theia/debug/debug-session-contribution.ts, arduino-ide-extension/src/browser/theia/debug/debug-session-manager.ts, arduino-ide-extension/src/browser/theia/debug/debug-session.ts, arduino-ide-extension/src/browser/theia/debug/debug-stack-frame.ts, arduino-ide-extension/src/browser/theia/debug/debug-thread.ts, arduino-ide-extension/src/browser/theia/debug/debug-toolbar-widget.tsx, arduino-ide-extension/src/browser/theia/plugin-ext/debug-main.ts, arduino-ide-extension/src/browser/theia/plugin-ext/hosted-plugin.ts, arduino-ide-extension/src/browser/theia/plugin-ext/plugin-debug-session-factory.ts, arduino-ide-extension/src/browser/theia/plugin-ext/plugin-debug-session.ts, arduino-ide-extension/src/browser/theia/plugin-ext/plugin-menu-command-adapter.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/theia/core/messaging-contribution.ts, arduino-ide-extension/src/node/theia/plugin-ext/plugin-reader.ts, package.json
~**Depends on #1662**~ ✅ 
----
To use a more recent version of the `cortex-debug` VS Code extension. 
Closes #246
Closes #1582
=> feat: Updated to `cortex-debug@1.5.1`

.github/workflows/build.yml
The "Arduino IDE" [GitHub Actions workflow](https://docs.github.com/actions/using-workflows/about-workflows) generates a changelog from the commits since the last tag.
This changelog is published in multiple ways:
- Printed to workflow run logs
- Uploaded to Arduino's download server (mostly useful for the [nightly builds](https://www.arduino.cc/en/software#nightly-builds))
- Initial version of [release notes](https://github.com/arduino/arduino-ide/releases)
For the last, the changelog text must be passed from the dedicated changelog generation workflow step to the release step. This is done via a workflow job output.
At the time the system was set up, outputs for workflow `run` steps were set using the `set-output` workflow command. That "workflow command" system was later determined by …
=> Fix formatting of generated release notes

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/open-settings.ts
To fix the `Preferences` menu enablement issue.
- Manually update the menus when executing the command.
- Also disabled the menu when the settings dialog is opened.
Closes #1735
=> fix: `Preferences` menu enablement defect

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/core/theming.ts, arduino-ide-extension/src/browser/utils/window.ts
Copy and use custom VS Code themes in IDE2.
Fixed dependency injection of the theme service. With the correct theme service binding, IDE2 can access themes from the [`indexedDB`](https://developer.mozilla.org/en-US/docs/Web/API/indexedDB).
To verify:
- download a VS Code theme VSIX. (I used this for the verification: https://marketplace.visualstudio.com/items?itemName=N7n.n7-vscode-themes),
- rename the downloaded `.vsix` to `.zip`, unarchive it, and copy it under the `resources/app/plugins` folder. On macOS, it looks like this.
- Start IDE2 and open the settings dialog,
- You can see the new themes in the themes dropdown.
- When you select it, it works.
- Restart IDE2. The current custom theme is what you have selected.
Closes #1742
=> fix: theme service binding

.github/workflows/check-certificates.yml
The "Check Certificates" GitHub Actions workflow uses [**OpenSSL**](https://www.openssl.org/) to check for problems with the project's signing certificates.
Certificates exported to [PKS #12](https://en.wikipedia.org/wiki/PKCS_12) archive files using older tools may have been encrypted using the ["RC2-40-CBC" algorithm](https://en.wikipedia.org/wiki/RC2).
Due to the availability of more secure modern alternatives, [default support for RC2-40-CBC encryption was dropped in **OpenSSL** 3.x](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#PKCS-12-API-updates).
The macOS signing certificate uses this RC2-40-CBC encryption.
The "Check Certificates" GitHub Actions workflow runs on [the `ubuntu-latest` runner](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-git …
=> Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS#12

arduino-ide-extension/src/browser/boards/boards-data-menu-updater.ts
As per request from #343, IDE2 shows the selected board config value on the menu item.
https://user-images.githubusercontent.com/1405703/206217908-c99d066a-cad9-4c6a-867c-7150554439e9.mp4
Append the selected board config value to the menu label.
Closes #343
=> feat: show the selected board config value on menu

arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx
Fix the search options behavior of the library and boards manager widget when programmatically opening them.
- When the widget is opened the first time with any search options, the widget might miss the refresh event as it does not happen at instantiation time. This PR ensures that all list widget refresh events wait until the React component is rendered and is visible in the UI.
- This change also ensures that the debounced search will run with the most recent search options by setting the `trailing` property of the debounced function to `true`.
Closes #1740
=> fix: list view filtering when opening the view

arduino-ide-extension/src/node/monitor-service.ts
=> Fix corruption of incoming UTF-8-encoded serial data

arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/examples.ts, arduino-ide-extension/src/browser/contributions/interface-scale.ts, arduino-ide-extension/src/browser/contributions/new-cloud-sketch.ts, arduino-ide-extension/src/browser/contributions/open-settings.ts, arduino-ide-extension/src/browser/contributions/upload-certificate.ts, arduino-ide-extension/src/browser/contributions/upload-firmware.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/user-fields.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, arduino-ide-extension/src/browser/theia/core/common-frontend-contribution.ts
Fixes the `Sketch` > `Upload`/`Upload Using Programmer` menu items enablement. This PR is related to arduino/arduino-ide#1735 and covers arduino/arduino-ide#1533.
---- 
IDE2 switched from always-enabled menu items to dynamic ones with [this](https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc#diff-2635a822041da8b5a20323e233457da36a84db3817c6bd3ba9e7e944fefca04aR155-R157) change and [here](https://github.com/arduino/arduino-ide/commit/7d6a2d5e3340aabc1e635d508509dc92a4000fdc#diff-2635a822041da8b5a20323e233457da36a84db3817c6bd3ba9e7e944fefca04aR245) is the crucial part.
Without rebuilding the entire menu, there is no way to support a dynamic menu in an electron app. So in Theia, the menu is calculated at startup, and all menu items are always enabled even …
=> fix: menu item enablement issues

.eslintrc.js, arduino-ide-extension/src/browser/dialogs/cloud-share-sketch-dialog.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, electron/.gitignore, electron/build/template-package.json, electron/packager/index.js, electron/packager/npm-registry/config.yml, electron/packager/package.json, electron/packager/test/utils.test.js, electron/packager/yarn.lock, package.json, yarn.lock
- Speed up the build by eliminating the copy phase (this change does not affect the app signing or the ZIP structure modification part, solely the build by saving time with a filesystem copy and a `yarn install`),
- Simplify the packager by getting rid of the `file:` local path (the `arduino-ide-extension` npm package can be picked up from the private npm registry),
- Update to `lerna@6.1.0` (this change should help IDE2 to keep up with Theia and eliminates various [`dependabot`](https://github.com/dependabot) alerts),
- Fix incorrect `electron` imports in the code (`electron` must not be imported directly but from `@theia/core/electron-shared`),
- Remove unnecessary `electron-builder` `resolutions` for `yarn` (no need for it with the `@theia/*@1.3.1` version), and
- Lint the app packager …
=> build: use a local npm registry for app packaging

arduino-ide-extension/src/common/protocol/config-service.ts
This PR should fix #1775
Remove the trailing colon when parsing the protocol in URL string
=> Remove trailing colon when parsing the protocol from URL

arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx
Fixes #1769
The net/http package in arduino-cli supports `socks5` as scheme rather than `socks`. This PR replaces `socks` with `socks5` in proxy protocol to make socks proxy work.
1. Replaces `socks` with `socks5` in proxy protocol
2. Show `SOCKS5` in `Preferences`->`Network`
=> Replace socks with socks5 in proxy protocol

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/config/config-service-client.ts, arduino-ide-extension/src/browser/contributions/add-zip-library.ts, arduino-ide-extension/src/browser/contributions/archive-sketch.ts, arduino-ide-extension/src/browser/contributions/board-selection.ts, arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/examples.ts, arduino-ide-extension/src/browser/contributions/include-library.ts, arduino-ide-extension/src/browser/contributions/open-sketch.ts, arduino-ide-extension/src/browser/contributions/save-as-sketch.ts, arduino-ide-extension/src/browser/contributions/sketchbook.ts, arduino-ide-extension/src/browser/dialogs/settings/settings.ts, arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts, arduino-ide-extension/src/browser/menu/arduino-menus.ts, arduino-ide-extension/src/browser/notification-center.ts, arduino-ide-extension/src/browser/theia/core/tab-bar-decorator.ts, arduino-ide-extension/src/browser/theia/markers/problem-manager.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-model.ts, arduino-ide-extension/src/common/protocol/config-service.ts, arduino-ide-extension/src/common/protocol/notification-service.ts, arduino-ide-extension/src/common/protocol/sketches-service-client-impl.ts, arduino-ide-extension/src/electron-browser/theia/core/electron-main-menu-factory.ts, arduino-ide-extension/src/node/clang-formatter.ts, arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/notification-service-server.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, i18n/en.json
- Handle invalid `directories.user` path in `arduino-cli.yaml` at app startup.
- Change the sketchbook location from IDE2 without a restart.
- Show the `File` > `Sketchbook` menu item even if no sketches are in the folder.
- Show the `Tools` > `Port` menu item even if there are no available ports.
Preview:
https://user-images.githubusercontent.com/1405703/207853423-3c1e3502-9904-49d2-b2af-8ef01367af19.mp4
- IDE2 can start when `directories.user` is invalid or does not exist.
- If `directories.user` is not a valid directory, IDE2 toasts an error message at startup.
- `Save As...`, `Open`, `Archive Sketch`, and `Add .ZIP Library...` are fully functional when there is no valid `directories.user` value is set.
- If `directories.user` does not exist, IDE2 tries to create the folder.
- It's …
=> feat: configure sketchbook location without restart

arduino-ide-extension/src/browser/contributions/about.ts, arduino-ide-extension/src/common/protocol/config-service.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/config-service-impl.ts, i18n/en.json
To speed up the load time of the _About_ dialog in IDE2. As requested in #1572, IDE2 reads the CLI version from the `package.json`.
- 2.0.3:
- A dev build with the changes:
- Local IDE2 build with the changes:
If the CLI version is a pinned commitish and not a semver, IDE2 will show the commitsh.
Assuming the following pinned CLI version:
```diff
diff --git a/arduino-ide-extension/package.json b/arduino-ide-extension/package.json
index 1b7cc2de..ab4414ea 100644
--- a/arduino-ide-extension/package.json
+++ b/arduino-ide-extension/package.json
@@ -159,7 +159,7 @@
],
"arduino": {
"cli": {
-      "version": "0.29.0"
+      "version": "alma"
},
"fwuploader": {
"version": "2.2.2"
```
The expected _About_ dialog (with a dev build) is:
Closes #1572
----
It should be possible to run `arduino-cli …
=> feat: no remote fetch when IDE gets CLI version

arduino-ide-extension/src/browser/theia/editor/editor-contribution.ts
The editor encoding is not represented on the status bar anymore.
Start IDE, and see that the encoding is not present in the UI:
Closes #1393
=> feat: removed encoding from the status bar

arduino-ide-extension/src/browser/notification-center.ts, arduino-ide-extension/src/common/protocol/notification-service.ts, arduino-ide-extension/src/node/library-service-impl.ts, arduino-ide-extension/src/node/notification-service-server.ts
After installing a library from a ZIP, IDE2 must update the `File` > `Examples` and `Sketch` > `Include Library` menus to show the freshly installed library (if the selected board is appropriate).
- You have the AVR core installed, start IDE2 and select the Uno board,
- Check `File` > `Examples` and `Sketch` > `Include Library` menus, `ArduinoMDNS` is not present.
- Follow the steps from https://github.com/arduino/arduino-ide/issues/659, they're excellent, and the get the library from the ZIP,
- Install it with `Sketch` > `Include Library` > `Add ZIP Library...`
- After the installation, check the `File` > `Examples` and `Sketch` > `Include Library` menus, `ArduinoMDNS` is present.
https://user-images.githubusercontent.com/1405703/211270612-5e4142bb-6093-431c-9001-697ea749 …
=> fix: update Examples and Include Library menu after ZIP install

arduino-ide-extension/src/browser/contributions/add-file.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts
As asked for in #284, IDE2 can now add source files to the sketch folder root. Other files go into the `data` folder in the sketch folder root.
- code files will be copied to the sketch folder root
- other files go under the `data` folder in the sketch folder root
- after adding code files to the sketch, new files are expected to open in an editor.
https://user-images.githubusercontent.com/1405703/211023968-00185533-0f4f-426a-8e7c-104dca267070.mp4
Closes #284
=> fix: aligned `Add File...` behavior with IDE 1.x

arduino-ide-extension/src/browser/contributions/ino-language.ts
The running LS must be restarted on library/platform install/uninstall events and core client re-init events (the latter is fired when the sketchbook location changes in IDE2) so that IDE2 can provide the correct Arduino language features to the users.
- force restart of the LS on core/lib changes,
- and sketchbook location change
https://user-images.githubusercontent.com/1405703/211280536-5b183aeb-3ca7-4ef8-b02b-3d8f729d17aa.mp4
Closes #670
=> fix: restart LS on lib/core change, client re-init

arduino-ide-extension/src/browser/boards/boards-data-store.ts, arduino-ide-extension/src/browser/contributions/ino-language.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/common/protocol/boards-service.ts
The Arduino Language features must incorporate the settings of the selected board.
From now on, the IDE2 starts the LS with the FQBN decorated with the settings. Open the DevTools and check the console if you're interested:
```
INFO Starting language server: teensy:avr:teensy41:usb=serial,speed=600,opt=o2std,keys=en-us
```
Also, from now on, the LS restarts when the user changes the board settings of the currently running LS.
- See the excellent instructions from #1029.
- Also, the LS updates if you change `Tools` > `USB Type`  from `Serial` to `Raw HID` and vice versa. This can be verified with the [`textDocument/hover`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover) in the editor.
In action: …
=> fix: start the LS with the board specific settings

.gitignore, .vscode/settings.json, arduino-ide-extension/package.json, arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/test/node/monitor-settings-utils.test.ts, arduino-ide-extension/src/test/node/sketches-service-impl.test.ts
To fix the sketchbook folder structure in IDE2: `File` > `Sketchbook`
I completely rewrote the logic. The best is to verify with the test sketchbook IDE2 uses: [`__test_sketchbook__`](https://github.com/arduino/arduino-ide/tree/%231185/arduino-ide-extension/src/test/node/__test_sketchbook__).
From now on, IDE2 gracefully handles when the sketchbook location is a sketch folder.
In action:
https://user-images.githubusercontent.com/1405703/211765377-bf904317-f52e-43bd-a44a-3a5f50c09df5.mp4
Closes #1185
=> fix: sketchbook container building

arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/common/protocol/sketches-service.ts, arduino-ide-extension/src/common/utils.ts, arduino-ide-extension/src/node/is-temp-sketch.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, i18n/en.json, package.json
IDE2 should clearly communicate to the user when starting a debug session has failed due to an unverified sketch. In this case, users have to verify the sketch and restart the debug session.
This PR consists of two changes:
- https://github.com/arduino/vscode-arduino-tools/pull/38
- Since the error message parsing is unreliable (https://github.com/arduino/arduino-ide/issues/808#issuecomment-1212750132), IDE2 does not try to match English words but instead calculates the expected temp build output mimicking the CLI. If the error message contains the expected temp build path, IDE2 proposes the user to verify the sketch with a command.
https://user-images.githubusercontent.com/1405703/211327627-43a9aed6-ef3e-4dff-9077-c8279aa9ce7d.mp4
- attach your Arduino Zero board to the …
=> feat: handle when starting debug session failed

arduino-ide-extension/package.json, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts, electron/packager/index.js, package.json
~## Depends on #1809~ ✅ 
IDE2 wants to provide better UX when debugging an uncompiled sketch (#808). IDE2 must detect erroneous CLI behavior and provide user-friendly actions to achieve this. Currently, it's not trivial to detect the cause of an error (https://github.com/arduino/arduino-cli/issues/1762, https://github.com/arduino/arduino-cli/issues/1968#issuecomment-1306936142) so IDE2 tries to rely on filesystem path detected in the error messages. When the CLI compiles a sketch, it puts the build output into the temp folder. IDE2 tries to guess these temp folder paths from the location of the sketches on the filesystem. Sometimes, there is no deterministic way to determine the temp build output path. There are situations when it's only a guess. See here: …
=> test: added compiler test to verify IDE2's build path calculation is in sync with the CLI

arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts
To fix the flaky test.
- The gRPC core client provider requires an initialized config service when processing the error message received during the `InitRequest`. The actual fix is [here](https://github.com/arduino/arduino-ide/pull/1835/files#diff-f463d1c276a9080ec522ead62c6dd596e5bf330b093b7d51b71738c9795d0fda).
- Additional logging in the config service.
- The tests log into the console.
=> fix: flaky compiler test

arduino-ide-extension/src/browser/contributions/edit-contributions.ts
Arduino IDE's **Edit > Copy for Forum (Markdown)** feature copies the contents of the currently selected editor tab to the clipboard, with ["fenced code block" markup](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) added to provide correct formatting when the content is posted to a platform supporting [**Markdown**](https://www.markdownguide.org/) language such as [Arduino Forum](https://forum.arduino.cc/), GitHub, Stack Exchange, etc.
One of the most common points of friction between the volunteer helpers on the forum and the newcomers requesting assistance is the failure to use the correct markup when posting code. In the best case scenario the code and thread is made less readable and less convenient to copy to the IDE for further investigation. Components of the …
=> Add leading+trailing line break to "Copy for Forum" content

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/boards/boards-list-widget.ts, arduino-ide-extension/src/browser/library/library-list-widget.ts, arduino-ide-extension/src/browser/widgets/component-list/component-list.tsx, arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/browser/widgets/component-list/list-widget.tsx, arduino-ide-extension/src/common/protocol/arduino-component.ts, arduino-ide-extension/src/common/protocol/searchable.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/library-service-impl.ts, arduino-ide-extension/src/test/node/boards-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/library-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/test-bindings.ts
IDE2 modifies the lib/core search items from the CLI. This PR fixes it so that when you search for `SD`, you will get `SD` as the first hit.
I moved the search boosting to the IDE2 backend.
Lib search order
- `'Arduino'` in `types`,
- others
- `'Arduino'` and `'Retired'` in `types`
- `'Retired'` in `types` (note there is no such lib currently)
Core search order
- `'Arduino'` in `types`,
- others
- `'Arduino'` in `types` and `deprecated` is `true`.
- `deprecated` is `true` (note there is no such core currently)
Closes #1106
=> fix: library search boosting

arduino-ide-extension/src/browser/arduino-frontend-contribution.tsx, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/auth/authentication-client-service.ts, arduino-ide-extension/src/browser/auth/cloud-user-commands.ts, arduino-ide-extension/src/browser/contributions/account.ts, arduino-ide-extension/src/browser/menu/arduino-menus.ts, arduino-ide-extension/src/browser/style/cloud-sketchbook.css, arduino-ide-extension/src/browser/theia/core/sidebar-bottom-menu-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-composite-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-contributions.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketchbook-tree-widget.tsx, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-user-status.tsx, i18n/en.json
Moved the Arduino Cloud login from the tree to the sidebar.
New login location:
https://user-images.githubusercontent.com/1405703/218430756-cf160982-f5e3-489d-b90c-890c5e0d9237.mp4
Closes #1877
=> feat: moved login entry point to the side-bar

electron/build/scripts/notarize.js
IDE2 needs a way to manually sign the application on M1. The 'MACOS_FORCE_NOTARIZE' env variable forces the notarization to proceed if not on a CI.
=> build: can force notarization on macOS if not on a CI

electron/packager/config.js
The Arduino IDE update check uses a "channel update info file" on Arduino's download server. This file specifies the latest version of Arduino IDE available from the Arduino download server as well as the download URLs for the release archives.
There is a separate channel file for each host operating system:
- [**Windows**](https://downloads.arduino.cc/arduino-ide/stable.yml)
- [**Linux**](https://downloads.arduino.cc/arduino-ide/stable-linux.yml)
- [**macOS**](https://downloads.arduino.cc/arduino-ide/stable-mac.yml)
Two macOS host architectures are now supported:
- x86 (AKA "Intel")
- ARM64 (AKA "[Apple Silicon](https://en.wikipedia.org/wiki/Apple_silicon)")
These each have their own release archive files. The macOS channel file contains data on both. So the updater must be able to …
=> Use Apple Silicon build artifact name required by electron-updater

arduino-ide-extension/package.json
To ensure we are referencing the most recent arduino-cli release correctly in `arduino-ide-extension > package.json`.
=> Bump CLI to 0.31.0

arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-tree-widget.tsx
Removed unnecessary tree widget update and scroll to node action on mouse over/leave events.
Follow the steps from the [issue description](https://github.com/arduino/arduino-ide/issues/1766); they're excellent. You experience no unnecessary scrolling in the tree. You verify that the inline actions, such `...` for the context menu and pull/push in the cloud tree are rendered and functional when you hover over a node representing a sketch folder.
Closes #1766
=> fix: no unnecessary tree update on mouse over/out

arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/browser/create/create-fs-provider.ts, arduino-ide-extension/src/common/utils.ts
- To fix the encoding of invisible, ambiguous, and non-basic ASCII characters when pulling sketches from the cloud (#449)
- To fix the IDE2 crash when encoding of the cloud sketch content fails (#634)
- Import the [sketch_feb14c.zip](https://github.com/arduino/arduino-ide/files/10805350/sketch_feb14c.zip) sketch to https://create.arduino.cc/editor/,
- Open IDE2, log in, and pull the previously imported sketch from the cloud.
- IDE2 does not crash, and the encoding is correct in the main sketch file.
- Use the `"arduino.sketchbook.showAllFiles": true` settings, open the `.log` files from the sketch folder in an editor, and copy the below content to the top of the log files. Save your editors if auto-save is not on. Do the same with the `ReadMe.adoc`. Push your sketch to …
=> fix: encoding when reading a cloud sketch

arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx, arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-output.tsx
An alternative version of #1889. This PR also fixes #1724.
Scroll to the bottom fix:
https://user-images.githubusercontent.com/1405703/222668221-46b68d3b-ce4b-48ea-ba67-35f6d22b8667.mp4
Update widget content and scroll position after the widget shows:
https://user-images.githubusercontent.com/1405703/222668321-274bd881-f707-498f-bf3b-7b77af29b7a4.mp4
Scroll to the bottom of the monitor widget after the state update.
Closes #1724
Closes #1736
=> fix: scroll to the bottom after the state update

arduino-ide-extension/package.json, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/settings-reader.ts, arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/test/node/settings.reader.test.ts, arduino-ide-extension/src/test/node/test-bindings.ts
Relaxed the `settings.json` parsing in the IDE2's backend. The problem occurred when the `settings.json` contained comments or a trailing comma.
Use `jsonc-parser` and allow comments, a trailing comma, and empty content.
Closes #1945
=> fix: jsonc parsing in the IDE2 backend

docs/internal/release-procedure.md
The Arduino IDE release includes several tool dependencies. Unstable versions of these tools may be pinned provisionally for use with the development version of Arduino IDE, but production releases of Arduino IDE must use production releases of the tool dependencies.
The release manager should check the tool versions before making a release, but this important step is not mentioned in the release procedure documentation.
Add a bundled tools version check step to the release procedure documentation.
=> Add bundled tools version check step to release procedure

arduino-ide-extension/package.json, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/lib_pb.js, arduino-ide-extension/src/node/library-service-impl.ts
To speed up library search in IDE2 by omitting unnecessary information from the CLI via gRPC, such as the library release details.
Use the gRPC equivalent of the new `--omit-releases-details` flag for `lib search`.
The library manager works as in 2.0.4.
Ref: arduino/arduino-cli#2102
=> feat: omit release details to speed up lib search

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/filesystem/file-resource.ts
As noted in https://github.com/eclipse-theia/theia/issues/12327, there could be a race condition when saving the editor model. This PR customizes the file resource resolver to create instances that wait for all running write operations to finish before checking whether the resource is in sync.
It's not trivial to verify the changes. Without this PR, the bug can be reproduced with [these](https://github.com/arduino/arduino-ide/issues/437#issuecomment-1221379270) steps.
https://user-images.githubusercontent.com/1405703/226566369-1a0916cc-bdf8-42fb-914c-e60f28ca7ca0.mp4
I could not reproduce it with my changes, although I repeated the steps ~100 times.
Closes #437
=> fix: let the resource finish all write operation

arduino-ide-extension/src/browser/contributions/open-sketch-files.ts
Avoid duplicate editor tabs when opening a sketch with no previously saved workbench layout.
This PR fixes the incorrect widget key calculation. Two different widget keys have been calculated for the same resource. For example, [this](https://forum.arduino.cc/t/ide-2-0-3-double-tabs/1066585) forum post contains the log files and the widget layout. This is an extract that contains the relevant part:
```json
"mainPanel": {
"main": {
"type": "tab-area",
"widgets": [
{
"constructionOptions": {
"factoryId": "code-editor-opener",
"options": {
"counter": 0,
"kind": "navigatable",
"uri": "file:///c%3A/Users/Wim/Documents/Arduino/MaxMSP/double2float/double2float.0.1/double2float.0.1.ino"
}
},
"innerWidgetState": "{\"cursorState\":[{\"inSelectionMode\":false,\"selectionStart\":{\"lineNumber\":1,\"co …
```
=> fix: incorrect editor widget key calculation

arduino-ide-extension/src/browser/contributions/contribution.ts
I find it inconvenient to switch back to the monitor widget after an upload. I implemented a super simple feature to re-focus the monitor widget after a verify/upload/upload using programmer/burn bootloader command.
Requirements:
- the monitor widget is the current in the bottom panel. It does not necessarily have to have the focus, but when multiple tabs are open at the bottom, the monitor widget is on the top.
- the command execution was successful. This task had no designs or requirements, but it's better to show the error output instead of re-focusing the monitor widget when the command has failed.
I am happy to tweak it to achieve something different behavior. We can also close this PR if not needed. I found it helpful.
In action: …
=> feat: re-focus monitor widget after verify/upload

arduino-ide-extension/src/browser/library/library-list-widget.ts, arduino-ide-extension/src/browser/utils/dom.ts, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-composite-widget.tsx, arduino-ide-extension/src/browser/widgets/sketchbook/sketchbook-widget.tsx
As mentioned in #1720, the focus border looks odd when activating the Sketchbook widget. This PR fixes it.
Before the fix (with `2.0.4`):
https://user-images.githubusercontent.com/1405703/227485376-580320a7-3519-4ae4-9bc4-c2a0cc15722a.mp4
After the fix:
https://user-images.githubusercontent.com/1405703/227485926-cce8346f-0d10-4e21-baf8-bc9bc5f02aaa.mp4
Ref: arduino/arduino-ide#1720
=> fix: the focus in the sketchbook widget

.github/workflows/build.yml
The Linux build does not start occasionally, and GH Actions reports a canceled build. Also, the Linux container used by the IDE2 build is deprecated:
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
Use `ubuntu-20.04` on the CI.
=> ci: use `ubuntu-20.04` for the Linux build

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/monitor-manager-proxy-client-impl.ts, arduino-ide-extension/src/browser/monitor-model.ts, arduino-ide-extension/src/browser/serial/monitor/monitor-view-contribution.tsx, arduino-ide-extension/src/browser/serial/monitor/monitor-widget.tsx, arduino-ide-extension/src/browser/serial/monitor/serial-monitor-send-input.tsx, arduino-ide-extension/src/browser/style/index.css, arduino-ide-extension/src/browser/style/monitor.css, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/common/protocol/monitor-service.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/monitor-manager-proxy-impl.ts, arduino-ide-extension/src/node/monitor-manager.ts, arduino-ide-extension/src/node/monitor-service.ts, arduino-ide-extension/src/node/monitor-settings/monitor-settings-provider.ts, i18n/en.json
This PR enables clear communication of the problem when starting a monitor process fails.
Shows monitor connection status in the `<input>`
- not-connected (board or port is missing),
- connecting (when trying to connect to the monitor port),
- connected ✅, and
- error (the connection has failed for whatever reason, and the user should select another board or close + reopen the widget after fixing any port issues outside of IDE2)
https://user-images.githubusercontent.com/1405703/229084603-3b9ebc3d-9e3b-46c8-a896-9c6939333492.mp4
- Propagate error from backend to frontend via the monitor ws.
- Open the ws connection before creating the monitor duplex. Otherwise, the status update or error cannot reach the frontend.
- Fixed monitor widget DI.
- Fixed monitor service lifecycle inside the …
=> fix: propagate monitor errors to the frontend

arduino-ide-extension/package.json, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js
Use a released version of the CLI in the IDE2.
- Updated to ~`0.32.1`~ `0.32.2` CLI and
- Regenerated the JS/TS API for the CLI.
=> chore: Updated to `0.32.2` CLI

.github/workflows/build.yml, electron/build/template-package.json
To fix the auto-updater defect on Windows caused by a library used by IDE2.
I downloaded the build artifacts and verified them on different OSs:
- macOS (12.3.6) (dmg),
- Linux (Ubuntu 22.04) (zip, AppImage),
- Windows (10 Pro, 21H2) (MSI, interactive installer)
I verified the followings: the app starts, can upload to the board, and the LS works.
- Use `electron-builder@23.6.0`,
- Set the `CSC_FOR_PULL_REQUEST` env variable in the workflow to run the signing part for PRs.
=> fix: updated to `electron-builder@23.6.0`

arduino-ide-extension/src/browser/dialogs/settings/settings.ts
In Theia, the current theme ID is not always in sync with the persisted `workbench.colorTheme` preference value. For example, one can preview a theme with the `CtrlCmd+K` + `CtrlCmd+T` key chords. The theme changes on quick pick selection change events, but the change is persisted only on accept (user presses `Enter`).
IDE2 has its way of showing and managing different settings in the UI. When the theme is changed outside the IDE2's UI, the model could get out of sync. This PR ensures that on `workbench.colorTheme` preference change, IDE2's settings model is synchronized with persisted Theia preferences.
The theme does not revert on interface scale change:
https://user-images.githubusercontent.com/1405703/229155731-7b616842-17af-4290-a4a2-fecdf1641178.mp4
The theme `<select>` reflects the …
=> fix: update `themeId` settings after theme change

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/dialogs/settings/settings-component.tsx, arduino-ide-extension/src/browser/theia/core/theming.ts, arduino-ide-extension/src/browser/theia/monaco/monaco-theming-service.ts, arduino-ide-extension/src/test/browser/theming.test.ts, electron/build/scripts/arduino-ide-electron-main.js, i18n/en.json
~## Depends on #1988~ ✅ 
This PR updates the behavior or the theme `<select>` in the _Settings_ dialog and makes it overall easier to "install" and use custom (VS Code extension-based) themes in IDE2.
1. IDE2 shows only `Light`, `Dark`, and `High Contrast` themes in the _Settings_ dialog.
https://user-images.githubusercontent.com/1405703/229831684-fbba1daf-e8b1-4403-9cf8-a82f912ea501.mp4
2. This PR does **not** change the fully qualified name of the Arduino themes or the behavior of the `Preferences: Color Theme` command contributed by Theia. (Or with the <kbd>Ctrl/⌘</kbd>+<kbd>K</kbd> <kbd>Ctrl/⌘</kbd>+<kbd>T</kbd> key-chord.) Experienced users should use this command to list and select unofficial themes. The quick-pick theme items show the fully qualified names of the Arduino themes to …
=> feat: removed non-official themes from the settings dialog

arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/browser/widgets/cloud-sketchbook/cloud-sketch-cache.ts, arduino-ide-extension/src/test/browser/create-api.test.ts
The sketch cache might be empty when trying to generate the secrets included in the main sketch file from the `secrets` property.
Closes #1999
Please follow the steps from #1999 to reproduce and verify the defect.
=> fix: try fetch the sketch by path if not in the cache

.github/workflows/build.yml
Arduino IDE offers an update to the user when a newer version is available. The availability of an update is determined by comparing the user's IDE version against data file ("channel update info file") stored on Arduino's download server.
These "channel update info files" are automatically generated by the build workflow.
Previously the release process was fully automated, including the upload of the "channel update info files" to the server.
As a temporary workaround for limitations of the GitHub Actions runner machines used to produce the automated builds, some release builds are now produced manually:
- Linux build (because the Ubuntu 18.04 runner was shut down and newer runner versions produce builds incompatible with older Linux versions)
- macOS Apple Silicon build (because GitHub …
=> Don't upload "channel update info files" related to manual builds to S3 on release

docs/advanced-usage.md
Arduino IDE comes with a selection of officially maintained and supported built-in themes:
- Light
- Dark
- High Contrast
Although these three should be sufficient for most users, some users may have other requirements or preferences for the Arduino IDE UI theming.
Fortunately, because it is built on the [**Eclipse Theia** IDE framework](https://theia-ide.org/), Arduino IDE [supports **VS Code** theme extensions](https://theia-ide.org/docs/extensions/#vs-code-extensions). This makes [a large variety of 3rd party themes](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes) available to the user, and even [the ability to create custom themes](https://learn.microsoft.com/en-us/shows/vs-code-livestreams/build-your-own-vs-code-theme).
Instructions for installing VS Code …
=> Document 3rd party theme installation in "Advanced Usage"

arduino-ide-extension/src/node/library-service-impl.ts
To save some part of an excellent work of [@nmzaheer](https://github.com/nmzaheer) from #1611.
> Comparison with Arduino 2.0.2 on the left and Arduino 2.0.1 on the right
> 
> ![gffhfhfhfghf](https://user-images.githubusercontent.com/5036103/199223046-798216a3-9797-4c09-95f2-cc5d196adb8d.png)
Although the _Boards/Library Manager_ UI has been updated in [arduino/arduino-ide#1927](https://github.com/arduino/arduino-ide/pull/1927), the `description` vs. `summary` handling is still a fix IDE2 needs.
Ref: arduino/arduino-ide#1611
=> Corrected library.properties assignment w.r.t description and summary

arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/test/browser/create-api.test.ts
This PR slightly modifies the implementation of [arduino/arduino-ide#875](https://github.com/arduino/arduino-ide/pull/875) to reduce the unnecessary `GET /sketches`. The endpoint claims to support pagination, but it does not. So if the number of sketches can be divided by the `limit` without a remainder, another fetch is required.
This PR does not change the limit but leaves it at 50. This PR adds tests to verify the new behavior. Note that those tests do not run on the CI, only locally when secrets are set in the environment.
To verify:
- you have more than 50 sketches on https://create.arduino.cc/editor,
- open IDE2 and log in to the cloud, and
- verify that you see all you sketches in the cloud sketchbook tree.
=> fix: reduced unnecessary `GET /sketches` request

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/core-client-provider.ts, arduino-ide-extension/src/node/theia/env-variables/env-variables-server.ts, arduino-ide-extension/src/test/node/boards-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/core-client-provider.slow-test.ts, arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/library-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts, arduino-ide-extension/src/test/node/test-bindings.ts, yarn.lock
~## This PR must not be merged before the `2.1.0` release.~ Done ✅ 
IDE2 needs integration tests to verify that the core gRPC client can be initialized for the CLI daemon. This PR is to ensure https://github.com/arduino/arduino-cli/pull/2119 won't break anything.
_Update:_
- Eventually, the tests revealed [arduino/arduino-ide#2021](https://github.com/arduino/arduino-ide/issues/2021) and helped fix the library index recovery to work on `it` and `de` locales by relaxing the CLI error message parsing.
- Copied the env-variable server from Theia and made it possible to customize it for the tests. Each test has its own `data` folder.
- Relaxed the primary package and library index error detection. This should make the init error detection locale independent.
- Kill the daemon process subtree …
=> test: gRPC core client init integration test

arduino-ide-extension/src/browser/create/create-features.ts, arduino-ide-extension/src/browser/local-cache/local-cache-fs-provider.ts, arduino-ide-extension/src/browser/theia/markers/problem-manager.ts
To enable diagnostics for cloud sketches.
As part of `PROEDITOR-50`, the error markers have been disabled for built-ins (daedae1). Then cloud sketches were added to IDE2, but they're in the same root folder where the built-ins are. This PR relaxes the diagnostics filtering and lets it work for the cloud sketchbook cache folder.
- Error diagnostics work with ordinary sketches,
- Error diagnostics work with cloud sketches independently from the user's logged-in status,
- There are still no error diagnostics for built-ins and code from platforms if you navigate into them. (basically, what is in `directory.data` but not in `directory.data/RemoteSketchbook/ArduinoCloud` get filtered)
Closes #669
=> fix: do not exclude cloud sketch diagnostics

arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
Changed the `source` and `cwd` args to avoid accidentally creating an
invalid `glob` patterns when doing the brace expansion by `cpy`.
Please follow the steps from #2043. There are new tests to cover that case.
Closes arduino/arduino-ide#2043
=> fix: copy when punctuation marks in sketch path

arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx, arduino-ide-extension/src/common/protocol/installable.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/library-service-impl.ts, i18n/en.json
IDE2 should notify the user when installing a library/platform has failed.
- Catch any Arduino component install errors and toast the error message to the user.
For the verification, please follow #621.
https://github.com/arduino/arduino-ide/assets/1405703/a4df4e38-185b-47de-8bf5-d9c9dd3397c0
This PR should also cover platform install failures. For example, nothing happens when there is no Internet connection and one tries to install a platform with `2.1.0`. This PR should cover it. Providing a less cryptic error message with no Internet connection is separate from this PR: https://github.com/arduino/arduino-ide/issues/1429.
`2.1.0`:
https://github.com/arduino/arduino-ide/assets/1405703/19e9571d-a316-4e9e-aaa7-ae0ee932fce8
Build from this PR: …
=> fix: show notification if lib/core install failed

arduino-ide-extension/src/browser/theia/filesystem/file-resource.ts
To fix non-functional save behavior when a file resource has conflicts.
All write operations are queued to overcome #437. This PR ensures that when an operation is already queued and fails due to conflict, do **not** queue the subsequent write operation; it's already queued.
https://github.com/arduino/arduino-ide/assets/1405703/1ce7d7b5-466e-41f7-8fcc-6d0c3d9d8e40
[arduino/arduino-ide#1972](https://github.com/arduino/arduino-ide/pull/1972) must still work.
https://github.com/arduino/arduino-ide/assets/1405703/4ed576a3-4014-433e-a293-9c86ccbf3659
Closes #2051
=> fix: do not enqueue write operations on conflict

arduino-ide-extension/src/test/node/core-client-provider.slow-test.ts
It should make integration tests more resilient on the Windows CI.
From now on, tests are not starting a daemon to initialize the `directories.data` folder for the test suites but rely on the raw command. It is required to avoid spawning the discovery processes, which cannot be terminated on Windows while the daemon is up and running.
Steps to verify (probably not possible as the review 😕):
- I expect no flaky integration tests on the Windows CI.
- The nightly builds should get back to normal.
Closes #2059
=> test: use raw `core index-update` for the tests

arduino-ide-extension/src/browser/widgets/component-list/filterable-list-container.tsx
With #2061, IDE2 shows an error notification if an error was caught during the platform/library installation. This is all good, but IDE2 throws `UserAbortError` when the user interrupts the installation process. In such a case, no error notification is needed.
Catch and swallow `UserAbortError` during the installation.
How to verify:
- Please follow the steps from #2063; you will see no error notifications.
- Try to install the `Forced-BME280` library; the installation fails, and the cause of the error is shown to the user as an error notification.
https://github.com/arduino/arduino-ide/assets/1405703/5cf285bf-a9fa-4085-b260-1cbceeab2f60
Closes #2063
Apologies for the double review, Per.
=> fix: show no errors if users cancel lib install

arduino-ide-extension/src/browser/library/library-list-widget.ts, arduino-ide-extension/src/browser/utils/dom.ts, arduino-ide-extension/src/test/browser/dom.test.ts
Setting the `innerHTML` in an unsafe way has been removed, as it is vulnerable to stored Cross-Site Scripting.
I have replaced the `innerHTML` with a series of `<span>` elements optionally containing a `<b>` child. Neither functional nor style changes are expected in IDE2.
`2.1.0` look and feel vs. the build from this PR:
`2.1.0` DOM:
DOM from this PR:
- If you have the `ArduinoIoTCloud` library installed, uninstall it,
- Install the `ArduinoIoTCloud` library,
- IDE2 opens the confirmation dialog,
- Check the UI and compare it with the `2.1.0` release. They should be the same.
Ref: PNX-3669
=> fix: remove setting unsafe `innerHTML`

arduino-ide-extension/package.json, arduino-ide-extension/src/common/protocol/executable-service.ts, arduino-ide-extension/src/node/arduino-daemon-impl.ts, arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts, arduino-ide-extension/src/node/clang-formatter.ts, arduino-ide-extension/src/node/config-service-impl.ts, arduino-ide-extension/src/node/exec-util.ts, arduino-ide-extension/src/node/executable-service-impl.ts, arduino-ide-extension/src/test/node/arduino-daemon-impl.test.ts, arduino-ide-extension/src/test/node/clang-formatter.test.ts, arduino-ide-extension/src/test/node/exec-util.test.ts, yarn.lock
To eliminate the unsafe `shell: true` options when spawning processes. No IDE2 functionality changes are expected.
- removed unnecessary `chai-string` and the corresponding type declarations,
- cleaned up `getExecPath` function and removed another dependency: `which`, and
- added tests for each executable provided by IDE2.
- please put IDE2 on a path with spaces❗,
- CLI is functional, LS works, and you can format the sketch,
- you can flash with the firmware uploader
Ref: PNX-3671
=> fix: removed unsafe `shell` when executing process

arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/test/node/core-service-impl.test.ts
Omit the port object from the compile request so the CLI can correctly fall back to the `default` upload port. This does not work when the `port` object is empty. Only `null` is a valid port value in such a scenario.
Previously, if the `port` was not set in IDE2, the compile request object was created with an empty port object (`{}`). IDE2 will create a compile request with the default `null` `port` value if the port is not specified.
This PR sets the `hardwareId` on the port object. `Port#hardwareId ` has not been used in IDE2 since its introduction.
I went through the steps from #2089, but I am not 100% sure I could follow them. I did the followings:
- Opened 2.1.0, and uploaded the "Soft brick" sketch to my Micro, then CLI/IDE2 couldn't detect my Micro board after. Every upload attempt …
=> fix: omit port from upload request when not set

arduino-ide-extension/src/browser/theia/core/application-shell.ts
Saving any (local and cloud) sketches without an Internet connection must be possible. (Pulling/pushing cloud sketch changes are expected to not work without the Internet.)
The previous logic has incorrectly bailed the save when there is no Internet connection. The corrected logic disallows saving files if there is no connection between the front and backend.
How to verify the fix:
- open IDE2, create a new sketch, turn auto-save off, disconnect from the Internet (you will see the yellow `Offline` status bar),
- modify the sketch and save it. It works. Restart IDE2, and you will see the updated sketch content.
This PR **does not fix** https://github.com/arduino/arduino-ide/issues/2081.
Ref: cff2c956845e04d320231e8a924d1a47ad016af7
Closes #2079
=> fix: relaxed `saveAll` if no Internet connection

arduino-ide-extension/src/browser/contributions/contribution.ts, arduino-ide-extension/src/browser/contributions/save-as-sketch.ts, arduino-ide-extension/src/browser/contributions/save-sketch.ts, arduino-ide-extension/src/browser/theia/core/connection-status-service.ts, arduino-ide-extension/src/test/browser/connection-status-service.test.ts
~## Depends on #2080~ ✅ 
----
IDE2 must warn the users to manually save the sketch content when IDE cannot do it due to a crashed backend process.
Check the `socket.connected` status when calculating the nature of the connectivity problem in the frontend.
Steps to verify: Please see https://github.com/arduino/arduino-ide/issues/2081
Closes #2081
=> fix: warn user when IDE cannot save the sketch

arduino-ide-extension/scripts/download-ls.js
I want to locally build arduino ide on a linux arm64 machine.
Updates one of the build scripts, so that the ide can build succesfully on linux arm64. 
Tested on Orange Pi 5, Armbian distro.
=> add linux-arm64 to download-ls

arduino-ide-extension/package.json, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
To let IDE2 consume https://github.com/arduino/arduino-cli/pull/2234 and keep the repository history clean💄 
This reverts commit 0fbd1fbe85fbbd864ad5e6a00850b32cbd2e83e0.
Reverts: arduino/arduino-ide#2083
=> Revert "chore(cli): Bumped the CLI version to `0.33.0`"

.github/workflows/build.yml, .github/workflows/check-certificates.yml, .github/workflows/check-i18n-task.yml, docs/internal/release-procedure.md
Previously, releases were always made from a point in the revision history of the `main` branch (typically the tip of the branch at the time of the release). Although the simplicity of this approach is nice, it can be limiting in some cases. For this reason, the project is switching to using a "trunk-based" development strategy, as described here:
https://trunkbaseddevelopment.com/
This approach allows making releases at any time that consist of the arbitrary subset of revisions suitable for shipping to the users at that time. The commits that should be included in the release are cherry-picked to a release branch and the tag created on that branch.
This means that:
- PRs can be merged to the `main` branch as soon as they have passed review rather than having to postpone the merge of …
=> Adjust release procedure and CI system for "trunk-based" development strategy

arduino-ide-extension/package.json, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/board_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/common_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/compile_pb.js, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.d.ts, arduino-ide-extension/src/node/cli-protocol/cc/arduino/cli/commands/v1/core_pb.js
Get the latest CLI release into IDE2 nightly.
- Reverts https://github.com/arduino/arduino-ide/commit/d0bce15f8baaa17b0272a5b8c0ba45e5577ed3a9, and
- Set the CLI dependency to `0.33.1`.
Related: https://github.com/arduino/arduino-ide/pull/2119
=> chore(cli): Bumped the CLI version to `0.33.1`

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/update-arduino-state.ts, arduino-ide-extension/src/browser/theia/plugin-ext/hosted-plugin.ts, arduino-ide-extension/src/browser/theia/terminal/terminal-frontend-contribution.ts, arduino-ide-extension/src/browser/theia/terminal/terminal-widget-impl.ts, arduino-ide-extension/src/common/protocol/arduino-context-mapper.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/test/common/arduino-context-mapper.test.ts, arduino-ide-extension/src/test/node/core-service-impl.slow-test.ts, package.json, yarn.lock
The follow-up PR of https://github.com/arduino/arduino-ide/pull/2071.
To provide a way to implement external tools for the Arduino IDE without modifying the IDE codebase. See #58.
This PR introduces a tiny layer of code to listen to Arduino context-related changes and set it on the VS Code extension. Other VS Code extensions can import this new VSIX API and retrieve context information from the Arduino IDE—information such as the sketch path, FQBN of the currently selected board, etc. See [`vscode-arduino-api`](https://github.com/dankeboy36/vscode-arduino-api) for more details.
I have an [ongoing](https://github.com/dankeboy36/esp-exception-decoder/pull/1) reference re-implementation of the well-known [ESP exception decoder](https://github.com/me-no-dev/EspExceptionDecoder/). It works in …
=> feat: expose Arduino state to VS Code extensions

arduino-ide-extension/package.json, electron-app/package.json, package.json
We have to do it after the release. See https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages.
Otherwise, the nightly build will show as an IDE2 update—for example, https://forum.arduino.cc/t/nightly-build-0705-wants-to-update-to-2-1-1/1144912.
Updated from `2.1.1` to `2.1.2`
The tester build should have 2.1.2.-hash version
=> chore(version): updated the version to `2.1.2`

arduino-ide-extension/src/node/arduino-daemon-impl.ts, electron/build/patch/backend/main.js
`debug` messages logged by the Theia logger were not forwarded to the file logger. This PR fixes it.
- In the bundled application, the customized logger that writes the log
files bogusly includes only the first message fragment in the log
message. This PR ensures all message fragments are included in the final
message before it is printed to the console/terminal and persisted to
the rotating log files.
- Includes messages with `debug` severity in the log.
- Disables the ANSI coloring in the CLI daemon log by adding the
`NO_COLOR=true` environment variable to the spawned CLI daemon process.
- Trims trailing line ending of the daemon log.
- Start IDE2 with `debug` log level from a terminal. On macOS, it is similar to `/Applications/Arduino\ IDE\ …
=> fix: include all log `args` in the log message 

scripts/i18n/transifex-pull.js
The localization of the UI strings specific to the Arduino IDE application is done via the Transifex localization platform. A scheduled workflow pulls the data from Transifex weekly and submits a pull request for the updates.
Previously, the script used to pull the data did not clean the data files before pulling. This meant that a vestigial file would accumulate in the repository whenever a language was removed from the Transifex project.
The accumulation is avoided by deleting the data files for the locales managed on Transifex (all locales other than the source English locale) before downloading the data from Transifex.
Fixes https://github.com/arduino/arduino-ide/issues/2152
---
The workflow is configured to only trigger on a schedule and the requirement of the Transifex credentials …
=> Clean localization data files before pulling from Transifex

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-component.tsx, arduino-ide-extension/src/browser/dialogs/certificate-uploader/select-board-components.tsx, arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-component.tsx, arduino-ide-extension/src/common/protocol/board-list.ts, arduino-ide-extension/src/test/common/board-list.test.ts
When multiple boards are discovered on a detected port, the board selector component is broken in the firmware uploader dialog. This PR moves the board inference logic from the UI to the model and allows selecting a board+port pair even before confirming the board in the board list.
This PR pins the CLI version to `0.34.0-rc.1` to overcome the flaky tests mentioned at https://github.com/arduino/arduino-ide/pull/2176#issuecomment-1684790036.
I could reproduce the bug following the steps in #2175. I could fix the bug, but the firmware update fails at the CLI.
I connect my Arduino Nano RP2040 board and start the firmware update, and get all these board list watch logs and the stderr of the executable:
<details><summary>click to see the `board list watch` events and the error log from the …
=> fix: expand boards if available on detected port 

arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/node/utils/errors.ts, arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
IDE2 must gracefully handle when it cannot restore a sketch from a network drive at startup.
This PR relaxes the logic of how IDE2 checks whether a sketch is accessible. From now on, `UNKNOWN` errors are caught, and the missing sketch is not restored.
Closes #2166
=> fix: handle `UNKNOWN` code on `syscall: 'stat'`

arduino-ide-extension/src/browser/contributions/upload-certificate.ts, arduino-ide-extension/src/common/protocol/arduino-firmware-uploader.ts, arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts
Fix the certificate flashing.
Use a `string` array of command flags instead of the concatenated final `string` command.
Ref: arduino/arduino-ide#2067
Closes #2179
I could reproduce and fix the defect, but the certificate flashing failed with the `Error: missing ack on erase: ab` [familiar error](https://github.com/arduino/arduino-ide/pull/2178#issue-1857676149):
```
Error executing /Users/a.kitta/dev/git/arduino-ide/arduino-ide-extension/lib/node/resources/arduino-fwuploader certificates flash -b arduino:mbed_nano:nanorp2040connect -a /dev/cu.usbmodem14301 -u arduino.cc:443: Error: missing ack on erase: ab Error: Error executing /Users/a.kitta/dev/git/arduino-ide/arduino-ide-extension/lib/node/resources/arduino-fwuploader certificates flash -b arduino:mbed_nano:nanorp2040connect -a …
```
=> fix: incorrect certificate flashing command string

.github/workflows/build.yml
The project was recently switched to using a "trunk-based" development strategy (https://github.com/arduino/arduino-ide/pull/2120). This necessitated some adjustments to the [configuration](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions) of the GitHub Actions workflows in order to ensure the CI system could be used to effectively validate the project at the state staged for release in the release branch.
A `run-determination` job was added to the workflow. This job determines whether the conditions under which the workflow was triggered indicate that the rest of the jobs in the workflow should be run.
A validation workflow should run fully under any of the following conditions:
- The [trigger …
=> Do full run of "Arduino IDE" workflow on tag push

arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts, arduino-ide-extension/src/electron-main/theia/theia-api-main.ts
To fix the non-functional `New Tab` content menu item from `•••`. The first context menu item with ID `0` has no click handler.
Customized the default Theia menu item building to attach the click handler to the menu node with ID `0`
Steps to reproduce:
- Open IDE2,
- Create a new sketch (`File` > `New Sketch`, or `Ctrl/Cmd+N`),
- Open the context menu in the editor's toolbar by clicking on `•••`,
- Click `New Tab` the new file dialog opens.
Originally reported here: https://forum.arduino.cc/t/new-tab-command-first-invocation-does-nothing/1160085
Ref: https://github.com/eclipse-theia/theia/pull/12500#issuecomment-1686074836
=> fix: falsy context menu `handlerId`

arduino-ide-extension/src/node/i18n/arduino-localization-contribution.ts
Some of the translation module names have changed in https://github.com/arduino/arduino-ide/pull/2153. We did not know this before merging: https://github.com/arduino/arduino-ide/pull/2031. This PR fixes the `UA` module name.
FIx `UA` translation module name.
=> fix: name of translation (`UA`) module

.github/workflows/compose-full-changelog.yml
Fix the changelog generation.
Pinned `@octokit/rest` to `19.0.13`, so that it works with Node.js 16+.
Closes arduino/arduino-ide#2200
=> fix(ci): fix the changelog generation

.vscode/tasks.json, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, electron-app/arduino-ide-backend-main.js, electron-app/arduino-ide-electron-main.js, electron-app/package.json
Problem: When IDE2 runs in production mode (the app is bundled up), it logs into a file. When IDE2 starts, multiple processes start under the hood. The process hierarchy is like this _electron main_ > _backend main_ >> _plugins_fsWatcher_and_other_subProcesses_. IDE2 logs only in the _backend main_ process and its child processes. The _electron main_ process logging is missing from the generated single log file.
Since the _electron main_ logging is missing, it very often happens that IDE2 does not even start on users' env (due to file permission, IPv6 vs. IPv4 issue, etc.), and the cause (error) is missing from the logs.
- Without introducing a sophisticated logging server and/or message queues, it's impossible to write the same log file stream from different processes.
- I would like to …
=> fix: forward backend logging to electron

arduino-ide-extension/src/browser/contributions/update-arduino-state.ts
To fix a race condition when setting the Arduin state for extensions at app startup. If the board+port state is set before it's read from the `localStorage`, clients will get an `undefined` `fqbn`.
Defer updating the board+port state for extensions when it's ready.
Ref: arduino/arduino-ide#2165
Ref: dankeboy36/esp-exception-decoder#10
Steps to reproduce:
- you have an ESP32 board, the ESP32 platform and the [debugger extension](https://github.com/dankeboy36/esp-exception-decoder#installation) are installed.
- create a new sketch,
- attach the board, select the board and port, and save the sketch,
- upload the sketch,
- open the decoder terminal with the `ESP Exception Decoder: Show Decoder Terminal` command,
- you see the FQBN and the sketch printed to the console,
- quit IDE2,
- start …
=> fix: defer board+port state update for extensions

arduino-ide-extension/src/browser/contributions/user-fields.ts
After #2165, there are no artificial board+port change events in IDE2 at startup. Hence, if the port and board have been set in a previous IDE2 session, no board+port change occurs at the next startup. This PR patches the user-field behavior and makes sure to retrieve the board+port.
Ref: arduino/arduino-ide#2165
Closes arduino/arduino-ide#2230
Related:
- https://github.com/arduino/arduino-ide/pull/2165#pullrequestreview-1568872036
- https://github.com/arduino/arduino-ide/pull/2165#pullrequestreview-1571165467
=> fix: refresh the user-fields at app startup

arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/browser/contributions/examples.ts, arduino-ide-extension/src/browser/contributions/include-library.ts, arduino-ide-extension/src/browser/contributions/selected-board.ts
There are a few regressions in IDE2 after the board+port simplification (#2165). This PR fixes them.
Refresh the following at app startup when the board+port selection has been restored:
- the board+port in the status bar. (this is not a functional bug, but with https://github.com/arduino/arduino-ide/commit/db83ed095bed5cc0151cac4f006581ec2f660a08, an unnecessary refresh has been removed),
- `File` > `Examples` menu (https://github.com/arduino/arduino-ide/commit/20a192afe6d14818ad2be18ac8c53e9fb2c4d671),
- `Sketch` > `Include Library` menu (https://github.com/arduino/arduino-ide/commit/20a192afe6d14818ad2be18ac8c53e9fb2c4d671),
- Debug toolbar item (https://github.com/arduino/arduino-ide/commit/4d04aac56d5af1e502f6a596a641e4bccd43a882)
1. Open IDE2,
2. Create a new sketch …
=> fix: use board+port at startup if it's restored

.github/workflows/build.yml, package.json, scripts/merge-channel-files.js
On every release tag, and [manual trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) when the "**Include builds on non-free runners**" [checkbox](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) is checked, make the Arduino IDE build for native [Apple Silicon](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) host in addition to the builds that are always generated by the "Arduino IDE" GitHub Actions workflow.
Previously, the build workflow only produced a build for x86-64 (AKA "Intel") macOS hosts. Although it is possible to use those builds on Apple Silicon machines via the [Rosetta …
=> Add native Apple Silicon target to build workflow

.eslintrc.js, .github/workflows/build.yml, arduino-ide-extension/src/browser/create/create-api.ts, arduino-ide-extension/src/browser/create/typings.ts, arduino-ide-extension/src/test/browser/create-api.slow-test.ts
Enables the Create API integration tests on the CI.
- Made the tests more resilient,
- Run the Create API integration tests with other slow tests,
- Test the Create API error codes,
- Update the workflow to run the Create API integration tests,
- Relax the linter to ignore `/lib` folders.
Tests run on the CI: https://github.com/arduino/arduino-ide/actions/runs/6417438126/job/17425977420?pr=2092#step:7:649.
=> test: run cloud sketches tests on the CI

.github/workflows/assets/linux.Dockerfile, .github/workflows/build.yml, .github/workflows/check-containers.yml, .github/workflows/push-container-images.yml
The Linux build of Arduino IDE is [dynamically linked](https://en.wikipedia.org/wiki/Dynamic_linker) against the [libstdc++](https://gcc.gnu.org/onlinedocs/libstdc++/) and [glibc](https://www.gnu.org/software/libc/) shared libraries. This results in it having a dependency on the version of the libraries that happen to be present in the environment it is built in.
Although [newer versions of the shared libraries are compatible with executables linked against an older version](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html#abi.versioning.goals), the reverse is not true. This means that building Arduino IDE on a Linux machine with a recent distro version installed causes the IDE to error on startup for users who have a distro with older versions of the dependencies …
=> Make Linux build in a container for compatibility with older distros

.github/workflows/build.yml
The "Arduino IDE" GitHub Actions workflow is used to generate several distinct types of builds:
- Tester builds of commits
- Nightly builds
- Release builds
Different operations must be performed depending on which type of build is being produced. The workflow uses dedicated [jobs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs) for publishing the nightly builds and for publishing the release builds. Those jobs are [configured to run only when certain criteria are met](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif).
One such criteria is that the `merge-channel-files` job ran as expected. There are [four possible result types of a job](https://docs.github.com/en/actions/learn-github-actions/cont …
=> Correct conditional logic for publishing steps of build workflow

.github/workflows/assets/linux.Dockerfile
A Docker container is used to produce the Linux build of Arduino IDE.
The dependencies of the build are pinned to a specific version in the Dockerfile in order to ensure a stable environment in the images.
One such dependency is Git. The [version of Git available from the package repository of the Ubuntu 18.04 distro](https://launchpad.net/ubuntu/bionic/+source/git) used for the image is too outdated to be used for this purpose. For this reason, [a PPA](https://git-scm.com/download/linux#:~:text=For%20Ubuntu%2C%20this%20PPA%20provides%20the%20latest%20stable%20upstream%20Git%20version) is used as the source for the Git package.
On the last test build of the image, the installation of the `git=1:2.42.0-0ppa1~ubuntu18.04.1` package failed: …
=> Remove version pin of Git dependency in Linux build container Dockerfile

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Can open IDE2 from an ino file.
Use a fallback frontend app config when starting IDE2 from an ino file
(from Explorer, Finder, etc.) and the app config is not yet set.
See the [Beta Testing Guide](https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md) on how to verify the changes.
Preconditions:
- make sure the tester build is your default app to open ino files (On macOS, I had to wipe all previous IDE2 versions)
- download the tester build,
- start the IDE2 from its app icon (it starts),
- open more than one sketch and quit,
- start the IDE2 from its app icon (it starts, all previously opened (saved!) sketch windows open),
- quit IDE,
- open IDE2 by double clicking on an ino file (in Explorer, Finder, etc.) (it opens the sketch),
- quit …
=> fix: can open IDE2 from an ino file

arduino-ide-extension/src/browser/dialogs/certificate-uploader/certificate-uploader-component.tsx, arduino-ide-extension/src/browser/dialogs/certificate-uploader/select-board-components.tsx, arduino-ide-extension/src/browser/dialogs/firmware-uploader/firmware-uploader-component.tsx
When the previously selected board is not detected, unset the `<select>` option.
Closes #2222
=> fix: board `<select>` update on board detach

arduino-ide-extension/scripts/download-examples.js
The Arduino IDE installation includes a collection of example sketches demonstrating fundamental concepts.
These examples are hosted in a dedicated repository, which is a dependency of this project. A new release has been made in that `arduino/arduino-examples` repository:
https://github.com/arduino/arduino-examples/releases/tag/1.10.1
Bump the version of the `arduino/arduino-examples` dependency in the download script so that the latest version of the examples will be bundled with the Arduino IDE installation.
Related:
- https://github.com/arduino/arduino-ide/pull/1519
- https://github.com/arduino/arduino-ide/pull/383
=> Bump built-in example sketches version to 1.10.1

.vscode/settings.json, arduino-ide-extension/package.json
- IDE2 should use the `0.35.1` of the Arduino CLI.
- Use the latest (`>=1.85`) preferred value of the `source.fixAll.eslint` VS Code settings.
- Pinned the CLI version,
- Update the shared `settings.json` file
Closes arduino/arduino-ide#2318
=> chore: pinned Arduino CLI `0.35.1`

arduino-ide-extension/scripts/download-fwuploader.js
A separate build of Arduino IDE is produced for each of the macOS host architectures:
* Apple Silicon (ARM)
* Intel (x86)
The Arduino IDE distribution includes several bundled helper tools. The build of those tools should also be selected according to the target host architecture.
At the time the infrastructure was set up for bundling the "Arduino Firmware Uploader" tool with the Arduino IDE distribution, that tool was only produced in a macOS x86 variant. So this was used even in the Apple Silicon Arduino IDE distribution, relying on Rosetta 2 to provide compatibility when used on Apple Silicon machines. Since that time, the Arduino Firmware Uploader build infrastructure has been updated to produce an Apple Silicon build of the tool …
=> Bundle native Arduino Firmware Uploader with Apple Silicon build

arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/browser/style/debug.css, arduino-ide-extension/src/browser/theia/debug/debug-configuration-widget.tsx, arduino-ide-extension/src/browser/theia/debug/debug-widget.ts
Improve communication of no debugger support when accessed via the activity bar
https://github.com/arduino/arduino-ide/assets/1405703/713a8533-1503-476b-b9e0-8b1cec88084a
- Disable the debug widget if the debugging is unsupported by the selected board + programmer + config options triplet. If debugging is unsupported, the message is the same as in the toolbar.
- Remove the 'Add configuration...' select option from the debug widget.
Closes #14
=> feat: disable debug widget if unsupported by board

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/contributions/ino-language.ts, electron-app/package.json, i18n/en.json
Added a new preference (`arduino.language.asyncWorkers`) to control the number of async workers used by `clangd`.
Users can use fine tune the `clangd` thread count to overcome excessive CPU usage.
- use `0.1.2` Arduino Tools VSIX,
- use `0.35.2` CLI,
- use `0.7.6` Arduino LS,
- new preference to control the `clangd` thread count per sketch
Ref: arduino/arduino-language-server#177
Ref: arduino/vscode-arduino-tools#46
=> feat: preference to limit thread count of the LS

arduino-ide-extension/package.json, electron-app/package.json, package.json
The version number must be increased before the next release. See the [docs](https://github.com/arduino/arduino-ide/blob/main/docs/internal/release-procedure.md#3--check-version-of-packages).
Bump version from `2.2.2` to `2.3.0`
=> chore: use version `2.3.0` for the next release

arduino-ide-extension/package.json, electron-app/package.json, package.json
Produce the nightly builds (and IDE2 updates) with the correct `2.3.1-nightly*` version.
Bump version from `2.3.0` to `2.3.1`
See the [documentation](https://github.com/arduino/arduino-ide/blob/1b9c7e93e029e65765010eb84e1604b5e483a963/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) for more details on why we have to do this or reference a previous after-release version metadata bump PR [here](https://github.com/arduino/arduino-ide/pull/1923).
=> chore: switch to version `2.3.1` after the release

arduino-ide-extension/src/browser/theia/debug/debug-widget.ts, arduino-ide-extension/src/browser/theia/dialogs/widgets.ts, arduino-ide-extension/src/test/browser/widgets.test.ts
Fix the empty _Debug_ widget issue in IDE2.
Use customized `PanelLayout#removeWidget` and
`PanelLayout#insertWidget` logic for the layout
updates. The customized functions ensure no side
effect if adding/removing the widget to/from the
layout but it's already present/absent.
Unlike the default [`PanelLayout#removeWidget`](https://github.com/phosphorjs/phosphor/blob/9f5e11025b62d2c4a6fb59e2681ae1ed323dcde4/packages/widgets/src/panellayout.ts#L154-L156) behavior,
do not try to remove the widget if it's
not present (has a negative index). Otherwise,
required widgets might be removed based on the
default [`ArrayExt#removeAt`](https://github.com/phosphorjs/phosphor/blob/9f5e11025b62d2c4a6fb59e2681ae1ed323dcde4/packages/algorithm/src/array.ts#L1075-L1077) behavior.
Closes: …
=> fix: debug widget layout updates

package.json, yarn.lock
Fix all security issues reported by Dependabot and `yarn audit`.
Resolutions:
- `nano@^10.1.3`,
- `msgpackr@^1.10.1`,
- `axios@^1.6.7`
Fixes:
- [GHSA-wf5p-g6vw-rhxx](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx) (`CVE-2023-45857`)
- [GHSA-jchw-25xp-jwwc](https://github.com/advisories/GHSA-jchw-25xp-jwwc) (`CVE-2023-26159`)
- [GHSA-7hpj-7hhx-2fgx](https://github.com/advisories/GHSA-7hpj-7hhx-2fgx) (`CVE-2023-52079`)
Ref: nrwl/nx#20493
Ref: eclipse-theia/theia#13365
=> fix(security): update all vulnerable dependencies

arduino-ide-extension/package.json, electron-app/package.json, package.json
Produce the nightly builds (and IDE2 updates) with the correct `2.3.2-nightly*` version.
Bump version from `2.3.1` to `2.3.2`
See the [documentation](https://github.com/arduino/arduino-ide/blob/1b9c7e93e029e65765010eb84e1604b5e483a963/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) for more details on why we have to do this or reference a previous after-release version metadata bump PR [here](https://github.com/arduino/arduino-ide/pull/2356).
=> chore: switch to version `2.3.2` after the release

package.json, yarn.lock
Update [`ip`](https://www.npmjs.com/package/ip) to fix security vulnerability CVE-2023-42282.
Refs:
- https://github.com/advisories/GHSA-78xj-cgh5-2h22
- https://github.com/indutny/node-ip/commit/32f468f1245574785ec080705737a579be1223aa
=> fix(security): use `ip@2.0.1` for CVE-2023-42282

.github/workflows/build.yml, .github/workflows/check-i18n-task.yml, .github/workflows/i18n-nightly-push.yml, .github/workflows/i18n-weekly-pull.yml, .github/workflows/themes-weekly-pull.yml, arduino-ide-extension/package.json, arduino-ide-extension/src/browser/contributions/debug.ts, arduino-ide-extension/src/common/protocol/boards-service.ts, arduino-ide-extension/src/node/boards-service-impl.ts, arduino-ide-extension/src/test/browser/debug.test.ts, electron-app/package.json, i18n/en.json
Allow debugging when the platform supports it but has no programmer.
- No premature error when checking whether debugging is supported for a board without a selected programmer. This should help platforms without a programmer to keep the debug functionality. (https://github.com/arduino/arduino-ide/issues/2368#issuecomment-1945593840, https://github.com/earlephilhower/arduino-pico/issues/2003),
- Update Arduino Tools VSIX version to `0.1.3`.
- CI: use `go@1.21` to build the CLI on the fly from a commitish.
Ref: arduino/arduino-cli#2540
Ref: arduino/vscode-arduino-tools#47 
Closes: arduino/arduino-ide#2368
=> fix: no required `programmer` for `debug --info`

arduino-ide-extension/package.json, electron-app/package.json, package.json
Produce the nightly builds (and IDE2 updates) with the correct `2.3.3-nightly*` version.
Bump version from `2.3.2` to `2.3.3`
See the [documentation](https://github.com/arduino/arduino-ide/blob/1b9c7e93e029e65765010eb84e1604b5e483a963/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) for more details on why we have to do this or reference a previous after-release version metadata bump PR [here](https://github.com/arduino/arduino-ide/pull/2369).
=> chore: switch to version `2.3.3` after the release

arduino-ide-extension/src/node/sketches-service-impl.ts, arduino-ide-extension/src/test/node/sketches-service-impl.slow-test.ts
Fix the examples opening with the `.pde` main sketch file extension.
https://github.com/arduino/arduino-ide/assets/1405703/04467b9a-ac07-4d9d-8358-6e3608bd9be4
Do not assume the `.ino` extension for the main sketch file when copying a sketch.
Closes arduino/arduino-ide#2377
=> fix: copy example with `.pde` main sketch file

arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/common/protocol/core-service.ts, arduino-ide-extension/src/node/core-service-impl.ts, arduino-ide-extension/src/node/service-error.ts
https://github.com/arduino/arduino-ide/issues/103
1. Add utility to map grcp errors to custom generated CLI errors
2. If default upload fails with `ProgrammerIsRequiredForUploadError` , perform upload request again using selected programmer
=> feat: upload using programmer by default if board requires it

.github/workflows/build.yml
We noticed the CI builds are no longer producing artifacts for intel mac.
This is due to the fact that Github Actions runners referenced with "macos-latest", i.e. MacOS v14 OS runners, will now default to arm systems.
At the moment the only intel based Mac OS 14 runner image is `macos-14-large` ([ref](https://github.com/actions/runner-images/issues/9741#issuecomment-2075259811)) which is a paid solution.
We've decided to change the referenced image to "macos-13" as a work-around, to start reproducing the intel builds of IDE 2.x whilst avoiding additional cost.
Change the referenced image to "macos-13" in `build.yml`
https://github.com/actions/runner-images/issues/9741
=> Use `macos-13` for Intel build

.github/workflows/build.yml
MacOS ARM build does not required a paid build solution anymore as `macos-latest` workflow uses Apple silicon machines by default.
=> Use `macos-latest` runner for macOS ARM build

arduino-ide-extension/src/node/service-error.ts
Fixes #2516
Prevent parsing metadata from CLI errors when no metadata items present.
Minor changes:
- Use `getTypeName` instead of `getTypeUrl` to parse grpc error
- Add type assertion to `isInstanceOf` function
=> fix: prevent parsing CLI errors without metadata

docs/development.md
When the IDE depends on a non-released version of the Arduino CLI, LS, etc., tools, it must check out the corresponding pinned commit from Git and build them from the sources. This process requires Go, but it's preferable to use [taskfile](https://taskfile.dev/) for the correct timestamps and dev versions. This pull request refers to the existing documentation of the Arduino CLI, and it should be sufficient to build all other binaries.
Document prerequisites of the Arduino CLI, LS, etc. tools when built from a Git commitish.
The preview version of the change: https://github.com/arduino/arduino-ide/blob/fda5a5f7714aea8fb4c447fa650e839a1473553d/docs/development.md#prerequisites.
closes: arduino/arduino-ide#2499
=> fix(doc): add missing prerequisites to dev docs

.github/workflows/build.yml, electron-app/scripts/windowsCustomSign.js
Disable windows signing for pull requests coming from forks.
Resolves https://github.com/arduino/arduino-ide/issues/2545
=> fix: disable local windows signing for external contributions

.github/workflows/build.yml
The Windows builds of the application are cryptographically signed. The signing requires an "eToken" hardware authentication device be connected to the machine performing the signing (https://github.com/arduino/arduino-ide/pull/2452). This means that it is necessary to use a [self-hosted GitHub Actions runner](https://docs.github.com/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) for the Windows job of the build workflow rather than the [runners hosted by GitHub](https://docs.github.com/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners).
There are some unique characteristics of the self-hosted runner which the workflow code must accommodate. The default working directory of the self-hosted runner is not …
=> Simplify and generalize configurable working directory code in build workflow

.github/workflows/build.yml
The Windows builds of the application are cryptographically signed. The signing requires an "eToken" hardware authentication device be connected to the machine performing the signing. This means that it is necessary to use a [self-hosted GitHub Actions runner](https://docs.github.com/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) for the Windows job of the build workflow rather than the [runners hosted by GitHub](https://docs.github.com/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners) (https://github.com/arduino/arduino-ide/pull/2452).
There are some unique characteristics of the self-hosted runner which the workflow code must accommodate. One of these is that, rather than installing dependencies of the …
=> Use appropriate indicator for dependency installation conditionals in build workflow

.github/workflows/build.yml
The "build" workflow builds the application for a range of target hosts. This is done by using a [job matrix](https://docs.github.com/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix). A separate parallel job runs for each target. The target-specific configuration data is defined in the job matrix array.
This configuration data includes the information related to the code signing certificates. Inexplicably, during the work to add support for signing the Windows builds with an "eToken" hardware authentication device (https://github.com/arduino/arduino-ide/pull/2452), this data was not used for the Windows code signing configuration. Instead the certificate data was redundantly hardcoded into the workflow code.
Use the established flexible job …
=> Get job-specific configuration from matrix in build workflow

.github/workflows/build.yml, electron-app/scripts/windowsCustomSign.js
The "build" workflow signs the macOS and Windows builds of the application. The signing process relies on access to [GitHub Actions secrets](https://docs.github.com/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions). For this reason, the workflow is configured to only sign the builds when it has access to GitHub Actions secrets to avoid spurious failures of the workflow that would otherwise be caused by signing failure.
A flexible general purpose system for accurately determining whether to attempt signing of a build was established years ago (https://github.com/arduino/arduino-ide/pull/1115) However, when the Windows signing system was reworked to support the new "eToken" hardware authenticator-based approach …
=> Remove inaccurate and redundant signing determination code from build system

.github/workflows/build.yml, .github/workflows/check-javascript.yml, .github/workflows/check-yarn.yml, .github/workflows/test-javascript.yml, README.md
The "build" workflow builds the application for all supported targets, generates workflow artifacts from which the builds can be downloaded by users and [beta testers](https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md), and publishes [nightly](https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md#testing-nightly-build) and production releases.
As if that wasn't enough, additional operations unrelated to building the application were jammed into the workflow:
* Lint code
* Run tests
* [Check for out of sync Yarn lockfile](https://yarnpkg.com/cli/install#options-immutable)
This monolithic approach is harmful for multiple reasons:
* Makes it difficult to interpret a failed workflow run
* Unnecessarily adds a significant …
=> Move non-build tasks to dedicated GitHub Actions workflows

arduino-ide-extension/package.json, arduino-ide-extension/scripts/generate-protocol.js, arduino-ide-extension/src/node/sketches-service-impl.ts, electron-app/scripts/post-package.js, yarn.lock
Update `glob` version to fix memory leak issue
See https://github.com/isaacs/node-glob/issues/435
Use  `glob` version 10 as the highest compatible with IDE node version
Closes https://github.com/arduino/arduino-ide/issues/2537
=> fix: memory leak when scanning sketchbooks with large files

arduino-ide-extension/package.json, arduino-ide-extension/src/browser/arduino-ide-frontend-module.ts, arduino-ide-extension/src/browser/theia/plugin-ext/tree-view-widget.tsx, arduino-ide-extension/src/node/arduino-ide-backend-module.ts, arduino-ide-extension/src/node/theia/plugin-ext-vscode/scanner-vscode.ts
This PR patches the default behavior of the [viewsWelcome](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome) and aligns it to VS Code, most notably, it honors the `enablement` property of the `viewsWelcome` contribution (https://github.com/eclipse-theia/theia/issues/14309) to provide dynamic UX via a [VS Code when context](https://code.visualstudio.com/api/references/when-clause-contexts).
Originally from the [Arduino Forum](https://forum.arduino.cc/t/porting-a-code-generator-plugin-to-ide-2-3/1306804/10):
> I know it's just static info with links... but if could it could be dynamic, the ideal GUI would disable the 3 sketch buttons until the key is created.
https://github.com/user-attachments/assets/34771537-a477-4922-95c3-fe4b5a7e6dad
- patches …
=> fix: align `viewsWelcome` behavior to VS Code

arduino-ide-extension/src/browser/arduino-preferences.ts, arduino-ide-extension/src/browser/contributions/upload-sketch.ts, arduino-ide-extension/src/browser/contributions/verify-sketch.ts, i18n/en.json
From [here](https://forum.arduino.cc/t/add-an-option-to-upload-without-recompiling/1213940):
> For example, I'm now developing using for an ESP32. It requires that I hold down the EN button to put the board into the correct mode to accept the download. It's a tiny button that's hard to hold down, and if I forget to push it or accidentally release it too soon, I'm forced to wait for a long compile before I can try it again.
> I also need to program three of these boards with identical code. Again, I have to sit and wait through multiple compiles that produce exactly the same binary.
This PR adds a new preference to control whether the verify command should automatically run before the upload. If the `arduino.upload.autoVerify` setting value is `false`, IDE does not recompile the sketch …
=> feat: can skip verify before upload

arduino-ide-extension/package.json, arduino-ide-extension/scripts/generate-protocol.js
- Use Arduino CLI `v1.1.1`
- Use `arduino_cli_{version}_proto.zip` to generate CLI binding for official releases
Since https://github.com/arduino/arduino-cli/pull/2673 google profile have been removed from source so the generation script is now fetching proto files from the `arduino_cli_{version}_proto.zip` file generated for every release as it includes the google proto files, see https://github.com/arduino/arduino-cli/pull/2761
Fetching protos from source is still used if a specific `commitsh` is provided or is CLI version is 1.1.0, see https://github.com/arduino/arduino-cli/issues/2755
In this case, google proto are fetched separately from [arduino_cli_1.1.1_proto.zip](https://downloads.arduino.cc/arduino-cli/arduino-cli_1.1.1_proto.zip) and copied to the source folder.
=> feat: Use Arduino CLI v1.1.1

arduino-ide-extension/package.json, electron-app/package.json, package.json
Motivation
Produce the nightly builds (and IDE2 updates) with the correct 2.3.5-nightly* version.
Change description
Bump version from 2.3.4 to 2.3.5
To produce a correctly versioned nightly build.
See the [docs](https://github.com/arduino/arduino-ide/blob/1b9c7e93e029e65765010eb84e1604b5e483a963/docs/internal/release-procedure.md#7-%EF%B8%8F-bump-version-metadata-of-packages) for more details.
=> chore: switch to version `2.3.5` after the release

.github/workflows/check-i18n-task.yml, .github/workflows/check-javascript.yml, .github/workflows/check-yarn.yml, .github/workflows/i18n-nightly-push.yml, .github/workflows/i18n-weekly-pull.yml, .github/workflows/test-javascript.yml, .github/workflows/themes-weekly-pull.yml
Ubuntu 24.04 is the new default version for Ubuntu latest runner https://github.com/actions/runner-images/issues/10636
Ubuntu 24.04 no longer includes the following dependencies:
- `libx11-dev`, `libxkbfile-dev` required by `native-keymap`
- `libsecret-1-dev` required by `keytar` package.
Note that `keytar` is now deprecated and it's a dependency on both IDE2 and Theia https://github.com/eclipse-theia/theia/issues/13593
Manually install missing dependencies in CI workflows only for Linux
Adopted in favour of https://github.com/arduino/arduino-ide/pull/2649
=> fix: add missing linux dependencies after ubuntu-latest runner update

arduino-ide-extension/scripts/download-examples.js
The Arduino IDE installation includes a collection of example sketches demonstrating fundamental concepts.
These examples are hosted in a dedicated repository, which is a dependency of this project. A new release has been made in that `arduino/arduino-examples` repository:
https://github.com/arduino/arduino-examples/releases/tag/1.10.2
Bump the version of the `arduino/arduino-examples` dependency in the download script so that the latest version of the examples will be bundled with the Arduino IDE installation.
Related:
- https://github.com/arduino/arduino-ide/pull/2322
- https://github.com/arduino/arduino-ide/pull/1519
- https://github.com/arduino/arduino-ide/pull/383
=> Bump built-in example sketches version to 1.10.2

.gitignore, arduino-ide-extension/src/browser/theia/messages/notification-component.tsx
A Cross Site Scripting vulnerability has been found in the notification component.
We're fixing the issue by sanitising the message before showing it in the notification popup
=> fix: sanitize message in notification component

.github/workflows/build.yml
Certain operations in the "Arduino IDE" GitHub Actions workflow use [GitHub Actions secrets](https://docs.github.com/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) which are defined in the repository's administrative settings.
These secrets will typically not be defined when the workflow is run in a [fork](https://docs.github.com/get-started/quickstart/fork-a-repo). However, the workflow's base functionality, the automated building of the application, does not require secrets. Since that base functionality alone is very useful to contributors (either to validate relevant changes to the application and infrastructure, or to generate [tester builds](https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md)) who are …
=> Give build workflow step access to required deployment environment

electron-app/scripts/package.js
Check if electron version parsing is correctly parsed by semver package. Also fix error warning for invalid type
=> fix: safer electron version parsing for electron-builder command

.github/workflows/build.yml
Motivation of this change is the same as https://github.com/arduino/arduino-ide/pull/2647
This specific change has been overlooked in the above PR because `merge-channel-files` runs only when a release is triggered, so the additional error wan't exposed during normal builds. 
Add missing linux dependencies for actions that invokes `yarn install`.
=> fix: add missing linux dependencies for `merge-channel-files` job

.github/workflows/compose-full-changelog.yml
Motivation of this change is the same as https://github.com/arduino/arduino-ide/pull/2647
This specific change has been overlooked in the above PR because `create-changelog`  is skipped during normal builds. 
Add missing linux dependencies for actions that use `yarn`.
=> fix: add missing linux dependencies for `create-changelog` job

arduino-ide-extension/package.json, electron-app/package.json, package.json
=> chore: switch to version `2.3.6` after the release

arduino-ide-extension/src/electron-main/theia/electron-main-application.ts
Resolved https://github.com/arduino/arduino-ide/issues/2678
Propagate argv electron params when starting a second instance
=> fix: propagate electron params in second instance startup

arduino-ide-extension/src/common/utils.ts, arduino-ide-extension/src/electron-main/theia/electron-main-application.ts, electron-app/package.json
Resolves https://github.com/arduino/arduino-ide/issues/2688
Theia internally create an initial empty window on app start to improve UX while first loading the app instance, see https://github.com/eclipse-theia/theia/pull/12897
On MacOS, since open sketch via file association was triggered before initial window reference was set, the open sketch logic would create a new window instance instead of reusing the early created window reference, leaving an unresponsive additional empty window.
The `open-file` event is triggered before the app is ready and `initialWindow` is created, leading to `openSketch`
to create a new window instead of reusing the `initialWindow`.
Currently there is no ideal way to wait or react to `initialWindow` value change, so we pool on the value.
Note that this only …
=> fix: wait for theia `initalWindow` to be set before opening sketch through `open-file` event

arduino-ide-extension/src/electron-main/arduino-electron-main-module.ts
Resolves https://github.com/arduino/arduino-ide/issues/2696
Use `ElectronConnectionHandler` instead of `ConnectionHandler` to establish communication between the frontend and the electron main process. This is needed specifically for services interacting with electron.
The issue seems to appear also on the [Theia IDE example](https://github.com/eclipse-theia/theia/blob/436de3c4571e0000fdcbbf2e94ddfc992f38ccb2/examples/api-samples/src/electron-main/update/sample-updater-main-module.ts#L28). An issue will follow on Theia side.
=> fix: use `ElectronConnectionHandler` to connect the ide updater frontend and the electron main process 
